import { subclass, type SubclassSpec } from './helpers';

/** Subclasses do Caldeirão de Tasha para Todas as Coisas (2020). Sem as do Artífice (classe fora da Open5e). */
const specs: SubclassSpec[] = [
  // Bárbaro
  {
    cls: 'barbarian',
    name: 'Path of the Beast',
    pt: 'Caminho da Fera',
    desc: 'Barbarians whose rage awakens a bestial nature that reshapes their body.',
    ptDesc: 'Bárbaros cuja fúria desperta uma natureza bestial que transforma o corpo.',
    features: [
      [3, 'Form of the Beast', 'Forma da Fera', 'When you rage, grow a natural weapon until the rage ends: Bite (1d8 piercing; once per turn, if below half hit points, regain hit points equal to your proficiency bonus on a hit), Claws (1d6 slashing; one extra claw attack when you attack with them in the Attack action) or Tail (1d8 piercing, reach; as a reaction add 1d8 to your AC against an attack).', 'Ao entrar em fúria, desenvolva uma arma natural até ela acabar: Mordida (1d8 perfurante; uma vez por turno, se estiver abaixo da metade dos PV, recupere PV iguais à proficiência ao acertar), Garras (1d6 cortante; um ataque extra com garra ao atacar com elas na ação Atacar) ou Cauda (1d8 perfurante, alcance; com a reação, some 1d8 à CA contra um ataque).'],
      [6, 'Bestial Soul', 'Alma Bestial', 'Your natural weapons count as magical. After a rest, choose: swim speed and water breathing, climb speed with no checks, or jump distance increased by a d20 roll once per turn.', 'Suas armas naturais contam como mágicas. Depois de um descanso, escolha: natação e respirar na água, escalada sem testes, ou somar 1d20 a um salto uma vez por turno.'],
      [10, 'Infectious Fury', 'Fúria Contagiosa', 'While raging, when you hit with natural weapons, the target makes a Wisdom save or, by your choice, uses its reaction to attack another creature, or takes 2d12 psychic damage. Uses equal to your proficiency bonus per long rest.', 'Em fúria, ao acertar com armas naturais, o alvo faz um teste de Sabedoria ou, à sua escolha, usa a reação para atacar outra criatura, ou sofre 2d12 de dano psíquico. Usos iguais à proficiência por descanso longo.'],
      [14, 'Call the Hunt', 'Chamado da Caçada', 'When you rage, choose up to as many willing creatures as your Constitution modifier within 30 feet: you gain 5 temporary hit points per creature, and once per turn each can deal an extra 1d6 damage on a hit while your rage lasts. Uses equal to your proficiency bonus per long rest.', 'Ao entrar em fúria, escolha até um número de criaturas voluntárias igual ao seu modificador de Constituição a até 9 m: você ganha 5 PV temporários por criatura, e cada uma pode causar 1d6 de dano extra uma vez por turno enquanto a fúria durar. Usos iguais à proficiência por descanso longo.'],
    ],
  },
  {
    cls: 'barbarian',
    name: 'Path of Wild Magic',
    pt: 'Caminho da Magia Selvagem',
    desc: 'Barbarians whose rage releases unpredictable surges of magic.',
    ptDesc: 'Bárbaros cuja fúria libera surtos imprevisíveis de magia.',
    features: [
      [3, 'Magic Awareness', 'Percepção Mágica', 'As an action, sense spells and magic items within 60 feet until the end of your next turn, learning their school. Uses equal to your proficiency bonus per long rest.', 'Com uma ação, perceba magias e itens mágicos a até 18 m até o fim do seu próximo turno, descobrindo a escola deles. Usos iguais à proficiência por descanso longo.'],
      [3, 'Wild Surge', 'Surto Selvagem', 'When you rage, roll on the Wild Magic table (d8): effects include necrotic bursts that heal you, teleporting with each bonus action, a spirit that explodes, a magic weapon that returns, retaliating force, protective lights, flowers and vines that make difficult terrain, or a radiant bolt each turn.', 'Ao entrar em fúria, role na tabela de Magia Selvagem (d8): os efeitos incluem explosões necróticas que curam você, teletransporte a cada ação bônus, um espírito que explode, uma arma mágica que volta, retaliação de energia, luzes protetoras, flores e trepadeiras que criam terreno difícil ou um raio radiante a cada turno.'],
      [6, 'Bolstering Magic', 'Magia Fortalecedora', 'As an action, touch a creature: it adds 1d3 to attack rolls and ability checks for 10 minutes, or regains a spell slot of level 1d3 or lower. Uses equal to your proficiency bonus per long rest.', 'Com uma ação, toque numa criatura: ela soma 1d3 em ataques e testes de atributo por 10 minutos, ou recupera um espaço de magia de círculo 1d3 ou menor. Usos iguais à proficiência por descanso longo.'],
      [10, 'Unstable Backlash', 'Reação Instável', 'When you take damage or fail a save while raging, you can use your reaction to roll on the Wild Magic table, replacing the current effect.', 'Quando sofrer dano ou falhar num teste de resistência em fúria, você pode usar a reação para rolar de novo na tabela de Magia Selvagem, trocando o efeito atual.'],
      [14, 'Controlled Surge', 'Surto Controlado', 'When you roll on the Wild Magic table, you roll twice and choose the effect (rolling the same number lets you choose any effect).', 'Ao rolar na tabela de Magia Selvagem, você rola duas vezes e escolhe o efeito (resultados iguais deixam escolher qualquer efeito).'],
    ],
  },
  // Bardo
  {
    cls: 'bard',
    name: 'College of Creation',
    pt: 'Colégio da Criação',
    desc: 'Bards who channel the Song of Creation to bring things into being.',
    ptDesc: 'Bardos que canalizam a Canção da Criação para trazer coisas à existência.',
    features: [
      [3, 'Mote of Potential', 'Partícula de Potencial', 'A creature that receives your Bardic Inspiration also gets a mote: ability check (roll the die twice, keep either), attack (thunder burst for the die roll to nearby creatures on a Constitution save) or save (temporary hit points equal to the roll + Charisma).', 'Quem recebe sua Inspiração de Bardo também ganha uma partícula: teste de atributo (rola o dado duas vezes e escolhe), ataque (explosão trovejante com o valor do dado em quem estiver perto, teste de Constituição) ou resistência (PV temporários iguais ao dado + Carisma).'],
      [3, 'Performance of Creation', 'Apresentação da Criação', 'As an action, create a nonmagical item worth up to 20 × your bard level gp, of size Medium (Large at 6th, Huge at 14th), lasting a number of hours equal to your proficiency bonus. Once per long rest, or by spending a 2nd-level slot.', 'Com uma ação, crie um item não mágico de até 20 × nível de bardo em PO, de tamanho Médio (Grande no 6, Enorme no 14), que dura horas iguais à proficiência. Uma vez por descanso longo, ou gastando um espaço de 2º círculo.'],
      [6, 'Animating Performance', 'Apresentação Animada', 'As an action, animate a Large or smaller nonmagical item as a Dancing Item that obeys you for 1 hour, acting on your turn. Once per long rest, or by spending a 3rd-level slot.', 'Com uma ação, anime um item não mágico Grande ou menor como um Item Dançante que obedece você por 1 hora e age no seu turno. Uma vez por descanso longo, ou gastando um espaço de 3º círculo.'],
      [14, 'Creative Crescendo', 'Crescendo Criativo', 'When you use Performance of Creation, you can create a number of items equal to your Charisma modifier, one of them of any size, and the value limit no longer applies.', 'Ao usar a Apresentação da Criação, você pode criar um número de itens igual ao modificador de Carisma, um deles de qualquer tamanho, e o limite de valor deixa de valer.'],
    ],
  },
  {
    cls: 'bard',
    name: 'College of Eloquence',
    pt: 'Colégio da Eloquência',
    desc: 'Bards who master the art of persuasion and rhetoric.',
    ptDesc: 'Bardos que dominam a arte da persuasão e da retórica.',
    features: [
      [3, 'Silver Tongue', 'Língua de Prata', 'When you make a Persuasion or Deception check, treat a d20 roll of 9 or lower as a 10.', 'Ao fazer um teste de Persuasão ou Enganação, trate um resultado de 9 ou menos no d20 como 10.'],
      [3, 'Unsettling Words', 'Palavras Perturbadoras', 'As a bonus action, spend a Bardic Inspiration die on a creature within 60 feet: it subtracts the roll from its next saving throw before your next turn.', 'Com uma ação bônus, gaste um dado de Inspiração de Bardo numa criatura a até 18 m: ela subtrai o resultado do próximo teste de resistência antes do seu próximo turno.'],
      [6, 'Unfailing Inspiration', 'Inspiração Infalível', 'When a creature adds your Bardic Inspiration die and fails, it keeps the die.', 'Quando uma criatura soma seu dado de Inspiração de Bardo e falha, ela continua com o dado.'],
      [6, 'Universal Speech', 'Fala Universal', 'As an action, up to as many creatures as your Charisma modifier within 60 feet can understand you for 1 hour. Once per long rest, or by spending a spell slot.', 'Com uma ação, até um número de criaturas igual ao seu modificador de Carisma a até 18 m passa a entender você por 1 hora. Uma vez por descanso longo, ou gastando um espaço de magia.'],
      [14, 'Infectious Inspiration', 'Inspiração Contagiosa', 'When a creature succeeds using your Bardic Inspiration, you can use your reaction to give a die to another creature within 60 feet without spending one. Uses equal to your Charisma modifier per long rest.', 'Quando uma criatura tem sucesso usando sua Inspiração de Bardo, você pode usar a reação para dar um dado a outra criatura a até 18 m sem gastar um. Usos iguais ao modificador de Carisma por descanso longo.'],
    ],
  },
  // Clérigo
  {
    cls: 'cleric',
    name: 'Order Domain',
    pt: 'Domínio da Ordem',
    desc: 'Clerics of law who command allies and enforce discipline.',
    ptDesc: 'Clérigos da lei que comandam aliados e impõem disciplina.',
    features: [
      [[1, 3, 5, 7, 9], 'Domain Spells', 'Magias de Domínio', 'Always prepared: Command, Heroism (1st); Hold Person, Zone of Truth (3rd); Mass Healing Word, Slow (5th); Compulsion, Locate Creature (7th); Commune, Dominate Person (9th).', 'Sempre preparadas: Comando, Heroísmo (1º); Imobilizar Pessoa, Zona da Verdade (3º); Palavra Curativa em Massa, Lentidão (5º); Compulsão, Localizar Criatura (7º); Comunhão, Dominar Pessoa (9º).'],
      [1, 'Bonus Proficiencies', 'Proficiências Adicionais', 'You gain proficiency with heavy armor and in Intimidation or Persuasion.', 'Você ganha proficiência com armaduras pesadas e em Intimidação ou Persuasão.'],
      [1, 'Voice of Authority', 'Voz da Autoridade', 'When you cast a spell of 1st level or higher targeting an ally, that ally can use its reaction to make one weapon attack against a creature of your choice it can see.', 'Ao conjurar uma magia de 1º círculo ou maior que tenha um aliado como alvo, esse aliado pode usar a reação para fazer um ataque com arma contra uma criatura à sua escolha que ele veja.'],
      [2, 'Channel Divinity: Order’s Demand', 'Canalizar Divindade: Exigência da Ordem', 'As an action, creatures of your choice within 30 feet make a Wisdom save or are charmed until the end of your next turn, and may drop what they hold.', 'Com uma ação, criaturas à sua escolha a até 9 m fazem um teste de Sabedoria ou ficam enfeitiçadas até o fim do seu próximo turno, podendo largar o que seguram.'],
      [6, 'Embodiment of the Law', 'Personificação da Lei', 'When you cast an enchantment spell of 1st level or higher, you can cast it as a bonus action if its casting time is an action. Uses equal to your Wisdom modifier per long rest.', 'Ao conjurar uma magia de encantamento de 1º círculo ou maior com tempo de 1 ação, você pode conjurá-la com ação bônus. Usos iguais ao modificador de Sabedoria por descanso longo.'],
      [[8, 14], 'Divine Strike', 'Golpe Divino', 'Once per turn, your weapon hits deal an extra 1d8 psychic damage (2d8 at 14th level).', 'Uma vez por turno, seus acertos com arma causam 1d8 de dano psíquico extra (2d8 no nível 14).'],
      [17, 'Order’s Wrath', 'Ira da Ordem', 'When your Divine Strike hits, you can curse the target: the next time an ally hits it before your next turn, it takes an extra 2d8 psychic damage.', 'Quando seu Golpe Divino acerta, você pode amaldiçoar o alvo: na próxima vez que um aliado o acertar antes do seu próximo turno, ele sofre 2d8 de dano psíquico extra.'],
    ],
  },
  {
    cls: 'cleric',
    name: 'Peace Domain',
    pt: 'Domínio da Paz',
    desc: 'Clerics who forge bonds between allies so they protect one another.',
    ptDesc: 'Clérigos que criam laços entre aliados para que protejam uns aos outros.',
    features: [
      [[1, 3, 5, 7, 9], 'Domain Spells', 'Magias de Domínio', 'Always prepared: Heroism, Sanctuary (1st); Aid, Warding Bond (3rd); Beacon of Hope, Sending (5th); Aura of Purity, Otiluke’s Resilient Sphere (7th); Greater Restoration, Rary’s Telepathic Bond (9th).', 'Sempre preparadas: Heroísmo, Santuário (1º); Auxílio, Elo Protetor (3º); Sinal de Esperança, Mensagem (5º); Aura de Pureza, Esfera Resiliente de Otiluke (7º); Restauração Maior, Elo Telepático de Rary (9º).'],
      [1, 'Implement of Peace', 'Instrumento da Paz', 'You gain proficiency in Insight, Performance or Persuasion.', 'Você ganha proficiência em Intuição, Atuação ou Persuasão.'],
      [1, 'Emboldening Bond', 'Elo Encorajador', 'As an action, bond up to as many willing creatures as your proficiency bonus within 30 feet for 10 minutes. Once per turn, a bonded creature within 30 feet of another can add 1d4 to an attack, check or save. Uses equal to your proficiency bonus per long rest.', 'Com uma ação, crie um elo entre até um número de criaturas voluntárias igual à proficiência a até 9 m, por 10 minutos. Uma vez por turno, uma criatura do elo a até 9 m de outra pode somar 1d4 a um ataque, teste ou resistência. Usos iguais à proficiência por descanso longo.'],
      [2, 'Channel Divinity: Balm of Peace', 'Canalizar Divindade: Bálsamo da Paz', 'As an action, move up to your speed without provoking opportunity attacks; each creature of your choice you pass within 5 feet of regains 2d6 + Wisdom hit points.', 'Com uma ação, mova-se até o seu deslocamento sem provocar ataques de oportunidade; cada criatura à sua escolha por quem você passar a 1,5 m recupera 2d6 + Sabedoria em PV.'],
      [6, 'Protective Bond', 'Elo Protetor', 'When a bonded creature is about to take damage, another bonded creature within 30 feet can use its reaction to teleport next to it and take all the damage instead.', 'Quando uma criatura do elo vai sofrer dano, outra do elo a até 9 m pode usar a reação para se teletransportar para perto e sofrer todo o dano no lugar dela.'],
      [8, 'Potent Spellcasting', 'Conjuração Potente', 'Add your Wisdom modifier to the damage of your cleric cantrips.', 'Some o modificador de Sabedoria ao dano dos seus truques de clérigo.'],
      [17, 'Expansive Bond', 'Elo Expansivo', 'The bond’s range becomes 60 feet, and a creature that takes damage through Protective Bond has resistance to it.', 'O alcance do elo vira 18 m, e quem sofre dano pelo Elo Protetor tem resistência a ele.'],
    ],
  },
  {
    cls: 'cleric',
    name: 'Twilight Domain',
    pt: 'Domínio do Crepúsculo',
    desc: 'Clerics who guard the night and give comfort and rest to the weary.',
    ptDesc: 'Clérigos que guardam a noite e dão conforto e descanso aos cansados.',
    features: [
      [[1, 3, 5, 7, 9], 'Domain Spells', 'Magias de Domínio', 'Always prepared: Faerie Fire, Sleep (1st); Moonbeam, See Invisibility (3rd); Aura of Vitality, Leomund’s Tiny Hut (5th); Aura of Life, Greater Invisibility (7th); Circle of Power, Mislead (9th).', 'Sempre preparadas: Fogo das Fadas, Sono (1º); Raio Lunar, Ver o Invisível (3º); Aura de Vitalidade, Pequena Cabana de Leomund (5º); Aura de Vida, Invisibilidade Maior (7º); Círculo de Poder, Enganar (9º).'],
      [1, 'Bonus Proficiencies', 'Proficiências Adicionais', 'You gain proficiency with martial weapons and heavy armor.', 'Você ganha proficiência com armas marciais e armaduras pesadas.'],
      [1, 'Eyes of Night', 'Olhos da Noite', 'You have darkvision 300 feet. As an action, share it with up to as many willing creatures as your Wisdom modifier within 10 feet for 1 hour, once per long rest (or by spending a spell slot).', 'Você tem visão no escuro de 90 m. Com uma ação, compartilhe-a com até um número de criaturas voluntárias igual ao modificador de Sabedoria a até 3 m por 1 hora, uma vez por descanso longo (ou gastando um espaço de magia).'],
      [1, 'Vigilant Blessing', 'Bênção Vigilante', 'As an action, give one creature advantage on its next initiative roll.', 'Com uma ação, dê a uma criatura vantagem na próxima jogada de iniciativa.'],
      [2, 'Channel Divinity: Twilight Sanctuary', 'Canalizar Divindade: Santuário do Crepúsculo', 'As an action, create a 30-foot sphere of dim light around you for 1 minute. When a creature ends its turn inside, you can give it 1d6 + cleric level temporary hit points or end a charmed or frightened effect on it.', 'Com uma ação, crie uma esfera de 9 m de penumbra ao seu redor por 1 minuto. Quando uma criatura termina o turno dentro dela, você pode dar 1d6 + nível de clérigo em PV temporários ou encerrar um efeito de enfeitiçado ou amedrontado nela.'],
      [6, 'Steps of Night', 'Passos da Noite', 'As a bonus action in dim light or darkness, gain a flying speed equal to your walking speed for 1 minute. Uses equal to your proficiency bonus per long rest.', 'Com uma ação bônus, em penumbra ou escuridão, ganhe deslocamento de voo igual ao seu deslocamento por 1 minuto. Usos iguais à proficiência por descanso longo.'],
      [[8, 14], 'Divine Strike', 'Golpe Divino', 'Once per turn, your weapon hits deal an extra 1d8 radiant damage (2d8 at 14th level).', 'Uma vez por turno, seus acertos com arma causam 1d8 de dano radiante extra (2d8 no nível 14).'],
      [17, 'Twilight Shroud', 'Manto do Crepúsculo', 'You and your allies have half cover while in your Twilight Sanctuary.', 'Você e seus aliados têm meia cobertura dentro do seu Santuário do Crepúsculo.'],
    ],
  },
  // Druida
  {
    cls: 'druid',
    name: 'Circle of Spores',
    pt: 'Círculo dos Esporos',
    desc: 'Druids who embrace decay and the fungal cycle of death and rebirth.',
    ptDesc: 'Druidas que abraçam a decomposição e o ciclo fúngico de morte e renascimento.',
    features: [
      [[2, 3, 5, 7, 9], 'Circle Spells', 'Magias do Círculo', 'You learn Chill Touch, and always have prepared: Blindness/Deafness, Gentle Repose (3rd); Animate Dead, Gaseous Form (5th); Blight, Confusion (7th); Cloudkill, Contagion (9th).', 'Você aprende Toque Arrepiante e sempre tem preparadas: Cegueira/Surdez, Repouso Tranquilo (3º); Animar Mortos, Forma Gasosa (5º); Praga, Confusão (7º); Névoa Mortal, Contágio (9º).'],
      [2, 'Halo of Spores', 'Halo de Esporos', 'When a creature you can see moves into or starts its turn within 10 feet of you, use your reaction to force a Constitution save or deal 1d4 necrotic damage (1d6 at 6th, 1d8 at 10th, 1d10 at 14th).', 'Quando uma criatura que você vê entra ou começa o turno a até 3 m de você, use a reação para obrigá-la a um teste de Constituição ou causar 1d4 de dano necrótico (1d6 no 6, 1d8 no 10, 1d10 no 14).'],
      [2, 'Symbiotic Entity', 'Entidade Simbiótica', 'As an action, spend a Wild Shape use to gain 4 temporary hit points per druid level for 10 minutes. While they last, Halo of Spores damage doubles and your melee weapon hits deal an extra 1d6 necrotic.', 'Com uma ação, gaste um uso de Forma Selvagem para ganhar 4 PV temporários por nível de druida por 10 minutos. Enquanto durarem, o dano do Halo de Esporos dobra e seus acertos corpo a corpo causam 1d6 de dano necrótico extra.'],
      [6, 'Fungal Infestation', 'Infestação Fúngica', 'When a Small or Medium beast or humanoid dies within 10 feet, use your reaction to animate it as a zombie with 1 hit point for 1 hour. Uses equal to your Wisdom modifier per long rest.', 'Quando uma fera ou humanoide Pequeno ou Médio morre a até 3 m, use a reação para animá-lo como zumbi com 1 PV por 1 hora. Usos iguais ao modificador de Sabedoria por descanso longo.'],
      [10, 'Spreading Spores', 'Esporos Disseminados', 'While Symbiotic Entity is active, as a bonus action you can place your Halo of Spores as a 10-foot cube within 30 feet that damages creatures entering or starting their turn there.', 'Com a Entidade Simbiótica ativa, com uma ação bônus você pode lançar o Halo de Esporos como um cubo de 3 m a até 9 m, que fere quem entrar ou começar o turno ali.'],
      [14, 'Fungal Body', 'Corpo Fúngico', 'You can’t be blinded, deafened, frightened or poisoned, and critical hits against you count as normal hits unless you are incapacitated.', 'Você não pode ficar cego, surdo, amedrontado nem envenenado, e acertos críticos contra você contam como normais a menos que esteja incapacitado.'],
    ],
  },
  {
    cls: 'druid',
    name: 'Circle of Stars',
    pt: 'Círculo das Estrelas',
    desc: 'Druids who draw power from starlight and the constellations.',
    ptDesc: 'Druidas que tiram poder da luz das estrelas e das constelações.',
    features: [
      [2, 'Star Map', 'Mapa Estelar', 'You have a star map as a spellcasting focus, know Guidance, always have Guiding Bolt prepared, and can cast it without a slot a number of times equal to your proficiency bonus per long rest.', 'Você tem um mapa estelar como foco de conjuração, conhece Orientação, sempre tem Raio Guiador preparado e pode conjurá-lo sem espaço um número de vezes igual à proficiência por descanso longo.'],
      [2, 'Starry Form', 'Forma Estrelada', 'As a bonus action, spend a Wild Shape use to become luminous for 10 minutes as a constellation. Archer: bonus-action ranged spell attack for 1d8 + Wisdom radiant. Chalice: when you heal with a spell, you or another creature within 30 feet regains 1d8 + Wisdom. Dragon: treat d20 rolls of 9 or lower as 10 on Intelligence/Wisdom checks and concentration saves.', 'Com uma ação bônus, gaste um uso de Forma Selvagem para ficar luminoso por 10 minutos como uma constelação. Arqueiro: ataque mágico à distância com ação bônus, 1d8 + Sabedoria de dano radiante. Cálice: ao curar com magia, você ou outra criatura a até 9 m recupera 1d8 + Sabedoria. Dragão: trate 9 ou menos no d20 como 10 em testes de Inteligência/Sabedoria e de concentração.'],
      [6, 'Cosmic Omen', 'Presságio Cósmico', 'After a long rest, roll a die: even (Weal) or odd (Woe). As a reaction, add (Weal) or subtract (Woe) 1d6 from a roll of a creature within 30 feet. Uses equal to your proficiency bonus per long rest.', 'Depois de um descanso longo, role um dado: par (Bonança) ou ímpar (Infortúnio). Com a reação, some (Bonança) ou subtraia (Infortúnio) 1d6 da jogada de uma criatura a até 9 m. Usos iguais à proficiência por descanso longo.'],
      [10, 'Twinkling Constellations', 'Constelações Cintilantes', 'Starry Form dice become 2d8, the Dragon grants a 20-foot flying speed, and you can change constellation at the start of each turn.', 'Os dados da Forma Estrelada viram 2d8, o Dragão dá voo de 6 m, e você pode trocar de constelação no início de cada turno.'],
      [14, 'Full of Stars', 'Repleto de Estrelas', 'While in Starry Form, you have resistance to bludgeoning, piercing and slashing damage.', 'Na Forma Estrelada, você tem resistência a dano de concussão, perfuração e corte.'],
    ],
  },
  {
    cls: 'druid',
    name: 'Circle of Wildfire',
    pt: 'Círculo do Fogo Selvagem',
    desc: 'Druids who understand that destruction by fire makes way for new growth.',
    ptDesc: 'Druidas que entendem que a destruição pelo fogo abre espaço para o novo.',
    features: [
      [[2, 3, 5, 7, 9], 'Circle Spells', 'Magias do Círculo', 'Always prepared: Burning Hands, Cure Wounds (2nd); Flaming Sphere, Scorching Ray (3rd); Plant Growth, Revivify (5th); Aura of Life, Fire Shield (7th); Flame Strike, Mass Cure Wounds (9th).', 'Sempre preparadas: Mãos Flamejantes, Curar Ferimentos (2º); Esfera Flamejante, Raio Ardente (3º); Crescimento de Plantas, Revivificar (5º); Aura de Vida, Escudo de Fogo (7º); Coluna de Chamas, Curar Ferimentos em Massa (9º).'],
      [2, 'Summon Wildfire Spirit', 'Invocar Espírito do Fogo Selvagem', 'As an action, spend a Wild Shape use to summon a wildfire spirit within 30 feet for 1 hour; creatures within 10 feet of it make a Dexterity save or take 2d6 fire damage. It acts on your turn, can attack with flame and teleport itself and allies.', 'Com uma ação, gaste um uso de Forma Selvagem para invocar um espírito do fogo selvagem a até 9 m por 1 hora; criaturas a até 3 m dele fazem um teste de Destreza ou sofrem 2d6 de dano de fogo. Ele age no seu turno, ataca com chamas e teletransporta a si e aos aliados.'],
      [6, 'Enhanced Bond', 'Elo Fortalecido', 'While your spirit is summoned, your spells that heal or deal fire damage add 1d8 to one roll, and you can cast spells with a range other than self as if from the spirit.', 'Com o espírito invocado, suas magias que curam ou causam dano de fogo somam 1d8 a uma jogada, e você pode conjurar magias de alcance que não seja pessoal como se estivesse no lugar do espírito.'],
      [10, 'Cauterizing Flames', 'Chamas Cauterizantes', 'When a Small or larger creature dies within 30 feet of you or your spirit, a spectral flame appears; when a creature enters it, you can use your reaction to heal or damage it for 2d10 + Wisdom. Uses equal to your proficiency bonus per long rest.', 'Quando uma criatura Pequena ou maior morre a até 9 m de você ou do espírito, surge uma chama espectral; quando uma criatura entra nela, você pode usar a reação para curá-la ou feri-la em 2d10 + Sabedoria. Usos iguais à proficiência por descanso longo.'],
      [14, 'Blazing Revival', 'Renascer em Chamas', 'If your spirit is within 120 feet when you drop to 0 hit points, you can drop it to 0 to regain half your hit points and stand up. Once per long rest.', 'Se o espírito estiver a até 36 m quando você cair a 0 PV, você pode zerar os PV dele para recuperar metade dos seus e se levantar. Uma vez por descanso longo.'],
    ],
  },
  // Guerreiro
  {
    cls: 'fighter',
    name: 'Psi Warrior',
    pt: 'Guerreiro Psíquico',
    desc: 'Fighters who augment their strikes and defenses with psionic power.',
    ptDesc: 'Guerreiros que reforçam golpes e defesas com poder psiônico.',
    features: [
      [3, 'Psionic Power', 'Poder Psiônico', 'You have Psionic Energy dice (d6, rising to d12) equal to twice your proficiency bonus. Protective Field: reaction to reduce damage to a nearby creature by a die + Intelligence. Psionic Strike: once per turn, add a die + Intelligence of force damage. Telekinetic Movement: move an object or willing creature up to 30 feet.', 'Você tem dados de Energia Psiônica (d6, chegando a d12) iguais ao dobro da proficiência. Campo Protetor: reação para reduzir o dano de uma criatura próxima em um dado + Inteligência. Golpe Psiônico: uma vez por turno, some um dado + Inteligência de dano de energia. Movimento Telecinético: mova um objeto ou criatura voluntária até 9 m.'],
      [7, 'Telekinetic Adept', 'Adepto Telecinético', 'Psi-Powered Leap: as a bonus action, gain a flying speed of twice your walking speed this turn. Telekinetic Thrust: after a Psionic Strike, the target makes a Strength save or is knocked prone or pushed 10 feet.', 'Salto Psíquico: com uma ação bônus, ganhe voo igual ao dobro do deslocamento neste turno. Impulso Telecinético: depois de um Golpe Psiônico, o alvo faz um teste de Força ou cai ou é empurrado 3 m.'],
      [10, 'Guarded Mind', 'Mente Protegida', 'You have resistance to psychic damage, and can spend a Psionic Energy die to end charmed or frightened effects on yourself.', 'Você tem resistência a dano psíquico e pode gastar um dado de Energia Psiônica para encerrar efeitos de enfeitiçado ou amedrontado em si.'],
      [15, 'Bulwark of Force', 'Baluarte de Energia', 'As a bonus action, give half cover to up to as many creatures as your Intelligence modifier within 30 feet for 1 minute. Once per long rest, or by spending a Psionic Energy die.', 'Com uma ação bônus, dê meia cobertura a até um número de criaturas igual ao modificador de Inteligência a até 9 m por 1 minuto. Uma vez por descanso longo, ou gastando um dado de Energia Psiônica.'],
      [18, 'Telekinetic Master', 'Mestre Telecinético', 'You can cast Telekinesis using Intelligence without components, and while concentrating on it you can make one weapon attack as a bonus action. Once per long rest, or by spending a Psionic Energy die.', 'Você pode conjurar Telecinésia usando Inteligência, sem componentes, e enquanto se concentra nela pode fazer um ataque com arma com ação bônus. Uma vez por descanso longo, ou gastando um dado de Energia Psiônica.'],
    ],
  },
  {
    cls: 'fighter',
    name: 'Rune Knight',
    pt: 'Cavaleiro Rúnico',
    desc: 'Fighters who empower their gear with the runes of giants.',
    ptDesc: 'Guerreiros que fortalecem o equipamento com as runas dos gigantes.',
    features: [
      [3, 'Bonus Proficiencies', 'Proficiências Adicionais', 'You gain proficiency with smith’s tools and learn Giant.', 'Você ganha proficiência com ferramentas de ferreiro e aprende gigante.'],
      [[3, 7, 10, 15], 'Rune Carver', 'Entalhador de Runas', 'You learn two runes (more at 7th, 10th and 15th: Cloud, Fire, Frost, Stone, Hill, Storm) and inscribe them on your gear. Each gives a passive benefit and an activated effect usable once per short or long rest; the save DC is 8 + proficiency + Constitution.', 'Você aprende duas runas (mais nos níveis 7, 10 e 15: Nuvem, Fogo, Gelo, Pedra, Colina, Tempestade) e as grava no equipamento. Cada uma dá um benefício passivo e um efeito ativado uma vez por descanso curto ou longo; CD = 8 + proficiência + Constituição.'],
      [3, 'Giant’s Might', 'Poder do Gigante', 'As a bonus action, for 1 minute: become Large if there is room, gain advantage on Strength checks and saves, and deal an extra 1d6 damage once per turn with weapons (1d8 at 10th, 1d10 at 18th). Uses equal to your proficiency bonus per long rest.', 'Com uma ação bônus, por 1 minuto: fique Grande se houver espaço, ganhe vantagem em testes de Força e cause 1d6 de dano extra uma vez por turno com armas (1d8 no 10, 1d10 no 18). Usos iguais à proficiência por descanso longo.'],
      [7, 'Runic Shield', 'Escudo Rúnico', 'When a creature within 60 feet is hit, you can use your reaction to force the attacker to reroll. Uses equal to your proficiency bonus per long rest.', 'Quando uma criatura a até 18 m é atingida, você pode usar a reação para obrigar o atacante a rolar de novo. Usos iguais à proficiência por descanso longo.'],
      [10, 'Great Stature', 'Grande Estatura', 'You grow 3d4 inches, and the extra damage of Giant’s Might becomes 1d8.', 'Você cresce 3d4 polegadas, e o dano extra do Poder do Gigante vira 1d8.'],
      [15, 'Master of Runes', 'Mestre das Runas', 'You can use each rune’s activated effect twice per short or long rest.', 'Você pode usar o efeito ativado de cada runa duas vezes por descanso curto ou longo.'],
      [18, 'Runic Juggernaut', 'Colosso Rúnico', 'Giant’s Might extra damage becomes 1d10, you can become Huge, and your reach increases by 5 feet while enlarged.', 'O dano extra do Poder do Gigante vira 1d10, você pode ficar Enorme e seu alcance aumenta em 1,5 m enquanto estiver aumentado.'],
    ],
  },
  // Monge
  {
    cls: 'monk',
    name: 'Way of the Astral Self',
    pt: 'Caminho do Eu Astral',
    desc: 'Monks who manifest their astral self as spectral arms and armor.',
    ptDesc: 'Monges que manifestam o eu astral como braços e armadura espectrais.',
    features: [
      [3, 'Arms of the Astral Self', 'Braços do Eu Astral', 'As a bonus action, spend 1 ki to summon astral arms for 10 minutes: creatures within 10 feet make a Dexterity save or take two Martial Arts dice of force damage. While active, use Wisdom for Strength checks and saves, and attack with the arms (reach +5 feet) using Wisdom, dealing force damage.', 'Com uma ação bônus, gaste 1 ki para invocar braços astrais por 10 minutos: criaturas a até 3 m fazem um teste de Destreza ou sofrem dois dados de Artes Marciais de dano de energia. Enquanto ativos, use Sabedoria em testes de Força e ataque com os braços (alcance +1,5 m) usando Sabedoria, causando dano de energia.'],
      [6, 'Visage of the Astral Self', 'Semblante do Eu Astral', 'As a bonus action (1 ki), summon an astral visage for 10 minutes: darkvision 120 feet through magical darkness, advantage on Insight and Intimidation, and you can project your voice or speak only to one creature.', 'Com uma ação bônus (1 ki), invoque um semblante astral por 10 minutos: visão no escuro de 36 m que atravessa escuridão mágica, vantagem em Intuição e Intimidação, e você pode projetar a voz ou falar só com uma criatura.'],
      [11, 'Body of the Astral Self', 'Corpo do Eu Astral', 'With arms and visage active, you can use your reaction to reduce acid, cold, fire, force, lightning or thunder damage by 1d10 + Wisdom, and once per turn your arm attacks deal an extra Martial Arts die.', 'Com braços e semblante ativos, você pode usar a reação para reduzir dano ácido, de frio, fogo, energia, elétrico ou trovejante em 1d10 + Sabedoria, e uma vez por turno os ataques com os braços causam um dado de Artes Marciais extra.'],
      [17, 'Awakened Astral Self', 'Eu Astral Desperto', 'As a bonus action (5 ki), summon arms, visage and armor for 10 minutes: +2 AC, and you can make three attacks with the arms when you take the Attack action.', 'Com uma ação bônus (5 ki), invoque braços, semblante e armadura por 10 minutos: +2 na CA e três ataques com os braços ao usar a ação Atacar.'],
    ],
  },
  {
    cls: 'monk',
    name: 'Way of Mercy',
    pt: 'Caminho da Misericórdia',
    desc: 'Masked monks who heal the suffering and bring a swift end to the incurable.',
    ptDesc: 'Monges mascarados que curam os que sofrem e dão fim rápido aos incuráveis.',
    features: [
      [3, 'Implements of Mercy', 'Instrumentos da Misericórdia', 'You gain proficiency in Insight and Medicine and with the herbalism kit, and you wear a special mask.', 'Você ganha proficiência em Intuição, Medicina e kit de herbalismo, e usa uma máscara especial.'],
      [3, 'Hand of Healing', 'Mão da Cura', 'As an action, spend 1 ki to touch a creature and restore a Martial Arts die + Wisdom hit points. With Flurry of Blows, you can replace one strike with this without spending ki.', 'Com uma ação, gaste 1 ki para tocar uma criatura e restaurar um dado de Artes Marciais + Sabedoria em PV. Na Rajada de Golpes, pode trocar um golpe por isso sem gastar ki.'],
      [3, 'Hand of Harm', 'Mão do Dano', 'Once per turn, when you hit with an unarmed strike, spend 1 ki to deal an extra Martial Arts die + Wisdom necrotic damage.', 'Uma vez por turno, ao acertar um ataque desarmado, gaste 1 ki para causar um dado de Artes Marciais + Sabedoria de dano necrótico extra.'],
      [6, 'Physician’s Touch', 'Toque do Médico', 'Hand of Healing also ends a disease or one of: blinded, deafened, paralyzed, poisoned or stunned. Hand of Harm can poison the target until the end of your next turn.', 'A Mão da Cura também encerra uma doença ou uma condição: cego, surdo, paralisado, envenenado ou atordoado. A Mão do Dano pode envenenar o alvo até o fim do seu próximo turno.'],
      [11, 'Flurry of Healing and Harm', 'Rajada de Cura e Dano', 'With Flurry of Blows, you can replace each strike with Hand of Healing without ki, and once per turn apply Hand of Harm without ki.', 'Na Rajada de Golpes, você pode trocar cada golpe pela Mão da Cura sem ki e, uma vez por turno, aplicar a Mão do Dano sem ki.'],
      [17, 'Hand of Ultimate Mercy', 'Mão da Misericórdia Suprema', 'As an action, spend 5 ki to touch a creature that died within 24 hours: it returns to life with 4d10 + Wisdom hit points, free of most conditions. Once per long rest.', 'Com uma ação, gaste 5 ki para tocar uma criatura que morreu há até 24 horas: ela volta à vida com 4d10 + Sabedoria PV, livre da maioria das condições. Uma vez por descanso longo.'],
    ],
  },
  // Paladino
  {
    cls: 'paladin',
    name: 'Oath of Glory',
    pt: 'Juramento da Glória',
    desc: 'Paladins who believe they are destined for heroic deeds and push their allies to greatness.',
    ptDesc: 'Paladinos que acreditam estar destinados a feitos heroicos e impulsionam os aliados à grandeza.',
    features: [
      [[3, 5, 9, 13, 17], 'Oath Spells', 'Magias de Juramento', 'Always prepared: Guiding Bolt, Heroism (3rd); Enhance Ability, Magic Weapon (5th); Haste, Protection from Energy (9th); Compulsion, Freedom of Movement (13th); Commune, Flame Strike (17th).', 'Sempre preparadas: Raio Guiador, Heroísmo (3º); Aprimorar Atributo, Arma Mágica (5º); Velocidade, Proteção contra Energia (9º); Compulsão, Liberdade de Movimento (13º); Comunhão, Coluna de Chamas (17º).'],
      [3, 'Channel Divinity', 'Canalizar Divindade', 'Peerless Athlete: as a bonus action, for 10 minutes gain advantage on Athletics and Acrobatics and carry and jump farther. Inspiring Smite: after a Divine Smite, distribute 2d8 + paladin level temporary hit points among creatures within 30 feet.', 'Atleta Inigualável: com uma ação bônus, por 10 minutos ganhe vantagem em Atletismo e Acrobacia e carregue e salte mais. Destruição Inspiradora: depois de uma Destruição Divina, distribua 2d8 + nível de paladino em PV temporários entre criaturas a até 9 m.'],
      [7, 'Aura of Alacrity', 'Aura de Agilidade', 'Your walking speed increases by 10 feet, and allies who start their turn within 5 feet of you (10 feet at 18th level) gain +10 feet of speed that turn.', 'Seu deslocamento aumenta em 3 m, e aliados que começam o turno a 1,5 m de você (3 m no nível 18) ganham +3 m de deslocamento nesse turno.'],
      [15, 'Glorious Defense', 'Defesa Gloriosa', 'When you or a creature within 10 feet is hit, use your reaction to add your Charisma modifier to its AC; if the attack misses, you can attack the attacker. Uses equal to your Charisma modifier per long rest.', 'Quando você ou uma criatura a até 3 m é atingida, use a reação para somar o modificador de Carisma à CA; se o ataque errar, você pode atacar o atacante. Usos iguais ao modificador de Carisma por descanso longo.'],
      [20, 'Living Legend', 'Lenda Viva', 'As a bonus action, for 1 minute: advantage on Charisma checks, turn a missed weapon attack into a hit once per turn, and reroll failed saves as a reaction. Once per long rest, or by spending a 5th-level slot.', 'Com uma ação bônus, por 1 minuto: vantagem em testes de Carisma, transforma um ataque com arma errado em acerto uma vez por turno e rola de novo testes de resistência falhos com a reação. Uma vez por descanso longo, ou gastando um espaço de 5º círculo.'],
    ],
  },
  {
    cls: 'paladin',
    name: 'Oath of the Watchers',
    pt: 'Juramento dos Vigilantes',
    desc: 'Paladins who guard the mortal world against extraplanar threats.',
    ptDesc: 'Paladinos que protegem o mundo mortal de ameaças de outros planos.',
    features: [
      [[3, 5, 9, 13, 17], 'Oath Spells', 'Magias de Juramento', 'Always prepared: Alarm, Detect Magic (3rd); Moonbeam, See Invisibility (5th); Counterspell, Nondetection (9th); Aura of Purity, Banishment (13th); Hold Monster, Scrying (17th).', 'Sempre preparadas: Alarme, Detectar Magia (3º); Raio Lunar, Ver o Invisível (5º); Contramágica, Indetectável (9º); Aura de Pureza, Banimento (13º); Imobilizar Monstro, Vidência (17º).'],
      [3, 'Channel Divinity', 'Canalizar Divindade', 'Watcher’s Will: as an action, you and up to as many creatures as your Charisma modifier within 30 feet gain advantage on Intelligence, Wisdom and Charisma saves for 1 minute. Abjure the Extraplanar: as an action, aberrations, celestials, elementals, fey and fiends within 30 feet make a Wisdom save or are turned for 1 minute.', 'Vontade do Vigilante: com uma ação, você e até um número de criaturas igual ao modificador de Carisma a até 9 m ganham vantagem em testes de Inteligência, Sabedoria e Carisma por 1 minuto. Repelir o Extraplanar: com uma ação, aberrações, celestiais, elementais, fadas e corruptores a até 9 m fazem um teste de Sabedoria ou são expulsos por 1 minuto.'],
      [[7, 18], 'Aura of the Sentinel', 'Aura da Sentinela', 'You and creatures of your choice within 10 feet (30 feet at 18th level) add your proficiency bonus to initiative.', 'Você e criaturas à sua escolha a até 3 m (9 m no nível 18) somam a proficiência à iniciativa.'],
      [15, 'Vigilant Rebuke', 'Repreensão Vigilante', 'When you or a creature within 30 feet succeeds on an Intelligence, Wisdom or Charisma save, use your reaction to deal 2d8 + Charisma force damage to the creature that forced it.', 'Quando você ou uma criatura a até 9 m passa num teste de Inteligência, Sabedoria ou Carisma, use a reação para causar 2d8 + Carisma de dano de energia em quem forçou o teste.'],
      [20, 'Mortal Bulwark', 'Baluarte Mortal', 'As a bonus action, for 1 minute: truesight 120 feet, advantage on attacks against extraplanar creatures, and a hit can banish such a creature on a failed Charisma save. Once per long rest, or by spending a 5th-level slot.', 'Com uma ação bônus, por 1 minuto: visão verdadeira de 36 m, vantagem em ataques contra criaturas extraplanares, e um acerto pode bani-las se falharem num teste de Carisma. Uma vez por descanso longo, ou gastando um espaço de 5º círculo.'],
    ],
  },
  // Patrulheiro
  {
    cls: 'ranger',
    name: 'Fey Wanderer',
    pt: 'Andarilho Feérico',
    desc: 'Rangers touched by the Feywild who blend charm with martial skill.',
    ptDesc: 'Patrulheiros tocados pela Agrestia das Fadas que unem charme e perícia marcial.',
    features: [
      [[3, 5, 9, 13, 17], 'Fey Wanderer Magic', 'Magia do Andarilho Feérico', 'You learn extra spells: Charm Person (3rd), Misty Step (5th), Dispel Magic (9th), Dimension Door (13th), Mislead (17th).', 'Você aprende magias extras: Enfeitiçar Pessoa (3º), Passo Nebuloso (5º), Dissipar Magia (9º), Porta Dimensional (13º), Enganar (17º).'],
      [3, 'Dreadful Strikes', 'Golpes Terríveis', 'Once per turn per creature, your weapon hits deal an extra 1d4 psychic damage (1d6 at 11th level).', 'Uma vez por turno contra cada criatura, seus acertos com arma causam 1d4 de dano psíquico extra (1d6 no nível 11).'],
      [3, 'Otherworldly Glamour', 'Glamour de Outro Mundo', 'Add your Wisdom modifier to Charisma checks, and gain proficiency in Deception, Performance or Persuasion.', 'Some o modificador de Sabedoria aos testes de Carisma e ganhe proficiência em Enganação, Atuação ou Persuasão.'],
      [7, 'Beguiling Twist', 'Reviravolta Sedutora', 'You have advantage on saves against being charmed or frightened. When a creature within 120 feet succeeds on such a save, use your reaction to force another creature within 120 feet to make a Wisdom save or be charmed or frightened by you for 1 minute.', 'Você tem vantagem em testes contra ficar enfeitiçado ou amedrontado. Quando uma criatura a até 36 m passa num teste assim, use a reação para obrigar outra criatura a até 36 m a um teste de Sabedoria ou ficar enfeitiçada ou amedrontada por você por 1 minuto.'],
      [11, 'Fey Reinforcements', 'Reforços Feéricos', 'You know Summon Fey and can cast it once per long rest without a slot or material component; you can also cast it without concentration, lasting 1 minute.', 'Você conhece Invocar Fada e pode conjurá-la uma vez por descanso longo sem espaço nem componente material; também pode conjurá-la sem concentração, durando 1 minuto.'],
      [15, 'Misty Wanderer', 'Andarilho Nebuloso', 'You can cast Misty Step without a slot a number of times equal to your Wisdom modifier per long rest, bringing a willing creature within 5 feet along.', 'Você pode conjurar Passo Nebuloso sem espaço um número de vezes igual ao modificador de Sabedoria por descanso longo, levando junto uma criatura voluntária a 1,5 m.'],
    ],
  },
  {
    cls: 'ranger',
    name: 'Swarmkeeper',
    pt: 'Guardião do Enxame',
    desc: 'Rangers bonded to a swarm of nature spirits.',
    ptDesc: 'Patrulheiros ligados a um enxame de espíritos da natureza.',
    features: [
      [[3, 5, 9, 13, 17], 'Swarmkeeper Magic', 'Magia do Guardião do Enxame', 'You learn Mage Hand and extra spells: Faerie Fire (3rd), Web (5th), Gaseous Form (9th), Arcane Eye (13th), Insect Plague (17th).', 'Você aprende Mão Mágica e magias extras: Fogo das Fadas (3º), Teia (5º), Forma Gasosa (9º), Olho Arcano (13º), Praga de Insetos (17º).'],
      [3, 'Gathered Swarm', 'Enxame Reunido', 'Once per turn after you hit, your swarm can: deal an extra 1d6 piercing damage, push the target 15 feet (Strength save), or move you 5 feet without provoking.', 'Uma vez por turno, depois de acertar, seu enxame pode: causar 1d6 de dano perfurante extra, empurrar o alvo 4,5 m (teste de Força) ou mover você 1,5 m sem provocar.'],
      [7, 'Writhing Tide', 'Maré Ondulante', 'As a bonus action, gain a 10-foot flying speed and hover for 1 minute. Uses equal to your proficiency bonus per long rest.', 'Com uma ação bônus, ganhe voo de 3 m e possa pairar por 1 minuto. Usos iguais à proficiência por descanso longo.'],
      [11, 'Mighty Swarm', 'Enxame Poderoso', 'Gathered Swarm damage becomes 1d8, the push also knocks prone, and moving you also grants half cover.', 'O dano do Enxame Reunido vira 1d8, o empurrão também derruba e o movimento também dá meia cobertura.'],
      [15, 'Swarming Dispersal', 'Dispersão do Enxame', 'When you take damage, use your reaction to gain resistance to it and teleport up to 30 feet. Uses equal to your proficiency bonus per long rest.', 'Ao sofrer dano, use a reação para ter resistência a ele e se teletransportar até 9 m. Usos iguais à proficiência por descanso longo.'],
    ],
  },
  // Ladino
  {
    cls: 'rogue',
    name: 'Phantom',
    pt: 'Fantasma',
    desc: 'Rogues who walk alongside death, drawing power from lingering souls.',
    ptDesc: 'Ladinos que caminham ao lado da morte e tiram poder das almas que ficam.',
    features: [
      [3, 'Whispers of the Dead', 'Sussurros dos Mortos', 'After a rest, gain proficiency in one skill or tool of your choice until your next rest.', 'Depois de um descanso, ganhe proficiência numa perícia ou ferramenta à sua escolha até o próximo descanso.'],
      [3, 'Wails from the Grave', 'Lamentos da Sepultura', 'After dealing Sneak Attack, deal half your Sneak Attack dice as necrotic damage to a second creature within 30 feet of the first. Uses equal to your proficiency bonus per long rest.', 'Depois de causar Ataque Furtivo, cause metade dos dados do Ataque Furtivo como dano necrótico a uma segunda criatura a até 9 m da primeira. Usos iguais à proficiência por descanso longo.'],
      [9, 'Tokens of the Departed', 'Lembranças dos Falecidos', 'When a creature dies within 30 feet, use your reaction to create a soul trinket (max = proficiency bonus). While holding one you have advantage on death and Constitution saves; you can destroy one to use Wails from the Grave without expending a use, or to ask the spirit a question.', 'Quando uma criatura morre a até 9 m, use a reação para criar uma bugiganga de alma (máximo = proficiência). Com uma, você tem vantagem em testes contra a morte e de Constituição; pode destruí-la para usar Lamentos da Sepultura sem gastar uso, ou para fazer uma pergunta ao espírito.'],
      [13, 'Ghost Walk', 'Caminhar Fantasma', 'As a bonus action, become spectral for 10 minutes: 10-foot flying speed, hover, attacks against you have disadvantage, and you can pass through objects. Once per long rest, or by destroying a soul trinket.', 'Com uma ação bônus, fique espectral por 10 minutos: voo de 3 m, pairar, ataques contra você têm desvantagem e você atravessa objetos. Uma vez por descanso longo, ou destruindo uma bugiganga de alma.'],
      [17, 'Death’s Friend', 'Amigo da Morte', 'Wails from the Grave also deals necrotic damage to the first target, and you always get a soul trinket after a long rest if you have none.', 'Lamentos da Sepultura também causa dano necrótico ao primeiro alvo, e você sempre ganha uma bugiganga de alma ao fim de um descanso longo se não tiver nenhuma.'],
    ],
  },
  {
    cls: 'rogue',
    name: 'Soulknife',
    pt: 'Lâmina da Alma',
    desc: 'Rogues who strike with blades of psychic energy.',
    ptDesc: 'Ladinos que atacam com lâminas de energia psíquica.',
    features: [
      [3, 'Psionic Power', 'Poder Psiônico', 'You have Psionic Energy dice (d6, rising to d12) equal to twice your proficiency bonus. Psi-Bolstered Knack: when you fail a proficient check, add a die. Psychic Whispers: telepathy with up to proficiency-bonus creatures for hours equal to a die roll.', 'Você tem dados de Energia Psiônica (d6, chegando a d12) iguais ao dobro da proficiência. Talento Reforçado: ao falhar num teste com proficiência, some um dado. Sussurros Psíquicos: telepatia com até proficiência criaturas por horas iguais a um dado.'],
      [3, 'Psychic Blades', 'Lâminas Psíquicas', 'When you take the Attack action, you can manifest a psychic blade (1d6 psychic, finesse, thrown 60 feet) and then make a bonus-action attack with a second blade (1d4).', 'Ao usar a ação Atacar, você pode manifestar uma lâmina psíquica (1d6 psíquico, acuidade, arremesso 18 m) e depois fazer um ataque com ação bônus com uma segunda lâmina (1d4).'],
      [9, 'Soul Blades', 'Lâminas da Alma', 'Homing Strikes: when you miss with a psychic blade, add a Psionic Energy die to the roll (spent only if it then hits). Psychic Teleportation: as a bonus action, spend a die and teleport up to 10 × the roll in feet.', 'Golpes Teleguiados: ao errar com uma lâmina psíquica, some um dado de Energia Psiônica (gasto só se acertar). Teletransporte Psíquico: com uma ação bônus, gaste um dado e se teletransporte até 10 × o resultado em pés (3 m por ponto).'],
      [13, 'Psychic Veil', 'Véu Psíquico', 'As an action, become invisible for 1 hour (ends if you deal damage or force a save). Once per long rest, or by spending a Psionic Energy die.', 'Com uma ação, fique invisível por 1 hora (acaba se causar dano ou forçar um teste). Uma vez por descanso longo, ou gastando um dado de Energia Psiônica.'],
      [17, 'Rend Mind', 'Rasgar a Mente', 'When you deal Sneak Attack with a psychic blade, the target makes a Wisdom save or is stunned for 1 minute. Once per long rest, or by spending three Psionic Energy dice.', 'Ao causar Ataque Furtivo com uma lâmina psíquica, o alvo faz um teste de Sabedoria ou fica atordoado por 1 minuto. Uma vez por descanso longo, ou gastando três dados de Energia Psiônica.'],
    ],
  },
  // Feiticeiro
  {
    cls: 'sorcerer',
    name: 'Aberrant Mind',
    pt: 'Mente Aberrante',
    desc: 'Sorcerers whose power comes from an alien influence from the Far Realm.',
    ptDesc: 'Feiticeiros cujo poder vem de uma influência alienígena do Reino Distante.',
    features: [
      [[1, 3, 5, 7, 9], 'Psionic Spells', 'Magias Psiônicas', 'You learn extra spells that can be swapped for divination or enchantment spells: Arms of Hadar, Dissonant Whispers, Mind Sliver (1st); Calm Emotions, Detect Thoughts (3rd); Hunger of Hadar, Sending (5th); Evard’s Black Tentacles, Summon Aberration (7th); Rary’s Telepathic Bond, Telekinesis (9th).', 'Você aprende magias extras, trocáveis por adivinhação ou encantamento: Braços de Hadar, Sussurros Dissonantes, Lasca Mental (1º); Acalmar Emoções, Detectar Pensamentos (3º); Fome de Hadar, Mensagem (5º); Tentáculos Negros de Evard, Invocar Aberração (7º); Elo Telepático de Rary, Telecinésia (9º).'],
      [1, 'Telepathic Speech', 'Fala Telepática', 'As a bonus action, link telepathically with a creature within 30 feet for minutes equal to your sorcerer level, if you share a language.', 'Com uma ação bônus, crie um elo telepático com uma criatura a até 9 m por minutos iguais ao seu nível de feiticeiro, se tiverem um idioma em comum.'],
      [6, 'Psionic Sorcery', 'Feitiçaria Psiônica', 'You can cast Psionic Spells by spending sorcery points equal to the spell level, without verbal, somatic or non-consumed material components.', 'Você pode conjurar Magias Psiônicas gastando pontos de feitiçaria iguais ao círculo, sem componentes verbais, somáticos ou materiais não consumidos.'],
      [6, 'Psychic Defenses', 'Defesas Psíquicas', 'You have resistance to psychic damage and advantage on saves against being charmed or frightened.', 'Você tem resistência a dano psíquico e vantagem em testes contra ficar enfeitiçado ou amedrontado.'],
      [14, 'Revelation in Flesh', 'Revelação na Carne', 'As a bonus action, spend sorcery points to transform for 10 minutes, choosing per point: see invisible within 60 feet, fly, swim and breathe underwater, or squeeze through 1-inch spaces.', 'Com uma ação bônus, gaste pontos de feitiçaria para se transformar por 10 minutos, escolhendo por ponto: ver o invisível a até 18 m, voar, nadar e respirar na água, ou passar por frestas de 2,5 cm.'],
      [18, 'Warping Implosion', 'Implosão Distorcida', 'As an action, teleport up to 120 feet; creatures within 30 feet of where you left make a Strength save or take 3d10 force damage and are pulled toward that point. Once per long rest, or by spending 5 sorcery points.', 'Com uma ação, teletransporte-se até 36 m; criaturas a até 9 m do ponto de partida fazem um teste de Força ou sofrem 3d10 de dano de energia e são puxadas para ele. Uma vez por descanso longo, ou gastando 5 pontos de feitiçaria.'],
    ],
  },
  {
    cls: 'sorcerer',
    name: 'Clockwork Soul',
    pt: 'Alma Mecânica',
    desc: 'Sorcerers whose power comes from the cosmic order of Mechanus.',
    ptDesc: 'Feiticeiros cujo poder vem da ordem cósmica de Mechanus.',
    features: [
      [[1, 3, 5, 7, 9], 'Clockwork Magic', 'Magia Mecânica', 'You learn extra spells that can be swapped for abjuration or transmutation spells: Alarm, Protection from Evil and Good (1st); Aid, Lesser Restoration (3rd); Dispel Magic, Protection from Energy (5th); Freedom of Movement, Summon Construct (7th); Greater Restoration, Wall of Force (9th).', 'Você aprende magias extras, trocáveis por abjuração ou transmutação: Alarme, Proteção contra o Bem e o Mal (1º); Auxílio, Restauração Menor (3º); Dissipar Magia, Proteção contra Energia (5º); Liberdade de Movimento, Invocar Constructo (7º); Restauração Maior, Muralha de Energia (9º).'],
      [1, 'Restore Balance', 'Restaurar o Equilíbrio', 'When a creature within 60 feet is about to roll with advantage or disadvantage, use your reaction to cancel it. Uses equal to your proficiency bonus per long rest.', 'Quando uma criatura a até 18 m vai rolar com vantagem ou desvantagem, use a reação para anular isso. Usos iguais à proficiência por descanso longo.'],
      [6, 'Bastion of Law', 'Bastião da Lei', 'As an action, spend 1 to 5 sorcery points to give a creature within 30 feet that many d8s of ward; when it takes damage, it can spend dice to reduce the damage.', 'Com uma ação, gaste de 1 a 5 pontos de feitiçaria para dar a uma criatura a até 9 m essa quantidade de d8 de proteção; ao sofrer dano, ela gasta dados para reduzi-lo.'],
      [14, 'Trance of Order', 'Transe da Ordem', 'As a bonus action, for 1 minute attacks against you can’t have advantage, and you treat d20 rolls of 9 or lower as 10. Once per long rest, or by spending 5 sorcery points.', 'Com uma ação bônus, por 1 minuto ataques contra você não podem ter vantagem, e você trata 9 ou menos no d20 como 10. Uma vez por descanso longo, ou gastando 5 pontos de feitiçaria.'],
      [18, 'Clockwork Cavalcade', 'Cavalgada Mecânica', 'As an action, in a 30-foot cube: restore up to 100 hit points split as you choose, repair damaged objects, and end spells of 6th level or lower on creatures and objects of your choice. Once per long rest, or by spending 7 sorcery points.', 'Com uma ação, num cubo de 9 m: restaure até 100 PV divididos como quiser, conserte objetos danificados e encerre magias de 6º círculo ou menor em criaturas e objetos à sua escolha. Uma vez por descanso longo, ou gastando 7 pontos de feitiçaria.'],
    ],
  },
  // Bruxo
  {
    cls: 'warlock',
    name: 'The Fathomless',
    pt: 'O Insondável',
    desc: 'Warlocks bound to an entity of the ocean depths.',
    ptDesc: 'Bruxos ligados a uma entidade das profundezas do oceano.',
    features: [
      [[1, 3, 5, 7, 9], 'Expanded Spell List', 'Lista de Magias Expandida', 'Added to your warlock list: Create or Destroy Water, Thunderwave (1st); Gust of Wind, Silence (2nd); Lightning Bolt, Sleet Storm (3rd); Control Water, Summon Elemental (4th); Bigby’s Hand, Cone of Cold (5th).', 'Somadas à sua lista de bruxo: Criar ou Destruir Água, Onda Trovejante (1º); Lufada de Vento, Silêncio (2º); Relâmpago, Tempestade de Granizo (3º); Controlar Água, Invocar Elemental (4º); Mão de Bigby, Cone de Frio (5º).'],
      [1, 'Tentacle of the Deeps', 'Tentáculo das Profundezas', 'As a bonus action, summon a tentacle within 60 feet for 1 minute and make a melee spell attack: 1d8 cold damage (2d8 at 10th) and the target’s speed drops by 10 feet. You can attack with it again as a bonus action. Uses equal to your proficiency bonus per long rest.', 'Com uma ação bônus, invoque um tentáculo a até 18 m por 1 minuto e faça um ataque mágico corpo a corpo: 1d8 de dano de frio (2d8 no 10) e o deslocamento do alvo cai 3 m. Pode atacar de novo com ação bônus. Usos iguais à proficiência por descanso longo.'],
      [1, 'Gift of the Sea', 'Dádiva do Mar', 'You gain a swimming speed of 40 feet and can breathe underwater.', 'Você ganha deslocamento de natação de 12 m e respira debaixo d’água.'],
      [6, 'Oceanic Soul', 'Alma Oceânica', 'You have resistance to cold damage, and when fully submerged you can speak with any creature that is also submerged.', 'Você tem resistência a dano de frio e, submerso, pode falar com qualquer criatura também submersa.'],
      [6, 'Guardian Coil', 'Espiral Guardiã', 'When a creature within 10 feet of your tentacle takes damage, use your reaction to reduce it by 1d8 (2d8 at 10th level).', 'Quando uma criatura a até 3 m do seu tentáculo sofre dano, use a reação para reduzi-lo em 1d8 (2d8 no nível 10).'],
      [10, 'Grasping Tentacles', 'Tentáculos Agarradores', 'You learn Evard’s Black Tentacles and can cast it once per long rest without a slot; when you cast it, you gain temporary hit points equal to your warlock level and damage can’t break your concentration on it.', 'Você aprende Tentáculos Negros de Evard e pode conjurá-la uma vez por descanso longo sem espaço; ao conjurá-la, ganha PV temporários iguais ao nível de bruxo e dano não quebra sua concentração nela.'],
      [14, 'Fathomless Plunge', 'Mergulho Insondável', 'As an action, teleport yourself and up to five willing creatures within 30 feet up to 1 mile to a body of water you have seen. Once per short or long rest.', 'Com uma ação, teletransporte você e até cinco criaturas voluntárias a até 9 m por até 1,5 km para um corpo d’água que você já viu. Uma vez por descanso curto ou longo.'],
    ],
  },
  {
    cls: 'warlock',
    name: 'The Genie',
    pt: 'O Gênio',
    desc: 'Warlocks whose patron is a noble genie, granting a magic vessel.',
    ptDesc: 'Bruxos cujo patrono é um gênio nobre que concede um receptáculo mágico.',
    features: [
      [[1, 3, 5, 7, 9], 'Expanded Spell List', 'Lista de Magias Expandida', 'Added to your warlock list by genie kind (dao, djinni, efreeti or marid), plus Detect Evil and Good, Phantasmal Force, Create Food and Water, Phantasmal Killer, Creation and, as a 9th-level option for Mystic Arcanum, Wish.', 'Somadas à sua lista de bruxo conforme o tipo de gênio (dao, djinni, efreeti ou marid), mais Detectar o Bem e o Mal, Força Fantasmagórica, Criar Alimentos e Água, Assassino Fantasmagórico, Criação e, como opção de 9º círculo para a Arcana Mística, Desejo.'],
      [1, 'Genie’s Vessel', 'Receptáculo do Gênio', 'You receive a magic vessel (spellcasting focus). Bottled Respite: as an action, enter the vessel for hours equal to twice your proficiency bonus, once per long rest. Genie’s Wrath: once per turn on a hit, deal extra damage equal to your proficiency bonus (bludgeoning, thunder, fire or cold by genie kind).', 'Você recebe um receptáculo mágico (foco de conjuração). Refúgio Engarrafado: com uma ação, entre no receptáculo por horas iguais ao dobro da proficiência, uma vez por descanso longo. Ira do Gênio: uma vez por turno, ao acertar, cause dano extra igual à proficiência (concussão, trovejante, fogo ou frio conforme o gênio).'],
      [6, 'Elemental Gift', 'Dádiva Elemental', 'You gain resistance by genie kind, and as a bonus action you can gain a 30-foot flying speed for 10 minutes. Uses equal to your proficiency bonus per long rest.', 'Você ganha resistência conforme o gênio e, com uma ação bônus, pode ganhar voo de 9 m por 10 minutos. Usos iguais à proficiência por descanso longo.'],
      [10, 'Sanctuary Vessel', 'Receptáculo Santuário', 'When you enter your vessel, up to five willing creatures within 30 feet can come along, and anyone who stays 10 minutes gains the benefit of a short rest plus extra healing.', 'Ao entrar no receptáculo, até cinco criaturas voluntárias a até 9 m podem ir junto, e quem ficar 10 minutos ganha os efeitos de um descanso curto e cura extra.'],
      [14, 'Limited Wish', 'Desejo Limitado', 'As an action, ask your patron for the effect of any spell of 6th level or lower with a casting time of 1 action, without components. Once per 1d4 long rests.', 'Com uma ação, peça ao patrono o efeito de qualquer magia de 6º círculo ou menor com tempo de 1 ação, sem componentes. Uma vez a cada 1d4 descansos longos.'],
    ],
  },
  // Mago
  {
    cls: 'wizard',
    name: 'Bladesinging',
    pt: 'Cantor da Lâmina',
    desc: 'Wizards who blend swordplay, dance and magic.',
    ptDesc: 'Magos que unem esgrima, dança e magia.',
    features: [
      [2, 'Training in War and Song', 'Treino em Guerra e Canção', 'You gain proficiency with light armor, one one-handed melee weapon, and Performance.', 'Você ganha proficiência com armaduras leves, uma arma corpo a corpo de uma mão e Atuação.'],
      [2, 'Bladesong', 'Canção da Lâmina', 'As a bonus action, start a Bladesong for 1 minute (no medium/heavy armor or shield): add Intelligence to AC and concentration saves, +10 feet of walking speed, and advantage on Acrobatics. Uses equal to your proficiency bonus per long rest.', 'Com uma ação bônus, inicie a Canção da Lâmina por 1 minuto (sem armadura média/pesada nem escudo): some Inteligência à CA e aos testes de concentração, +3 m de deslocamento e vantagem em Acrobacia. Usos iguais à proficiência por descanso longo.'],
      [6, 'Extra Attack', 'Ataque Extra', 'You can attack twice when you take the Attack action, and replace one of the attacks with a cantrip.', 'Você pode atacar duas vezes ao usar a ação Atacar e trocar um dos ataques por um truque.'],
      [10, 'Song of Defense', 'Canção de Defesa', 'While your Bladesong is active, use your reaction and expend a spell slot to reduce damage by five times the slot level.', 'Com a Canção da Lâmina ativa, use a reação e gaste um espaço de magia para reduzir o dano em cinco vezes o círculo do espaço.'],
      [14, 'Song of Victory', 'Canção da Vitória', 'While your Bladesong is active, add your Intelligence modifier to melee weapon damage.', 'Com a Canção da Lâmina ativa, some o modificador de Inteligência ao dano corpo a corpo com armas.'],
    ],
  },
  {
    cls: 'wizard',
    name: 'Order of Scribes',
    pt: 'Ordem dos Escribas',
    desc: 'Wizards devoted to the written word, whose spellbook awakens.',
    ptDesc: 'Magos dedicados à palavra escrita, cujo grimório desperta.',
    features: [
      [2, 'Wizardly Quill', 'Pena Mágica', 'As a bonus action, create a magic quill that writes without ink; copying spells into your spellbook takes 2 minutes per spell level.', 'Com uma ação bônus, crie uma pena mágica que escreve sem tinta; copiar magias para o grimório leva 2 minutos por círculo.'],
      [2, 'Awakened Spellbook', 'Grimório Desperto', 'Your spellbook is your focus. When you cast a damaging spell, you can swap its damage type for that of another spell of the same level in your book. Once per long rest, cast a ritual at normal casting time.', 'Seu grimório é seu foco. Ao conjurar uma magia de dano, você pode trocar o tipo de dano pelo de outra magia do mesmo círculo no grimório. Uma vez por descanso longo, conjure um ritual no tempo normal.'],
      [6, 'Manifest Mind', 'Mente Manifesta', 'As a bonus action, manifest your spellbook’s mind within 60 feet: it sheds dim light, has darkvision 60 feet, and you can cast spells as if from its space. Spell casts from it equal your proficiency bonus per long rest.', 'Com uma ação bônus, manifeste a mente do grimório a até 18 m: ela emite penumbra, tem visão no escuro de 18 m e você pode conjurar magias como se estivesse no lugar dela. Conjurações por ela iguais à proficiência por descanso longo.'],
      [10, 'Master Scrivener', 'Escrivão Mestre', 'After a long rest, create a magic scroll of a 1st- or 2nd-level spell from your book, cast at one level higher.', 'Depois de um descanso longo, crie um pergaminho mágico de uma magia de 1º ou 2º círculo do grimório, conjurada um círculo acima.'],
      [14, 'One with the Word', 'Um com a Palavra', 'You have advantage on Arcana checks. When you take damage while your manifested mind is present, you can prevent it by dissolving spells in your book (3d6 levels of spells unusable until 1d6 long rests). Once per long rest.', 'Você tem vantagem em testes de Arcanismo. Ao sofrer dano com a mente manifesta presente, pode evitá-lo apagando magias do grimório (3d6 círculos de magias inutilizáveis por 1d6 descansos longos). Uma vez por descanso longo.'],
    ],
  },
];

export const tceSubclasses = specs.map((s) => subclass('tce', s));
