import { spell, type SpellSpec } from './helpers';

const B = 'bard', C = 'cleric', D = 'druid', P = 'paladin', R = 'ranger', S = 'sorcerer', K = 'warlock', W = 'wizard';

/** Magias do Guia de Xanathar para Todas as Coisas (2017). Listas de classe sem o Artífice. */
const specs: SpellSpec[] = [
  // Truques
  { name: 'Control Flames', pt: 'Controlar Chamas', level: 0, school: 'transmutation', classes: [D, S, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'S',
    desc: 'You shape a nonmagical flame that fits in a 5-foot cube: make it spread 5 feet, extinguish it, double or halve its light for 1 hour, or make simple shapes appear in it for 1 hour. Up to three non-instantaneous effects at a time.',
    ptDesc: 'Você molda uma chama não mágica que caiba num cubo de 1,5 m: faz ela se espalhar 1,5 m, apaga, dobra ou reduz pela metade a luz por 1 hora, ou faz formas simples aparecerem nela por 1 hora. Até três efeitos não instantâneos ao mesmo tempo.' },
  { name: 'Create Bonfire', pt: 'Criar Fogueira', level: 0, school: 'conjuration', classes: [D, S, K, W], time: 'action', range: '60 feet', duration: '1 minute', conc: true, comp: 'VS', save: 'dexterity', dmg: '1d8',
    desc: 'A bonfire fills a 5-foot cube. A creature in it when it appears, or that enters it or ends its turn there, makes a Dexterity save or takes 1d8 fire damage. Damage rises to 2d8 at 5th level, 3d8 at 11th and 4d8 at 17th.',
    ptDesc: 'Uma fogueira ocupa um cubo de 1,5 m. Quem estiver nela quando surgir, entrar ou terminar o turno ali faz um teste de Destreza ou sofre 1d8 de dano de fogo. O dano vira 2d8 no nível 5, 3d8 no 11 e 4d8 no 17.' },
  { name: 'Frostbite', pt: 'Ulceração Gélida', level: 0, school: 'evocation', classes: [D, S, K, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'VS', save: 'constitution', dmg: '1d6',
    desc: 'A creature makes a Constitution save or takes 1d6 cold damage and has disadvantage on its next weapon attack before the end of its next turn. Damage scales at 5th, 11th and 17th level.',
    ptDesc: 'Uma criatura faz um teste de Constituição ou sofre 1d6 de dano de frio e tem desvantagem no próximo ataque com arma antes do fim do próximo turno dela. O dano aumenta nos níveis 5, 11 e 17.' },
  { name: 'Gust', pt: 'Rajada', level: 0, school: 'transmutation', classes: [D, S, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'VS', save: 'strength',
    desc: 'You seize the air: push a Medium or smaller creature 5 feet (Strength save negates), push an unattended object of up to 5 pounds 10 feet, or create a harmless sensory effect with air.',
    ptDesc: 'Você controla o ar: empurra uma criatura Média ou menor 1,5 m (teste de Força evita), empurra um objeto solto de até 2,5 kg por 3 m ou cria um efeito sensorial inofensivo com o ar.' },
  { name: 'Infestation', pt: 'Infestação', level: 0, school: 'conjuration', classes: [D, S, K, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'VSM', material: 'A living flea', save: 'constitution', dmg: '1d6',
    desc: 'Mites, fleas and parasites swarm a creature: it makes a Constitution save or takes 1d6 poison damage and moves 5 feet in a random direction. Damage scales at 5th, 11th and 17th level.',
    ptDesc: 'Ácaros, pulgas e parasitas cobrem uma criatura: ela faz um teste de Constituição ou sofre 1d6 de dano venenoso e se move 1,5 m numa direção aleatória. O dano aumenta nos níveis 5, 11 e 17.' },
  { name: 'Magic Stone', pt: 'Pedra Mágica', level: 0, school: 'transmutation', classes: [D, K], time: 'bonus-action', range: 'Touch', duration: '1 minute', comp: 'VS', attack: true, dmg: '1d6',
    desc: 'You imbue up to three pebbles. A creature can throw or sling one as a ranged spell attack using your modifier, dealing 1d6 + your spellcasting modifier bludgeoning damage.',
    ptDesc: 'Você encanta até três pedrinhas. Uma criatura pode arremessá-las ou dispará-las com funda como ataque mágico à distância usando o seu modificador, causando 1d6 + modificador de conjuração de dano de concussão.' },
  { name: 'Mold Earth', pt: 'Moldar Terra', level: 0, school: 'transmutation', classes: [D, S, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'S',
    desc: 'You shape dirt or stone in a 5-foot cube: excavate and move loose earth, create shapes and colors for 1 hour, or turn the ground into difficult terrain (or back) for 1 hour.',
    ptDesc: 'Você molda terra ou pedra num cubo de 1,5 m: escava e move terra solta, cria formas e cores por 1 hora, ou transforma o chão em terreno difícil (ou desfaz isso) por 1 hora.' },
  { name: 'Primal Savagery', pt: 'Selvageria Primitiva', level: 0, school: 'transmutation', classes: [D], time: 'action', range: 'Self', duration: 'instantaneous', comp: 'S', attack: true, dmg: '1d10',
    desc: 'Your teeth or nails sharpen and you make a melee spell attack against a creature within 5 feet, dealing 1d10 acid damage. Damage scales at 5th, 11th and 17th level.',
    ptDesc: 'Seus dentes ou unhas se afiam e você faz um ataque mágico corpo a corpo contra uma criatura a 1,5 m, causando 1d10 de dano ácido. O dano aumenta nos níveis 5, 11 e 17.' },
  { name: 'Shape Water', pt: 'Moldar Água', level: 0, school: 'transmutation', classes: [D, S, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'S',
    desc: 'You control water in a 5-foot cube: move it, form shapes for 1 hour, change its color or opacity for 1 hour, or freeze it for 1 hour.',
    ptDesc: 'Você controla a água num cubo de 1,5 m: move, cria formas por 1 hora, muda a cor ou a opacidade por 1 hora, ou a congela por 1 hora.' },
  { name: 'Thunderclap', pt: 'Estrondo', level: 0, school: 'evocation', classes: [B, D, S, K, W], time: 'action', range: 'Self (5-foot radius)', duration: 'instantaneous', comp: 'S', save: 'constitution', dmg: '1d6',
    desc: 'A thunderous burst: each other creature within 5 feet makes a Constitution save or takes 1d6 thunder damage. Heard 100 feet away. Damage scales at 5th, 11th and 17th level.',
    ptDesc: 'Um estouro trovejante: cada outra criatura a 1,5 m faz um teste de Constituição ou sofre 1d6 de dano trovejante. Ouvido a 30 m. O dano aumenta nos níveis 5, 11 e 17.' },
  { name: 'Toll the Dead', pt: 'Dobre Fúnebre', level: 0, school: 'necromancy', classes: [C, K, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'VS', save: 'wisdom', dmg: '1d8',
    desc: 'A dolorous bell tolls for a creature: it makes a Wisdom save or takes 1d8 necrotic damage, or 1d12 if it is missing any hit points. Damage scales at 5th, 11th and 17th level.',
    ptDesc: 'Um sino lúgubre dobra por uma criatura: ela faz um teste de Sabedoria ou sofre 1d8 de dano necrótico, ou 1d12 se já estiver ferida. O dano aumenta nos níveis 5, 11 e 17.' },
  { name: 'Word of Radiance', pt: 'Palavra Radiante', level: 0, school: 'evocation', classes: [C], time: 'action', range: '5 feet', duration: 'instantaneous', comp: 'VM', material: 'A holy symbol', save: 'constitution', dmg: '1d6',
    desc: 'Creatures of your choice within 5 feet make a Constitution save or take 1d6 radiant damage. Damage scales at 5th, 11th and 17th level.',
    ptDesc: 'Criaturas à sua escolha a 1,5 m fazem um teste de Constituição ou sofrem 1d6 de dano radiante. O dano aumenta nos níveis 5, 11 e 17.' },
  // 1º círculo
  { name: 'Absorb Elements', pt: 'Absorver Elementos', level: 1, school: 'abjuration', classes: [D, R, S, W], time: 'reaction', range: 'Self', duration: '1 round', comp: 'S',
    desc: 'Reaction when you take acid, cold, fire, lightning or thunder damage: you have resistance to that damage type until the start of your next turn, and your first melee hit on your next turn deals an extra 1d6 of that type.',
    ptDesc: 'Reação ao sofrer dano ácido, de frio, fogo, elétrico ou trovejante: você tem resistência a esse tipo até o início do seu próximo turno, e seu primeiro acerto corpo a corpo no próximo turno causa 1d6 extra desse tipo.',
    higher: 'The extra damage increases by 1d6 per slot level above 1st.', ptHigher: 'O dano extra aumenta 1d6 por círculo acima do 1º.' },
  { name: 'Beast Bond', pt: 'Elo Animal', level: 1, school: 'divination', classes: [D, R], time: 'action', range: 'Touch', duration: '10 minutes', conc: true, comp: 'VSM', material: 'A bit of fur wrapped in a cloth',
    desc: 'You link telepathically with a friendly beast (Intelligence 3 or lower) you touch. It can share sensory information, and it has advantage on attacks against creatures within 5 feet of you that you can see.',
    ptDesc: 'Você cria um elo telepático com uma fera amistosa (Inteligência 3 ou menos) que toca. Ela compartilha o que sente e tem vantagem em ataques contra criaturas a 1,5 m de você que você vê.' },
  { name: 'Catapult', pt: 'Catapulta', level: 1, school: 'transmutation', classes: [S, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'S', save: 'dexterity', dmg: '3d8',
    desc: 'An object of 1 to 5 pounds flies up to 90 feet in a line. A creature in its path makes a Dexterity save or takes 3d8 bludgeoning damage, stopping the object.',
    ptDesc: 'Um objeto de 0,5 a 2,5 kg voa até 27 m em linha reta. Uma criatura no caminho faz um teste de Destreza ou sofre 3d8 de dano de concussão, e o objeto para.',
    higher: 'The maximum weight increases by 5 pounds and the damage by 1d8 per slot level above 1st.', ptHigher: 'O peso máximo aumenta 2,5 kg e o dano 1d8 por círculo acima do 1º.' },
  { name: 'Cause Fear', pt: 'Causar Medo', level: 1, school: 'necromancy', classes: [K, W], time: 'action', range: '60 feet', duration: '1 minute', conc: true, comp: 'V', save: 'wisdom',
    desc: 'A creature makes a Wisdom save or is frightened of you until the spell ends, repeating the save at the end of each of its turns. Constructs and undead are immune.',
    ptDesc: 'Uma criatura faz um teste de Sabedoria ou fica amedrontada por você até a magia acabar, repetindo o teste no fim de cada turno. Constructos e mortos-vivos são imunes.',
    higher: 'One additional creature per slot level above 1st.', ptHigher: 'Uma criatura adicional por círculo acima do 1º.' },
  { name: 'Ceremony', pt: 'Cerimônia', level: 1, school: 'abjuration', classes: [C, P], time: '1hour', range: 'Touch', duration: 'instantaneous', comp: 'VSM', ritual: true, material: '25 gp worth of powdered silver, which the spell consumes',
    desc: 'You perform a religious rite: atonement, blessing water, coming of age, dedication, funeral rite or wedding, each with its own minor benefit (for example, a bonus d4 on checks or saves, or +2 AC while near a spouse).',
    ptDesc: 'Você realiza um rito religioso: expiação, bênção da água, maioridade, dedicação, rito fúnebre ou casamento, cada um com um benefício menor (por exemplo, +1d4 em testes ou +2 na CA perto do cônjuge).' },
  { name: 'Chaos Bolt', pt: 'Raio do Caos', level: 1, school: 'evocation', classes: [S], time: 'action', range: '120 feet', duration: 'instantaneous', comp: 'VS', attack: true, dmg: '2d8',
    desc: 'Ranged spell attack dealing 2d8 + 1d6 damage; the d8s determine the damage type. If both d8s match, the bolt leaps to another creature within 30 feet.',
    ptDesc: 'Ataque mágico à distância que causa 2d8 + 1d6 de dano; os d8 definem o tipo de dano. Se os dois d8 forem iguais, o raio salta para outra criatura a até 9 m.',
    higher: 'Each target takes 1d6 extra damage per slot level above 1st.', ptHigher: 'Cada alvo sofre 1d6 de dano extra por círculo acima do 1º.' },
  { name: 'Earth Tremor', pt: 'Tremor de Terra', level: 1, school: 'evocation', classes: [B, D, S, W], time: 'action', range: 'Self (10-foot radius)', duration: 'instantaneous', comp: 'VS', save: 'dexterity', dmg: '1d6',
    desc: 'Each other creature within 10 feet makes a Dexterity save or takes 1d6 bludgeoning damage and is knocked prone. Loose ground becomes difficult terrain.',
    ptDesc: 'Cada outra criatura a até 3 m faz um teste de Destreza ou sofre 1d6 de dano de concussão e cai. Chão solto vira terreno difícil.',
    higher: 'Damage increases by 1d6 per slot level above 1st.', ptHigher: 'O dano aumenta 1d6 por círculo acima do 1º.' },
  { name: 'Ice Knife', pt: 'Faca de Gelo', level: 1, school: 'conjuration', classes: [D, S, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'SM', material: 'A drop of water or piece of ice', attack: true, dmg: '1d10',
    desc: 'Ranged spell attack: 1d10 piercing damage on a hit. Hit or miss, the shard explodes: the target and creatures within 5 feet make a Dexterity save or take 2d6 cold damage.',
    ptDesc: 'Ataque mágico à distância: 1d10 de dano perfurante se acertar. Acertando ou não, o estilhaço explode: o alvo e criaturas a 1,5 m fazem um teste de Destreza ou sofrem 2d6 de dano de frio.',
    higher: 'Cold damage increases by 1d6 per slot level above 1st.', ptHigher: 'O dano de frio aumenta 1d6 por círculo acima do 1º.' },
  { name: 'Snare', pt: 'Armadilha', level: 1, school: 'abjuration', classes: [D, R, W], time: '1minute', range: 'Touch', duration: '8 hours', comp: 'SM', material: '25 feet of rope, which the spell consumes', save: 'dexterity',
    desc: 'You set a nearly invisible magical trap in a 5-foot circle. A creature entering it makes a Dexterity save or is hoisted upside down and restrained, repeating the save at the end of its turns.',
    ptDesc: 'Você arma uma armadilha mágica quase invisível num círculo de 1,5 m. Quem entrar faz um teste de Destreza ou é içado de cabeça para baixo e fica impedido, repetindo o teste no fim dos turnos.' },
  { name: 'Zephyr Strike', pt: 'Golpe do Zéfiro', level: 1, school: 'transmutation', classes: [R], time: 'bonus-action', range: 'Self', duration: '1 minute', conc: true, comp: 'V',
    desc: 'Your movement doesn’t provoke opportunity attacks. Once, on a weapon attack, you can gain advantage; on a hit it deals an extra 1d8 force damage and your speed increases by 30 feet that turn.',
    ptDesc: 'Seu movimento não provoca ataques de oportunidade. Uma vez, num ataque com arma, você pode ganhar vantagem; se acertar, causa 1d8 de dano de energia extra e seu deslocamento aumenta 9 m nesse turno.' },
  // 2º círculo
  { name: 'Aganazzar’s Scorcher', pt: 'Abrasador de Aganazzar', level: 2, school: 'evocation', classes: [S, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'VSM', material: 'A red dragon’s scale', save: 'dexterity', dmg: '3d8',
    desc: 'A 30-foot-long, 5-foot-wide line of flame: each creature in it makes a Dexterity save, taking 3d8 fire damage on a failure or half on a success.',
    ptDesc: 'Uma linha de chamas de 9 m por 1,5 m: cada criatura nela faz um teste de Destreza, sofrendo 3d8 de dano de fogo se falhar ou metade se passar.',
    higher: 'Damage increases by 1d8 per slot level above 2nd.', ptHigher: 'O dano aumenta 1d8 por círculo acima do 2º.' },
  { name: 'Dragon’s Breath', pt: 'Sopro do Dragão', level: 2, school: 'transmutation', classes: [S, W], time: 'bonus-action', range: 'Touch', duration: '1 minute', conc: true, comp: 'VSM', material: 'A hot pepper', save: 'dexterity', dmg: '3d6',
    desc: 'A willing creature can use its action to exhale a 15-foot cone of acid, cold, fire, lightning or poison (chosen at casting): Dexterity save, 3d6 damage or half on a success.',
    ptDesc: 'Uma criatura voluntária pode usar a ação para exalar um cone de 4,5 m de ácido, frio, fogo, eletricidade ou veneno (escolhido na conjuração): teste de Destreza, 3d6 de dano ou metade se passar.',
    higher: 'Damage increases by 1d6 per slot level above 2nd.', ptHigher: 'O dano aumenta 1d6 por círculo acima do 2º.' },
  { name: 'Dust Devil', pt: 'Redemoinho de Poeira', level: 2, school: 'conjuration', classes: [D, S, W], time: 'action', range: '60 feet', duration: '1 minute', conc: true, comp: 'VSM', material: 'A pinch of dust', save: 'strength', dmg: '1d8',
    desc: 'A 5-foot elemental whirlwind: creatures that end their turn within 5 feet of it make a Strength save or take 1d8 bludgeoning damage and are pushed 10 feet. You can move it 30 feet as a bonus action.',
    ptDesc: 'Um redemoinho elemental de 1,5 m: quem terminar o turno a 1,5 m dele faz um teste de Força ou sofre 1d8 de dano de concussão e é empurrado 3 m. Com ação bônus, você o move 9 m.',
    higher: 'Damage increases by 1d8 per slot level above 2nd.', ptHigher: 'O dano aumenta 1d8 por círculo acima do 2º.' },
  { name: 'Earthbind', pt: 'Prender à Terra', level: 2, school: 'transmutation', classes: [D, S, K, W], time: 'action', range: '300 feet', duration: '1 minute', conc: true, comp: 'V', save: 'strength',
    desc: 'A creature makes a Strength save or its flying speed becomes 0; an airborne creature descends safely at 60 feet per round.',
    ptDesc: 'Uma criatura faz um teste de Força ou seu deslocamento de voo vira 0; se estiver no ar, desce em segurança 18 m por rodada.' },
  { name: 'Healing Spirit', pt: 'Espírito Curativo', level: 2, school: 'conjuration', classes: [D, R], time: 'bonus-action', range: '60 feet', duration: '1 minute', conc: true, comp: 'VS',
    desc: 'A spirit fills a 5-foot cube. When a creature you can see moves into it for the first time on a turn or starts its turn there, you can have it regain 1d6 hit points. Uses equal to 1 + your spellcasting modifier (minimum 2). You can move it 30 feet as a bonus action.',
    ptDesc: 'Um espírito ocupa um cubo de 1,5 m. Quando uma criatura que você vê entra nele pela primeira vez no turno ou começa o turno ali, você pode curá-la em 1d6 PV. Usos iguais a 1 + modificador de conjuração (mínimo 2). Com ação bônus, você o move 9 m.',
    higher: 'Healing increases by 1d6 per slot level above 2nd.', ptHigher: 'A cura aumenta 1d6 por círculo acima do 2º.' },
  { name: 'Maximilian’s Earthen Grasp', pt: 'Garra Terrena de Maximilian', level: 2, school: 'transmutation', classes: [S, W], time: 'action', range: '30 feet', duration: '1 minute', conc: true, comp: 'VSM', material: 'A miniature hand sculpted from clay', save: 'strength', dmg: '2d6',
    desc: 'A Medium hand of earth rises and grabs a creature within 5 feet of it: Strength save or 2d6 bludgeoning damage and restrained. As an action, you can crush it again or move the hand.',
    ptDesc: 'Uma mão Média de terra surge e agarra uma criatura a 1,5 m dela: teste de Força ou 2d6 de dano de concussão e impedida. Com uma ação, você aperta de novo ou move a mão.' },
  { name: 'Mind Spike', pt: 'Espinho Mental', level: 2, school: 'divination', classes: [S, K, W], time: 'action', range: '60 feet', duration: '1 hour', conc: true, comp: 'S', save: 'wisdom', dmg: '3d8',
    desc: 'A creature makes a Wisdom save, taking 3d8 psychic damage on a failure or half on a success. On a failure you also always know its location until the spell ends.',
    ptDesc: 'Uma criatura faz um teste de Sabedoria, sofrendo 3d8 de dano psíquico se falhar ou metade se passar. Se falhar, você sabe onde ela está até a magia acabar.',
    higher: 'Damage increases by 1d8 per slot level above 2nd.', ptHigher: 'O dano aumenta 1d8 por círculo acima do 2º.' },
  { name: 'Pyrotechnics', pt: 'Pirotecnia', level: 2, school: 'transmutation', classes: [B, S, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'VS', save: 'constitution',
    desc: 'You extinguish a nonmagical flame in a 5-foot cube and turn it into fireworks (creatures within 10 feet make a Constitution save or are blinded until your next turn) or smoke (a 20-foot cloud that heavily obscures for 1 minute).',
    ptDesc: 'Você apaga uma chama não mágica num cubo de 1,5 m e a transforma em fogos de artifício (criaturas a até 3 m fazem um teste de Constituição ou ficam cegas até o seu próximo turno) ou fumaça (nuvem de 6 m que escurece totalmente por 1 minuto).' },
  { name: 'Shadow Blade', pt: 'Lâmina Sombria', level: 2, school: 'illusion', classes: [S, K, W], time: 'bonus-action', range: 'Self', duration: '1 minute', conc: true, comp: 'VS', attack: true, dmg: '2d8',
    desc: 'You create a sword of shadow (simple melee, finesse, light, thrown 20/60) that deals 2d8 psychic damage. You have advantage with it against targets in dim light or darkness.',
    ptDesc: 'Você cria uma espada de sombra (corpo a corpo simples, acuidade, leve, arremesso 6/18 m) que causa 2d8 de dano psíquico. Tem vantagem com ela contra alvos em penumbra ou escuridão.',
    higher: '3d8 with a 3rd- or 4th-level slot, 4d8 with 5th or 6th, 5d8 with 7th or higher.', ptHigher: '3d8 com espaço de 3º ou 4º círculo, 4d8 com 5º ou 6º, 5d8 com 7º ou maior.' },
  { name: 'Skywrite', pt: 'Escrita Celeste', level: 2, school: 'transmutation', classes: [B, D, W], time: 'action', range: 'Sight', duration: '1 hour', conc: true, comp: 'VS', ritual: true,
    desc: 'You write up to ten words in clouds in the sky, visible for miles. Strong winds can disperse them.',
    ptDesc: 'Você escreve até dez palavras nas nuvens do céu, visíveis a quilômetros. Ventos fortes podem desfazê-las.' },
  { name: 'Snilloc’s Snowball Swarm', pt: 'Enxame de Bolas de Neve de Snilloc', level: 2, school: 'evocation', classes: [S, W], time: 'action', range: '90 feet', duration: 'instantaneous', comp: 'VSM', material: 'A piece of ice or a small white rock chip', save: 'dexterity', dmg: '3d6',
    desc: 'Snowballs burst in a 5-foot-radius sphere: each creature there makes a Dexterity save, taking 3d6 cold damage on a failure or half on a success.',
    ptDesc: 'Bolas de neve explodem numa esfera de 1,5 m de raio: cada criatura ali faz um teste de Destreza, sofrendo 3d6 de dano de frio se falhar ou metade se passar.',
    higher: 'Damage increases by 1d6 per slot level above 2nd.', ptHigher: 'O dano aumenta 1d6 por círculo acima do 2º.' },
  { name: 'Warding Wind', pt: 'Vento Protetor', level: 2, school: 'evocation', classes: [B, D, S, W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'V',
    desc: 'Strong wind swirls within 10 feet of you: you are deafened, it extinguishes small flames, hedges out gas, makes the area difficult terrain for others, and ranged weapon attacks into or out of it have disadvantage.',
    ptDesc: 'Um vento forte gira a até 3 m de você: você fica surdo, chamas pequenas se apagam, gases não entram, a área vira terreno difícil para os outros e ataques à distância com arma que entram ou saem dela têm desvantagem.' },
  // 3º círculo
  { name: 'Catnap', pt: 'Cochilo', level: 3, school: 'enchantment', classes: [B, S, W], time: 'action', range: '30 feet', duration: '10 minutes', comp: 'SM', material: 'A pinch of sand',
    desc: 'Up to three willing creatures fall unconscious for 10 minutes; a creature that sleeps the full duration gains the benefit of a short rest and can’t benefit from this spell again until a long rest.',
    ptDesc: 'Até três criaturas voluntárias ficam inconscientes por 10 minutos; quem dormir todo o tempo ganha os efeitos de um descanso curto e só pode se beneficiar de novo após um descanso longo.',
    higher: 'One additional creature per slot level above 3rd.', ptHigher: 'Uma criatura adicional por círculo acima do 3º.' },
  { name: 'Enemies Abound', pt: 'Inimigos por Toda Parte', level: 3, school: 'enchantment', classes: [B, S, K, W], time: 'action', range: '120 feet', duration: '1 minute', conc: true, comp: 'VS', save: 'intelligence',
    desc: 'A creature makes an Intelligence save or loses the ability to tell friend from foe, regarding everyone as enemies and choosing targets randomly. It repeats the save when it takes damage.',
    ptDesc: 'Uma criatura faz um teste de Inteligência ou deixa de distinguir amigos de inimigos, tratando todos como inimigos e escolhendo alvos ao acaso. Repete o teste ao sofrer dano.' },
  { name: 'Erupting Earth', pt: 'Erupção de Terra', level: 3, school: 'transmutation', classes: [D, S, W], time: 'action', range: '120 feet', duration: 'instantaneous', comp: 'VSM', material: 'A piece of obsidian', save: 'dexterity', dmg: '3d12',
    desc: 'Earth erupts in a 20-foot cube: each creature there makes a Dexterity save, taking 3d12 bludgeoning damage on a failure or half on a success. The ground becomes difficult terrain.',
    ptDesc: 'A terra explode num cubo de 6 m: cada criatura ali faz um teste de Destreza, sofrendo 3d12 de dano de concussão se falhar ou metade se passar. O chão vira terreno difícil.',
    higher: 'Damage increases by 1d12 per slot level above 3rd.', ptHigher: 'O dano aumenta 1d12 por círculo acima do 3º.' },
  { name: 'Flame Arrows', pt: 'Flechas Flamejantes', level: 3, school: 'transmutation', classes: [D, R, S, W], time: 'action', range: 'Touch', duration: '1 hour', conc: true, comp: 'VS', dmg: '1d6',
    desc: 'Up to twelve pieces of ammunition in a quiver deal an extra 1d6 fire damage on a hit; the magic ends on each piece when it hits or misses.',
    ptDesc: 'Até doze munições numa aljava causam 1d6 de dano de fogo extra ao acertar; a magia acaba em cada munição quando ela acerta ou erra.',
    higher: 'Two more pieces of ammunition per slot level above 3rd.', ptHigher: 'Mais duas munições por círculo acima do 3º.' },
  { name: 'Life Transference', pt: 'Transferência de Vida', level: 3, school: 'necromancy', classes: [C, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'VS', dmg: '4d8',
    desc: 'You take 4d8 necrotic damage (can’t be reduced), and one creature you can see regains twice that amount in hit points.',
    ptDesc: 'Você sofre 4d8 de dano necrótico (que não pode ser reduzido), e uma criatura que você vê recupera o dobro disso em PV.',
    higher: 'Damage increases by 1d8 per slot level above 3rd.', ptHigher: 'O dano aumenta 1d8 por círculo acima do 3º.' },
  { name: 'Melf’s Minute Meteors', pt: 'Meteoros Minúsculos de Melf', level: 3, school: 'evocation', classes: [S, W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VSM', material: 'Niter, sulfur and pine tar formed into a bead', save: 'dexterity', dmg: '2d6',
    desc: 'Six tiny meteors orbit you. When you cast it and as a bonus action on later turns, launch one or two at points within 120 feet: creatures within 5 feet of each make a Dexterity save or take 2d6 fire damage (half on success).',
    ptDesc: 'Seis pequenos meteoros orbitam você. Ao conjurar e com ação bônus nos turnos seguintes, lance um ou dois em pontos a até 36 m: criaturas a 1,5 m de cada ponto fazem um teste de Destreza ou sofrem 2d6 de dano de fogo (metade se passar).',
    higher: 'Two more meteors per slot level above 3rd.', ptHigher: 'Mais dois meteoros por círculo acima do 3º.' },
  { name: 'Summon Lesser Demons', pt: 'Invocar Demônios Menores', level: 3, school: 'conjuration', classes: [K, W], time: 'action', range: '60 feet', duration: '1 hour', conc: true, comp: 'VSM', material: 'A vial of blood from a humanoid killed within the past 24 hours',
    desc: 'You summon demons by rolling on a table (for example, two CR 1 demons or eight CR 1/4 demons). They are hostile to everyone and attack the nearest non-demons; a blood circle keeps them out.',
    ptDesc: 'Você invoca demônios rolando numa tabela (por exemplo, dois de ND 1 ou oito de ND 1/4). Eles são hostis a todos e atacam os não demônios mais próximos; um círculo de sangue os mantém fora.',
    higher: 'Twice as many demons with a 6th- or 7th-level slot, three times as many with 8th or 9th.', ptHigher: 'O dobro de demônios com espaço de 6º ou 7º círculo, o triplo com 8º ou 9º.' },
  { name: 'Thunder Step', pt: 'Passo Trovejante', level: 3, school: 'conjuration', classes: [S, K, W], time: 'action', range: '90 feet', duration: 'instantaneous', comp: 'V', save: 'constitution', dmg: '3d10',
    desc: 'You teleport up to 90 feet (optionally bringing a willing creature within 5 feet). Creatures within 10 feet of where you left make a Constitution save, taking 3d10 thunder damage on a failure or half on a success.',
    ptDesc: 'Você se teletransporta até 27 m (podendo levar uma criatura voluntária a 1,5 m). Criaturas a até 3 m do ponto de partida fazem um teste de Constituição, sofrendo 3d10 de dano trovejante se falharem ou metade se passarem.',
    higher: 'Damage increases by 1d10 per slot level above 3rd.', ptHigher: 'O dano aumenta 1d10 por círculo acima do 3º.' },
  { name: 'Tidal Wave', pt: 'Onda Gigante', level: 3, school: 'conjuration', classes: [D, S, W], time: 'action', range: '120 feet', duration: 'instantaneous', comp: 'VSM', material: 'A drop of water', save: 'dexterity', dmg: '4d8',
    desc: 'A wave 30 feet long, 10 feet wide and 10 feet tall crashes down: each creature in it makes a Dexterity save or takes 4d8 bludgeoning damage and is knocked prone (half damage on a success). It extinguishes unprotected flames.',
    ptDesc: 'Uma onda de 9 m de comprimento, 3 m de largura e 3 m de altura desaba: cada criatura nela faz um teste de Destreza ou sofre 4d8 de dano de concussão e cai (metade do dano se passar). Apaga chamas desprotegidas.' },
  { name: 'Tiny Servant', pt: 'Servo Minúsculo', level: 3, school: 'transmutation', classes: [W], time: '1minute', range: 'Touch', duration: '8 hours', comp: 'VS',
    desc: 'You animate a Tiny nonmagical object into a creature with arms and legs that obeys your commands, given as a bonus action within 120 feet.',
    ptDesc: 'Você anima um objeto não mágico Miúdo como uma criatura com braços e pernas que obedece aos seus comandos, dados com ação bônus a até 36 m.',
    higher: 'Two additional objects per slot level above 3rd.', ptHigher: 'Dois objetos adicionais por círculo acima do 3º.' },
  { name: 'Wall of Sand', pt: 'Muralha de Areia', level: 3, school: 'evocation', classes: [W], time: 'action', range: '90 feet', duration: '10 minutes', conc: true, comp: 'VSM', material: 'A handful of sand',
    desc: 'A wall of swirling sand (up to 30 feet long, 10 feet high, 10 feet thick) blocks sight; creatures inside are blinded and moving through it costs triple movement.',
    ptDesc: 'Uma muralha de areia rodopiante (até 9 m de comprimento, 3 m de altura, 3 m de espessura) bloqueia a visão; quem está dentro fica cego e atravessá-la custa o triplo de movimento.' },
  { name: 'Wall of Water', pt: 'Muralha de Água', level: 3, school: 'evocation', classes: [D, S, W], time: 'action', range: '60 feet', duration: '10 minutes', conc: true, comp: 'VSM', material: 'A drop of water',
    desc: 'A wall of water (or a ring) makes its space difficult terrain; ranged weapon attacks through it have disadvantage, fire damage through it is halved, and cold damage freezes sections of it.',
    ptDesc: 'Uma muralha de água (ou um anel) torna o espaço terreno difícil; ataques à distância com arma através dela têm desvantagem, dano de fogo através dela cai pela metade e dano de frio congela partes dela.' },
  // 4º círculo
  { name: 'Charm Monster', pt: 'Enfeitiçar Monstro', level: 4, school: 'enchantment', classes: [B, D, S, K, W], time: 'action', range: '30 feet', duration: '1 hour', comp: 'VS', save: 'wisdom',
    desc: 'A creature makes a Wisdom save (with advantage if you or your companions are fighting it) or is charmed by you for 1 hour, regarding you as a friendly acquaintance. It knows it was charmed afterwards.',
    ptDesc: 'Uma criatura faz um teste de Sabedoria (com vantagem se você ou seus aliados estiverem lutando contra ela) ou fica enfeitiçada por 1 hora, vendo você como um conhecido amistoso. Depois ela sabe que foi enfeitiçada.',
    higher: 'One additional creature per slot level above 4th.', ptHigher: 'Uma criatura adicional por círculo acima do 4º.' },
  { name: 'Elemental Bane', pt: 'Ruína Elemental', level: 4, school: 'transmutation', classes: [D, K, W], time: 'action', range: '90 feet', duration: '1 minute', conc: true, comp: 'VS', save: 'constitution', dmg: '2d6',
    desc: 'Choose acid, cold, fire, lightning or thunder. A creature makes a Constitution save or, until the spell ends, takes an extra 2d6 of that type the first time each turn it takes that damage, and loses resistance to it.',
    ptDesc: 'Escolha ácido, frio, fogo, eletricidade ou trovão. Uma criatura faz um teste de Constituição ou, até a magia acabar, sofre 2d6 extras desse tipo na primeira vez em cada turno que receber esse dano, e perde a resistência a ele.',
    higher: 'One additional creature per slot level above 4th.', ptHigher: 'Uma criatura adicional por círculo acima do 4º.' },
  { name: 'Find Greater Steed', pt: 'Encontrar Corcel Maior', level: 4, school: 'conjuration', classes: [P], time: '10minutes', range: '30 feet', duration: 'instantaneous', comp: 'VS',
    desc: 'You summon a loyal spirit in the form of a griffon, pegasus, peryton, dire wolf, rhinoceros or saber-toothed tiger. It shares your self-targeting spells and can communicate telepathically with you.',
    ptDesc: 'Você invoca um espírito leal na forma de grifo, pégaso, peryton, lobo atroz, rinoceronte ou tigre-dentes-de-sabre. Ele compartilha as magias que você lança em si e se comunica telepaticamente com você.' },
  { name: 'Guardian of Nature', pt: 'Guardião da Natureza', level: 4, school: 'transmutation', classes: [D, R], time: 'bonus-action', range: 'Self', duration: '1 minute', conc: true, comp: 'V',
    desc: 'Primal Beast: +10 feet speed, darkvision 120 feet, advantage on Strength attacks and an extra 1d6 force damage on melee hits. Great Tree: 10 temporary hit points, advantage on Constitution saves and Dexterity/Wisdom attacks, and nearby ground becomes difficult terrain for enemies.',
    ptDesc: 'Fera Primal: +3 m de deslocamento, visão no escuro de 36 m, vantagem em ataques com Força e 1d6 de dano de energia extra em acertos corpo a corpo. Grande Árvore: 10 PV temporários, vantagem em testes de Constituição e em ataques com Destreza/Sabedoria, e o chão perto vira terreno difícil para inimigos.' },
  { name: 'Shadow of Moil', pt: 'Sombra de Moil', level: 4, school: 'necromancy', classes: [K], time: 'action', range: 'Self', duration: '1 minute', conc: true, comp: 'VSM', material: 'An undead eyeball encased in a gem worth at least 150 gp', dmg: '2d8',
    desc: 'Shadowy flames wreathe you: you are heavily obscured to others, have resistance to radiant damage, and a creature within 10 feet that hits you takes 2d8 necrotic damage.',
    ptDesc: 'Chamas sombrias envolvem você: você fica totalmente obscurecido para os outros, tem resistência a dano radiante, e quem acertar você a até 3 m sofre 2d8 de dano necrótico.' },
  { name: 'Sickening Radiance', pt: 'Radiância Nauseante', level: 4, school: 'evocation', classes: [S, K, W], time: 'action', range: '120 feet', duration: '10 minutes', conc: true, comp: 'VS', save: 'constitution', dmg: '4d10',
    desc: 'A 30-foot-radius sphere of dim greenish light. A creature that starts its turn there or enters it makes a Constitution save or takes 4d10 radiant damage, gains a level of exhaustion and emits light, losing invisibility.',
    ptDesc: 'Uma esfera de 9 m de raio de luz esverdeada fraca. Quem começar o turno ou entrar nela faz um teste de Constituição ou sofre 4d10 de dano radiante, ganha um nível de exaustão e passa a brilhar, perdendo a invisibilidade.' },
  { name: 'Storm Sphere', pt: 'Esfera da Tempestade', level: 4, school: 'evocation', classes: [S, W], time: 'action', range: '150 feet', duration: '1 minute', conc: true, comp: 'VS', save: 'strength', dmg: '2d6',
    desc: 'A 20-foot-radius sphere of whirling air: creatures ending their turn in it make a Strength save or take 2d6 bludgeoning damage, and it is difficult terrain. As a bonus action, a bolt from its center makes a ranged spell attack for 4d6 lightning damage (with advantage against targets inside).',
    ptDesc: 'Uma esfera de 6 m de raio de ar rodopiante: quem terminar o turno nela faz um teste de Força ou sofre 2d6 de dano de concussão, e ela é terreno difícil. Com ação bônus, um raio do centro faz um ataque mágico à distância de 4d6 de dano elétrico (com vantagem contra alvos dentro).',
    higher: 'Both damages increase by 1d6 per slot level above 4th.', ptHigher: 'Os dois danos aumentam 1d6 por círculo acima do 4º.' },
  { name: 'Summon Greater Demon', pt: 'Invocar Demônio Maior', level: 4, school: 'conjuration', classes: [K, W], time: 'action', range: '60 feet', duration: '1 hour', conc: true, comp: 'VSM', material: 'A vial of blood from a humanoid killed within the past 24 hours',
    desc: 'You summon a demon of CR 5 or lower that obeys you. At the end of each of its turns it makes a Charisma save (with disadvantage if you speak its true name); on a success your control ends and it turns hostile. A blood circle can keep it out.',
    ptDesc: 'Você invoca um demônio de ND 5 ou menor que obedece você. No fim de cada turno dele, ele faz um teste de Carisma (com desvantagem se você disser o nome verdadeiro dele); se passar, o controle acaba e ele fica hostil. Um círculo de sangue pode mantê-lo fora.',
    higher: 'The CR increases by 1 per slot level above 4th.', ptHigher: 'O ND aumenta 1 por círculo acima do 4º.' },
  { name: 'Vitriolic Sphere', pt: 'Esfera Vitriólica', level: 4, school: 'evocation', classes: [S, W], time: 'action', range: '150 feet', duration: 'instantaneous', comp: 'VSM', material: 'A drop of giant slug bile', save: 'dexterity', dmg: '10d4',
    desc: 'An acid orb explodes in a 20-foot-radius sphere: Dexterity save, 10d4 acid damage plus 5d4 at the end of its next turn on a failure, or half the initial damage on a success.',
    ptDesc: 'Um orbe ácido explode numa esfera de 6 m de raio: teste de Destreza, 10d4 de dano ácido mais 5d4 no fim do próximo turno se falhar, ou metade do dano inicial se passar.',
    higher: 'Initial damage increases by 2d4 per slot level above 4th.', ptHigher: 'O dano inicial aumenta 2d4 por círculo acima do 4º.' },
  { name: 'Watery Sphere', pt: 'Esfera Aquosa', level: 4, school: 'conjuration', classes: [D, S, W], time: 'action', range: '90 feet', duration: '1 minute', conc: true, comp: 'VSM', material: 'A droplet of water', save: 'strength',
    desc: 'A 5-foot-radius sphere of water: up to four Medium (or one Large) creatures in it make a Strength save or are restrained inside, unable to breathe without water breathing. You can move it 30 feet as an action.',
    ptDesc: 'Uma esfera de água de 1,5 m de raio: até quatro criaturas Médias (ou uma Grande) nela fazem um teste de Força ou ficam presas dentro, impedidas e sem respirar se não respirarem na água. Com uma ação, você a move 9 m.' },
  // 5º círculo
  { name: 'Control Winds', pt: 'Controlar Ventos', level: 5, school: 'transmutation', classes: [D, S, W], time: 'action', range: '300 feet', duration: '1 hour', conc: true, comp: 'VS',
    desc: 'You control the air in a 100-foot cube: gusts that push and hinder, a downdraft that knocks fliers down, or an updraft that slows falls and lets creatures jump higher.',
    ptDesc: 'Você controla o ar num cubo de 30 m: rajadas que empurram e atrapalham, uma corrente descendente que derruba voadores ou uma ascendente que amortece quedas e aumenta saltos.' },
  { name: 'Danse Macabre', pt: 'Dança Macabra', level: 5, school: 'necromancy', classes: [K, W], time: 'action', range: '60 feet', duration: '1 hour', conc: true, comp: 'VS',
    desc: 'Up to five Small or Medium corpses rise as zombies or skeletons under your control, adding your spellcasting modifier to their attack and damage rolls.',
    ptDesc: 'Até cinco cadáveres Pequenos ou Médios se erguem como zumbis ou esqueletos sob seu controle, somando seu modificador de conjuração às jogadas de ataque e dano.',
    higher: 'Two additional corpses per slot level above 5th.', ptHigher: 'Dois cadáveres adicionais por círculo acima do 5º.' },
  { name: 'Dawn', pt: 'Alvorada', level: 5, school: 'evocation', classes: [C, W], time: 'action', range: '60 feet', duration: '1 minute', conc: true, comp: 'VSM', material: 'A sunburst pendant worth at least 100 gp', save: 'constitution', dmg: '4d10',
    desc: 'A 30-foot-radius, 40-foot-high cylinder of sunlight. Creatures in it when it appears or at the end of your turn make a Constitution save, taking 4d10 radiant damage on a failure or half on a success. You can move it 60 feet as a bonus action.',
    ptDesc: 'Um cilindro de luz do sol de 9 m de raio e 12 m de altura. Quem estiver nele quando surgir ou no fim do seu turno faz um teste de Constituição, sofrendo 4d10 de dano radiante se falhar ou metade se passar. Com ação bônus, você o move 18 m.' },
  { name: 'Enervation', pt: 'Enervação', level: 5, school: 'necromancy', classes: [S, K, W], time: 'action', range: '60 feet', duration: '1 minute', conc: true, comp: 'VS', save: 'dexterity', dmg: '4d8',
    desc: 'A tendril of darkness drains a creature: Dexterity save, 4d8 necrotic damage on a failure and again as an action on each later turn (2d8 on a success, and the spell ends). You regain half the damage dealt.',
    ptDesc: 'Um tentáculo de escuridão drena uma criatura: teste de Destreza, 4d8 de dano necrótico se falhar e de novo com uma ação nos turnos seguintes (2d8 se passar, e a magia acaba). Você recupera metade do dano causado.',
    higher: 'Damage increases by 1d8 per slot level above 5th.', ptHigher: 'O dano aumenta 1d8 por círculo acima do 5º.' },
  { name: 'Far Step', pt: 'Passo Distante', level: 5, school: 'conjuration', classes: [S, K, W], time: 'bonus-action', range: 'Self', duration: '1 minute', conc: true, comp: 'V',
    desc: 'You teleport up to 60 feet, and can do it again as a bonus action on each of your turns until the spell ends.',
    ptDesc: 'Você se teletransporta até 18 m e pode repetir com ação bônus em cada turno até a magia acabar.' },
  { name: 'Holy Weapon', pt: 'Arma Sagrada', level: 5, school: 'evocation', classes: [C, P], time: 'bonus-action', range: 'Touch', duration: '1 hour', conc: true, comp: 'VS', dmg: '2d8',
    desc: 'A weapon shines and deals an extra 2d8 radiant damage on hits. As a bonus action, you can end it to make creatures within 30 feet make a Constitution save or take 4d8 radiant damage and be blinded for 1 minute.',
    ptDesc: 'Uma arma brilha e causa 2d8 de dano radiante extra ao acertar. Com ação bônus, você pode encerrar a magia para que criaturas a até 9 m façam um teste de Constituição ou sofram 4d8 de dano radiante e fiquem cegas por 1 minuto.' },
  { name: 'Immolation', pt: 'Imolação', level: 5, school: 'evocation', classes: [S, W], time: 'action', range: '90 feet', duration: '1 minute', conc: true, comp: 'V', save: 'dexterity', dmg: '8d6',
    desc: 'A creature makes a Dexterity save, taking 8d6 fire damage on a failure (half on a success). On a failure it keeps burning, taking 4d6 at the end of each turn until it succeeds on a save.',
    ptDesc: 'Uma criatura faz um teste de Destreza, sofrendo 8d6 de dano de fogo se falhar (metade se passar). Se falhar, continua queimando e sofre 4d6 no fim de cada turno até passar num teste.' },
  { name: 'Infernal Calling', pt: 'Chamado Infernal', level: 5, school: 'conjuration', classes: [K, W], time: '1minute', range: '90 feet', duration: '1 hour', conc: true, comp: 'VSM', material: 'A ruby worth at least 999 gp',
    desc: 'You summon a devil of CR 6 or lower. It isn’t controlled; you must bargain with it or use its talisman to command it, and it may turn on you.',
    ptDesc: 'Você invoca um diabo de ND 6 ou menor. Ele não é controlado; é preciso negociar ou usar o talismã dele para comandá-lo, e ele pode se voltar contra você.',
    higher: 'The CR increases by 1 per slot level above 5th.', ptHigher: 'O ND aumenta 1 por círculo acima do 5º.' },
  { name: 'Negative Energy Flood', pt: 'Inundação de Energia Negativa', level: 5, school: 'necromancy', classes: [K, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'VM', material: 'A broken bone and a square of black silk', save: 'constitution', dmg: '5d12',
    desc: 'A creature makes a Constitution save, taking 5d12 necrotic damage on a failure (half on a success); if killed, it rises as a zombie. An undead target instead gains temporary hit points equal to half the roll.',
    ptDesc: 'Uma criatura faz um teste de Constituição, sofrendo 5d12 de dano necrótico se falhar (metade se passar); se morrer, levanta como zumbi. Um morto-vivo, em vez disso, ganha PV temporários iguais à metade da rolagem.' },
  { name: 'Skill Empowerment', pt: 'Aprimorar Perícia', level: 5, school: 'transmutation', classes: [B, S, K, W], time: 'action', range: 'Touch', duration: '1 hour', conc: true, comp: 'VS',
    desc: 'A willing creature doubles its proficiency bonus for one skill it is proficient in.',
    ptDesc: 'Uma criatura voluntária dobra o bônus de proficiência numa perícia em que é proficiente.' },
  { name: 'Steel Wind Strike', pt: 'Golpe do Vento de Aço', level: 5, school: 'conjuration', classes: [R, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'SM', material: 'A melee weapon worth at least 1 sp', attack: true, dmg: '6d10',
    desc: 'You vanish and strike up to five creatures within range, making a melee spell attack against each for 6d10 force damage, then teleport next to one of them.',
    ptDesc: 'Você some e golpeia até cinco criaturas no alcance, fazendo um ataque mágico corpo a corpo contra cada uma com 6d10 de dano de energia, e depois se teletransporta para perto de uma delas.' },
  { name: 'Synaptic Static', pt: 'Estática Sináptica', level: 5, school: 'enchantment', classes: [B, S, K, W], time: 'action', range: '120 feet', duration: 'instantaneous', comp: 'VS', save: 'intelligence', dmg: '8d6',
    desc: 'Psychic energy bursts in a 20-foot-radius sphere: Intelligence save, 8d6 psychic damage (half on a success). On a failure, the creature subtracts 1d6 from attacks, checks and concentration saves for 1 minute.',
    ptDesc: 'Energia psíquica explode numa esfera de 6 m de raio: teste de Inteligência, 8d6 de dano psíquico (metade se passar). Se falhar, a criatura subtrai 1d6 de ataques, testes e testes de concentração por 1 minuto.' },
  { name: 'Transmute Rock', pt: 'Transmutar Rocha', level: 5, school: 'transmutation', classes: [D, W], time: 'action', range: '120 feet', duration: 'until dispelled', comp: 'VSM', material: 'Clay and water',
    desc: 'You turn stone in a 40-foot cube into mud (creatures sink and are restrained) or mud into stone (creatures inside are trapped until they break free).',
    ptDesc: 'Você transforma a pedra num cubo de 12 m em lama (criaturas afundam e ficam impedidas) ou lama em pedra (criaturas dentro ficam presas até se soltarem).' },
  { name: 'Wall of Light', pt: 'Muralha de Luz', level: 5, school: 'evocation', classes: [S, K, W], time: 'action', range: '120 feet', duration: '10 minutes', conc: true, comp: 'VSM', material: 'A hand mirror', save: 'constitution', dmg: '4d8',
    desc: 'A 60-foot-long wall of light blocks sight. Creatures in its area when it appears make a Constitution save or take 4d8 radiant damage and are blinded. As an action, fire a beam from it as a ranged spell attack for 4d8 radiant, shrinking the wall by 10 feet.',
    ptDesc: 'Uma muralha de luz de 18 m bloqueia a visão. Quem estiver na área quando surgir faz um teste de Constituição ou sofre 4d8 de dano radiante e fica cego. Com uma ação, dispare um raio dela como ataque mágico à distância de 4d8 radiante, encolhendo a muralha 3 m.',
    higher: 'Damage increases by 1d8 per slot level above 5th.', ptHigher: 'O dano aumenta 1d8 por círculo acima do 5º.' },
  { name: 'Wrath of Nature', pt: 'Ira da Natureza', level: 5, school: 'evocation', classes: [D, R], time: 'action', range: '120 feet', duration: '1 minute', conc: true, comp: 'VS',
    desc: 'Nature in a 60-foot cube turns against your foes: grasping grass and undergrowth, trees that strike (4d6 slashing), roots that restrain, and rocks you can hurl (3d8 bludgeoning).',
    ptDesc: 'A natureza num cubo de 18 m se volta contra seus inimigos: capim e mato que agarram, árvores que golpeiam (4d6 cortante), raízes que prendem e pedras que você arremessa (3d8 concussão).' },
  // 6º círculo
  { name: 'Bones of the Earth', pt: 'Ossos da Terra', level: 6, school: 'transmutation', classes: [D], time: 'action', range: '120 feet', duration: 'instantaneous', comp: 'VS', save: 'dexterity', dmg: '6d6',
    desc: 'Up to six stone pillars burst from the ground. A creature on top is lifted; one that would be pinned against a ceiling makes a Dexterity save or takes 6d6 bludgeoning damage and is restrained.',
    ptDesc: 'Até seis pilares de pedra irrompem do chão. Quem estiver em cima é erguido; quem for prensado contra um teto faz um teste de Destreza ou sofre 6d6 de dano de concussão e fica impedido.',
    higher: 'Two more pillars per slot level above 6th.', ptHigher: 'Mais dois pilares por círculo acima do 6º.' },
  { name: 'Create Homunculus', pt: 'Criar Homúnculo', level: 6, school: 'transmutation', classes: [W], time: '1hour', range: 'Touch', duration: 'instantaneous', comp: 'VSM', material: 'Clay, ash and mandrake root, which the spell consumes, and a jewel-encrusted dagger worth at least 1,000 gp',
    desc: 'You take 2d4 piercing damage that can’t be reduced and create a homunculus bound to you. You can transfer hit points to it and share its senses. Your hit point maximum drops by the damage dealt.',
    ptDesc: 'Você sofre 2d4 de dano perfurante que não pode ser reduzido e cria um homúnculo ligado a você. Pode transferir PV para ele e compartilhar os sentidos dele. Seu máximo de PV cai pelo dano sofrido.' },
  { name: 'Druid Grove', pt: 'Bosque Druídico', level: 6, school: 'abjuration', classes: [D], time: '10minutes', range: 'Touch', duration: '24 hours', comp: 'VSM', material: 'Mistletoe, which the spell consumes, harvested with a golden sickle under a full moon',
    desc: 'You ward an area up to a 90-foot cube outdoors: solid fog, grasping undergrowth, animated trees, hidden paths and other defenses protect it. Casting it daily for a year makes it permanent.',
    ptDesc: 'Você protege uma área de até um cubo de 27 m ao ar livre: neblina densa, mato que agarra, árvores animadas, trilhas ocultas e outras defesas. Conjurar todo dia por um ano a torna permanente.' },
  { name: 'Investiture of Flame', pt: 'Investidura da Chama', level: 6, school: 'transmutation', classes: [D, S, K, W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VS', save: 'dexterity', dmg: '4d8',
    desc: 'You are wreathed in flame: immunity to fire, resistance to cold, creatures near you take 1d10 fire damage, and as an action you can create a 15-foot line of fire (Dexterity save, 4d8 fire damage, half on a success).',
    ptDesc: 'Chamas envolvem você: imunidade a fogo, resistência a frio, quem estiver perto sofre 1d10 de dano de fogo e, com uma ação, você cria uma linha de fogo de 4,5 m (teste de Destreza, 4d8 de dano de fogo, metade se passar).' },
  { name: 'Investiture of Ice', pt: 'Investidura do Gelo', level: 6, school: 'transmutation', classes: [D, S, K, W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VS', save: 'constitution', dmg: '4d6',
    desc: 'Frost covers you: immunity to cold, resistance to fire, you ignore ice and snow as difficult terrain, the ground near you becomes difficult terrain, and as an action you can create a 15-foot cone of cold (Constitution save, 4d6 cold damage and halved speed; half damage on a success).',
    ptDesc: 'Gelo cobre você: imunidade a frio, resistência a fogo, gelo e neve não são terreno difícil para você, o chão ao seu redor vira terreno difícil e, com uma ação, você cria um cone de frio de 4,5 m (teste de Constituição, 4d6 de dano de frio e deslocamento pela metade; metade do dano se passar).' },
  { name: 'Investiture of Stone', pt: 'Investidura da Pedra', level: 6, school: 'transmutation', classes: [D, S, K, W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VS', save: 'dexterity',
    desc: 'You gain resistance to nonmagical bludgeoning, piercing and slashing damage, can make the ground tremble as an action (Dexterity save or prone), and can move through earth and stone without disturbing it.',
    ptDesc: 'Você ganha resistência a dano de concussão, perfuração e corte não mágicos, pode fazer o chão tremer com uma ação (teste de Destreza ou cai) e atravessa terra e pedra sem perturbá-las.' },
  { name: 'Investiture of Wind', pt: 'Investidura do Vento', level: 6, school: 'transmutation', classes: [D, S, K, W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VS', save: 'constitution', dmg: '2d10',
    desc: 'Wind swirls around you: ranged weapon attacks against you have disadvantage, you gain a 60-foot flying speed, and as an action you can create a 15-foot cube of wind (Constitution save, 2d10 bludgeoning damage and pushed 10 feet).',
    ptDesc: 'O vento gira ao seu redor: ataques à distância com arma contra você têm desvantagem, você ganha voo de 18 m e, com uma ação, cria um cubo de vento de 4,5 m (teste de Constituição, 2d10 de dano de concussão e empurrado 3 m).' },
  { name: 'Mental Prison', pt: 'Prisão Mental', level: 6, school: 'illusion', classes: [S, K, W], time: 'action', range: '60 feet', duration: '1 minute', conc: true, comp: 'S', save: 'intelligence', dmg: '5d10',
    desc: 'A creature makes an Intelligence save, taking 5d10 psychic damage on a failure (half on a success). On a failure, it believes it is surrounded by danger and is restrained; leaving the illusion deals 10d10 psychic damage.',
    ptDesc: 'Uma criatura faz um teste de Inteligência, sofrendo 5d10 de dano psíquico se falhar (metade se passar). Se falhar, acredita estar cercada de perigo e fica impedida; sair da ilusão causa 10d10 de dano psíquico.' },
  { name: 'Primordial Ward', pt: 'Proteção Primordial', level: 6, school: 'abjuration', classes: [D], time: 'action', range: 'Self', duration: '1 minute', conc: true, comp: 'VS',
    desc: 'You have resistance to acid, cold, fire, lightning and thunder. When you take damage of one of those types, you can use your reaction to gain immunity to it instead, ending the resistances.',
    ptDesc: 'Você tem resistência a ácido, frio, fogo, eletricidade e trovão. Ao sofrer dano de um desses tipos, pode usar a reação para ter imunidade a ele, encerrando as resistências.' },
  { name: 'Scatter', pt: 'Dispersar', level: 6, school: 'conjuration', classes: [S, K, W], time: 'action', range: '30 feet', duration: 'instantaneous', comp: 'V', save: 'wisdom',
    desc: 'Up to five creatures are teleported up to 120 feet to unoccupied spaces you can see; unwilling creatures make a Wisdom save to resist.',
    ptDesc: 'Até cinco criaturas são teletransportadas até 36 m para espaços livres que você vê; criaturas relutantes fazem um teste de Sabedoria para resistir.' },
  { name: 'Soul Cage', pt: 'Gaiola de Almas', level: 6, school: 'necromancy', classes: [K, W], time: 'reaction', range: '60 feet', duration: '8 hours', comp: 'VSM', material: 'A tiny silver cage worth 100 gp',
    desc: 'Reaction when a humanoid dies: you trap its soul. Up to six times, you can use it to heal yourself (2d8), ask it a question, gain advantage on a roll, or peer into a place it knew in life.',
    ptDesc: 'Reação quando um humanoide morre: você aprisiona a alma dele. Até seis vezes, pode usá-la para se curar (2d8), fazer uma pergunta, ganhar vantagem numa jogada ou ver um lugar que ele conhecia em vida.' },
  { name: 'Tenser’s Transformation', pt: 'Transformação de Tenser', level: 6, school: 'transmutation', classes: [W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VSM', material: 'A few hairs from a bull',
    desc: 'You gain 50 temporary hit points, advantage on weapon attacks, +2d12 force damage on weapon hits, martial weapon and armor proficiency, Strength and Constitution save proficiency, and an extra attack. You can’t cast spells, and you must succeed on a Constitution save at the end or gain exhaustion.',
    ptDesc: 'Você ganha 50 PV temporários, vantagem em ataques com arma, +2d12 de dano de energia ao acertar com arma, proficiência com armas marciais e armaduras, proficiência em testes de Força e Constituição e um ataque extra. Não pode conjurar magias e, ao fim, faz um teste de Constituição ou ganha exaustão.' },
  // 7º círculo
  { name: 'Crown of Stars', pt: 'Coroa de Estrelas', level: 7, school: 'evocation', classes: [S, K, W], time: 'action', range: 'Self', duration: '1 hour', comp: 'VS', attack: true, dmg: '4d12',
    desc: 'Seven motes of light orbit your head. As a bonus action, send one at a creature within 120 feet as a ranged spell attack for 4d12 radiant damage.',
    ptDesc: 'Sete pontos de luz orbitam sua cabeça. Com ação bônus, lance um numa criatura a até 36 m como ataque mágico à distância de 4d12 de dano radiante.',
    higher: 'Two more motes per slot level above 7th.', ptHigher: 'Mais dois pontos por círculo acima do 7º.' },
  { name: 'Power Word Pain', pt: 'Palavra de Poder: Dor', level: 7, school: 'enchantment', classes: [S, K, W], time: 'action', range: '60 feet', duration: 'instantaneous', comp: 'V',
    desc: 'A creature with 100 hit points or fewer is wracked with pain: speed no more than 10 feet, disadvantage on attacks, checks and most saves, and a Constitution save to cast spells. It repeats a Constitution save at the end of each turn.',
    ptDesc: 'Uma criatura com 100 PV ou menos é tomada pela dor: deslocamento máximo de 3 m, desvantagem em ataques, testes e na maioria das resistências, e precisa de um teste de Constituição para conjurar. Repete o teste de Constituição no fim de cada turno.' },
  { name: 'Temple of the Gods', pt: 'Templo dos Deuses', level: 7, school: 'conjuration', classes: [C], time: '1hour', range: '120 feet', duration: '24 hours', comp: 'VSM', material: 'A holy symbol worth at least 5 gp',
    desc: 'A temple of up to 120 feet appears, dedicated to your deity. Certain creature types must save to enter, divination can’t see inside, and healing spells cast inside are strengthened.',
    ptDesc: 'Surge um templo de até 36 m dedicado à sua divindade. Certos tipos de criatura precisam passar num teste para entrar, adivinhações não enxergam dentro, e magias de cura lá dentro são fortalecidas.' },
  { name: 'Whirlwind', pt: 'Turbilhão', level: 7, school: 'evocation', classes: [D, S, W], time: 'action', range: '300 feet', duration: '1 minute', conc: true, comp: 'VM', material: 'A piece of straw', save: 'dexterity', dmg: '10d6',
    desc: 'A 10-foot-radius, 30-foot-high whirlwind: creatures in it make a Dexterity save or take 10d6 bludgeoning damage (half on a success); a Large or smaller creature that fails is also pulled in and restrained.',
    ptDesc: 'Um turbilhão de 3 m de raio e 9 m de altura: quem estiver nele faz um teste de Destreza ou sofre 10d6 de dano de concussão (metade se passar); uma criatura Grande ou menor que falhar também é puxada para dentro e fica impedida.' },
  // 8º círculo
  { name: 'Abi-Dalzim’s Horrid Wilting', pt: 'Murchar Horrendo de Abi-Dalzim', level: 8, school: 'necromancy', classes: [S, W], time: 'action', range: '150 feet', duration: 'instantaneous', comp: 'VSM', material: 'A bit of sponge', save: 'constitution', dmg: '12d8',
    desc: 'Moisture is drawn from creatures in a 30-foot cube: Constitution save, 12d8 necrotic damage (half on a success). Constructs and undead are unaffected; plants and water elementals have disadvantage.',
    ptDesc: 'A umidade é sugada das criaturas num cubo de 9 m: teste de Constituição, 12d8 de dano necrótico (metade se passar). Constructos e mortos-vivos não são afetados; plantas e elementais da água têm desvantagem.' },
  { name: 'Illusory Dragon', pt: 'Dragão Ilusório', level: 8, school: 'illusion', classes: [W], time: 'action', range: '120 feet', duration: '1 minute', conc: true, comp: 'S', save: 'intelligence', dmg: '7d6',
    desc: 'A Huge shadow dragon frightens creatures that see it (Wisdom save). As a bonus action it moves and breathes a 60-foot cone: Intelligence save, 7d6 damage of a type you choose (half on a success).',
    ptDesc: 'Um dragão de sombra Enorme amedronta quem o vê (teste de Sabedoria). Com ação bônus, ele se move e exala um cone de 18 m: teste de Inteligência, 7d6 de dano de um tipo à sua escolha (metade se passar).' },
  { name: 'Maddening Darkness', pt: 'Escuridão Enlouquecedora', level: 8, school: 'evocation', classes: [K, W], time: 'action', range: '150 feet', duration: '10 minutes', conc: true, comp: 'VM', material: 'A drop of pitch mixed with a drop of mercury', save: 'wisdom', dmg: '8d8',
    desc: 'Magical darkness fills a 60-foot-radius sphere, filled with whispers. A creature that starts its turn there makes a Wisdom save, taking 8d8 psychic damage on a failure (half on a success).',
    ptDesc: 'Escuridão mágica cheia de sussurros preenche uma esfera de 18 m de raio. Quem começar o turno nela faz um teste de Sabedoria, sofrendo 8d8 de dano psíquico se falhar (metade se passar).' },
  { name: 'Mighty Fortress', pt: 'Fortaleza Poderosa', level: 8, school: 'conjuration', classes: [W], time: '1minute', range: '1 mile', duration: 'instantaneous', comp: 'VSM', material: 'A diamond worth at least 500 gp, which the spell consumes',
    desc: 'A stone fortress with four towers, walls and a keep rises from the ground, staffed by invisible servants. It lasts 7 days, or becomes permanent if cast in the same place every week for a year.',
    ptDesc: 'Uma fortaleza de pedra com quatro torres, muralhas e uma torre de menagem surge do chão, com servos invisíveis. Dura 7 dias, ou fica permanente se conjurada no mesmo lugar toda semana por um ano.' },
  // 9º círculo
  { name: 'Invulnerability', pt: 'Invulnerabilidade', level: 9, school: 'abjuration', classes: [W], time: 'action', range: 'Self', duration: '10 minutes', conc: true, comp: 'VSM', material: 'A small piece of adamantine worth at least 500 gp, which the spell consumes',
    desc: 'You are immune to all damage until the spell ends.',
    ptDesc: 'Você fica imune a todo dano até a magia acabar.' },
  { name: 'Mass Polymorph', pt: 'Metamorfose em Massa', level: 9, school: 'transmutation', classes: [B, S, W], time: 'action', range: '120 feet', duration: '1 hour', conc: true, comp: 'VSM', material: 'A caterpillar cocoon', save: 'wisdom',
    desc: 'Up to ten creatures transform into beasts of a challenge rating no higher than their own (or half their level); unwilling creatures make a Wisdom save.',
    ptDesc: 'Até dez criaturas viram feras de ND igual ou menor ao delas (ou metade do nível); criaturas relutantes fazem um teste de Sabedoria.' },
  { name: 'Psychic Scream', pt: 'Grito Psíquico', level: 9, school: 'enchantment', classes: [B, S, K, W], time: 'action', range: '90 feet', duration: 'instantaneous', comp: 'S', save: 'intelligence', dmg: '14d6',
    desc: 'Up to ten creatures with Intelligence 3 or higher make an Intelligence save, taking 14d6 psychic damage and being stunned on a failure (half damage on a success). A creature killed has its head explode.',
    ptDesc: 'Até dez criaturas com Inteligência 3 ou mais fazem um teste de Inteligência, sofrendo 14d6 de dano psíquico e ficando atordoadas se falharem (metade do dano se passarem). Quem morrer tem a cabeça explodida.' },
];

export const xgeSpells = specs.map((s) => spell('xge', s));
