import { subclass, type SubclassSpec } from './helpers';

/** Subclasses do Guia de Xanathar para Todas as Coisas (2017). */
const specs: SubclassSpec[] = [
  // Bárbaro
  {
    cls: 'barbarian',
    name: 'Path of the Ancestral Guardian',
    pt: 'Caminho do Guardião Ancestral',
    desc: 'Barbarians who call on the spirits of honored ancestors to shield their allies and punish foes.',
    ptDesc: 'Bárbaros que invocam os espíritos de ancestrais honrados para proteger os aliados e punir os inimigos.',
    features: [
      [3, 'Ancestral Protectors', 'Protetores Ancestrais', 'While raging, the first creature you hit on your turn is hindered by spectral warriors until the start of your next turn: it has disadvantage on attacks against anyone but you, and when it hits someone other than you, that target has resistance to the damage.', 'Em fúria, a primeira criatura que você atinge no seu turno é atrapalhada por guerreiros espectrais até o início do seu próximo turno: ela tem desvantagem em ataques contra qualquer um que não seja você e, quando acerta outra criatura, o alvo tem resistência ao dano.'],
      [[6, 10, 14], 'Spirit Shield', 'Escudo Espiritual', 'While raging, when a creature you can see within 30 feet takes damage, you can use your reaction to reduce that damage by 2d6 (3d6 at 10th level, 4d6 at 14th).', 'Em fúria, quando uma criatura que você vê a até 9 m sofre dano, você pode usar sua reação para reduzir o dano em 2d6 (3d6 no nível 10, 4d6 no 14).'],
      [10, 'Consult the Spirits', 'Consultar os Espíritos', 'You can cast Augury or Clairvoyance without a spell slot or components, using Wisdom. Once you do, you need a short or long rest to do it again.', 'Você pode conjurar Augúrio ou Clarividência sem espaço de magia nem componentes, usando Sabedoria. Depois disso, precisa de um descanso curto ou longo para repetir.'],
      [14, 'Vengeful Ancestors', 'Ancestrais Vingativos', 'When Spirit Shield reduces damage, the attacker takes force damage equal to the amount prevented.', 'Quando o Escudo Espiritual reduz um dano, o atacante sofre dano de energia igual ao valor evitado.'],
    ],
  },
  {
    cls: 'barbarian',
    name: 'Path of the Storm Herald',
    pt: 'Caminho do Arauto da Tempestade',
    desc: 'Barbarians whose rage becomes a storm aura shaped by desert, sea or tundra.',
    ptDesc: 'Bárbaros cuja fúria vira uma aura de tempestade moldada pelo deserto, pelo mar ou pela tundra.',
    features: [
      [3, 'Storm Aura', 'Aura da Tempestade', 'While raging you emit a 10-foot aura (choose desert, sea or tundra; you can change it on level up). You can activate its effect when you rage and again as a bonus action on later turns. Desert: creatures of your choice in the aura take 2 fire damage (scales with level). Sea: one creature in the aura makes a Dexterity save or takes 1d6 lightning damage (half on success; scales). Tundra: creatures of your choice in the aura gain 2 temporary hit points (scales). The save DC is 8 + proficiency + Constitution.', 'Em fúria você emana uma aura de 3 m (escolha deserto, mar ou tundra; pode trocar ao subir de nível). Você ativa o efeito ao entrar em fúria e de novo com uma ação bônus nos turnos seguintes. Deserto: criaturas à sua escolha na aura sofrem 2 de dano de fogo (aumenta com o nível). Mar: uma criatura na aura faz um teste de Destreza ou sofre 1d6 de dano elétrico (metade se passar; aumenta). Tundra: criaturas à sua escolha na aura ganham 2 PV temporários (aumenta). CD = 8 + proficiência + Constituição.'],
      [6, 'Storm Soul', 'Alma da Tempestade', 'Desert: resistance to fire, ignore extreme heat, and you can ignite unattended flammable objects. Sea: resistance to lightning, breathe underwater and swim speed 30 feet. Tundra: resistance to cold, ignore extreme cold, and you can freeze a 5-foot cube of water.', 'Deserto: resistência a fogo, ignora calor extremo e pode incendiar objetos inflamáveis soltos. Mar: resistência a elétrico, respira debaixo d’água e ganha deslocamento de natação 9 m. Tundra: resistência a frio, ignora frio extremo e pode congelar um cubo de 1,5 m de água.'],
      [10, 'Shielding Storm', 'Tempestade Protetora', 'Creatures of your choice in your aura gain the resistance from your Storm Soul.', 'Criaturas à sua escolha na sua aura ganham a resistência da sua Alma da Tempestade.'],
      [14, 'Raging Storm', 'Tempestade Furiosa', 'Desert: when a creature in your aura hits you, you can use your reaction to force a Dexterity save or it takes fire damage equal to half your barbarian level. Sea: when you hit a creature in your aura, you can use your reaction to force a Strength save or knock it prone. Tundra: when your aura activates, you can force one creature in it to make a Strength save or have speed 0 until your next turn.', 'Deserto: quando uma criatura na aura acerta você, sua reação a obriga a um teste de Destreza ou sofre dano de fogo igual à metade do seu nível de bárbaro. Mar: ao acertar uma criatura na aura, sua reação a obriga a um teste de Força ou ela cai. Tundra: quando a aura é ativada, você obriga uma criatura nela a um teste de Força ou ela fica com deslocamento 0 até o seu próximo turno.'],
    ],
  },
  {
    cls: 'barbarian',
    name: 'Path of the Zealot',
    pt: 'Caminho do Fanático',
    desc: 'Barbarians fueled by divine fury, whose gods refuse to let them stay dead.',
    ptDesc: 'Bárbaros movidos por fúria divina, cujos deuses não os deixam ficar mortos.',
    features: [
      [3, 'Divine Fury', 'Fúria Divina', 'While raging, the first creature you hit with a weapon on each turn takes extra 1d6 + half your barbarian level damage, necrotic or radiant (chosen when you gain this feature).', 'Em fúria, a primeira criatura que você acerta com uma arma em cada turno sofre 1d6 + metade do seu nível de bárbaro de dano extra, necrótico ou radiante (escolhido ao ganhar a habilidade).'],
      [3, 'Warrior of the Gods', 'Guerreiro dos Deuses', 'Spells that would bring you back to life don’t need material components.', 'Magias que trariam você de volta à vida não precisam de componentes materiais.'],
      [6, 'Fanatical Focus', 'Foco Fanático', 'Once per rage, if you fail a saving throw, you can reroll it and must use the new roll.', 'Uma vez por fúria, se falhar num teste de resistência, você pode rolar de novo e usar o novo resultado.'],
      [10, 'Zealous Presence', 'Presença Zelosa', 'As a bonus action, up to ten creatures of your choice within 60 feet that can hear you gain advantage on attack rolls and saving throws until the start of your next turn. Once per long rest.', 'Com uma ação bônus, até dez criaturas à sua escolha a até 18 m que ouvem você ganham vantagem em jogadas de ataque e testes de resistência até o início do seu próximo turno. Uma vez por descanso longo.'],
      [14, 'Rage Beyond Death', 'Fúria Além da Morte', 'While raging, dropping to 0 hit points doesn’t knock you unconscious. You still make death saves and suffer damage normally, but you only die from failed death saves when the rage ends while you are still at 0 hit points.', 'Em fúria, cair a 0 PV não deixa você inconsciente. Você ainda faz testes contra a morte e sofre dano normalmente, mas só morre por eles se a fúria acabar e você continuar com 0 PV.'],
    ],
  },
  // Bardo
  {
    cls: 'bard',
    name: 'College of Glamour',
    pt: 'Colégio do Glamour',
    desc: 'Bards touched by the Feywild, who weave beguiling magic into their performances.',
    ptDesc: 'Bardos tocados pela Agrestia das Fadas, que tecem magia sedutora nas apresentações.',
    features: [
      [3, 'Mantle of Inspiration', 'Manto de Inspiração', 'As a bonus action, spend a Bardic Inspiration die to give up to as many creatures as your Charisma modifier (minimum 1) within 60 feet temporary hit points (5 at 3rd level, increasing to 14 at 15th). Each can immediately use its reaction to move its speed without provoking opportunity attacks.', 'Com uma ação bônus, gaste um dado de Inspiração de Bardo para dar a até um número de criaturas igual ao seu modificador de Carisma (mínimo 1) a até 18 m PV temporários (5 no nível 3, até 14 no 15). Cada uma pode usar a reação para se mover o próprio deslocamento sem provocar ataques de oportunidade.'],
      [3, 'Enthralling Performance', 'Apresentação Cativante', 'After performing for at least 1 minute, choose up to as many humanoids as your Charisma modifier who watched; each makes a Wisdom save or is charmed by you for 1 hour, idolizing you and hindering anyone who opposes you. Once per short or long rest.', 'Depois de se apresentar por pelo menos 1 minuto, escolha até um número de humanoides igual ao seu modificador de Carisma que assistiram; cada um faz um teste de Sabedoria ou fica enfeitiçado por você por 1 hora, idolatrando você. Uma vez por descanso curto ou longo.'],
      [6, 'Mantle of Majesty', 'Manto de Majestade', 'As a bonus action, cast Command without a slot, then cast it again as a bonus action on each of your turns for 1 minute (concentration). Charmed creatures automatically fail the save. Once per long rest.', 'Com uma ação bônus, conjure Comando sem espaço e repita a conjuração com uma ação bônus em cada turno por 1 minuto (concentração). Criaturas enfeitiçadas por você falham automaticamente. Uma vez por descanso longo.'],
      [14, 'Unbreakable Majesty', 'Majestade Inquebrável', 'As a bonus action, for 1 minute, a creature that tries to attack you for the first time on a turn must make a Charisma save or choose another target (or lose the attack). On a success, it has disadvantage on saves against your spells on your next turn. Once per short or long rest.', 'Com uma ação bônus, por 1 minuto, a criatura que tentar atacar você pela primeira vez num turno faz um teste de Carisma ou precisa escolher outro alvo (ou perde o ataque). Se passar, tem desvantagem em testes contra suas magias no seu próximo turno. Uma vez por descanso curto ou longo.'],
    ],
  },
  {
    cls: 'bard',
    name: 'College of Swords',
    pt: 'Colégio das Espadas',
    desc: 'Blade-wielding bards who turn combat into a dazzling show.',
    ptDesc: 'Bardos de lâmina que transformam o combate num espetáculo deslumbrante.',
    features: [
      [3, 'Bonus Proficiencies', 'Proficiências Adicionais', 'You gain proficiency with medium armor and scimitars, and you can use a simple or martial melee weapon you are proficient with as a spellcasting focus.', 'Você ganha proficiência com armaduras médias e cimitarras e pode usar uma arma corpo a corpo simples ou marcial com a qual é proficiente como foco de conjuração.'],
      [3, 'Fighting Style', 'Estilo de Luta', 'Choose Dueling or Two-Weapon Fighting.', 'Escolha Duelismo ou Combate com Duas Armas.'],
      [3, 'Blade Flourish', 'Floreio de Lâmina', 'When you take the Attack action, your walking speed increases by 10 feet that turn. Once per turn when you hit with a weapon, you can spend a Bardic Inspiration die for a flourish: Defensive (add the die to damage and to your AC until your next turn), Slashing (add the die to damage against the target and another creature within 5 feet of you), or Mobile (add the die to damage and push the target up to 5 + the die roll feet; you can follow it with your reaction).', 'Ao usar a ação Atacar, seu deslocamento aumenta em 3 m nesse turno. Uma vez por turno, ao acertar com uma arma, você pode gastar um dado de Inspiração de Bardo num floreio: Defensivo (soma o dado ao dano e à CA até o seu próximo turno), Cortante (soma o dado ao dano do alvo e de outra criatura a 1,5 m de você) ou Móvel (soma o dado ao dano e empurra o alvo 1,5 m + o resultado; você pode segui-lo com a reação).'],
      [6, 'Extra Attack', 'Ataque Extra', 'You can attack twice when you take the Attack action.', 'Você pode atacar duas vezes ao usar a ação Atacar.'],
      [14, 'Master’s Flourish', 'Floreio de Mestre', 'When you use a Blade Flourish, you can roll a d6 instead of spending a Bardic Inspiration die.', 'Ao usar um Floreio de Lâmina, você pode rolar um d6 em vez de gastar um dado de Inspiração de Bardo.'],
    ],
  },
  {
    cls: 'bard',
    name: 'College of Whispers',
    pt: 'Colégio dos Sussurros',
    desc: 'Bards who trade in secrets and fear, posing as ordinary performers.',
    ptDesc: 'Bardos que negociam segredos e medo, disfarçados de artistas comuns.',
    features: [
      [3, 'Psychic Blades', 'Lâminas Psíquicas', 'Once per turn when you hit with a weapon, you can spend a Bardic Inspiration die to deal extra psychic damage: 2d6, rising to 3d6 at 5th, 5d6 at 10th and 8d6 at 15th level.', 'Uma vez por turno, ao acertar com uma arma, você pode gastar um dado de Inspiração de Bardo para causar dano psíquico extra: 2d6, 3d6 no nível 5, 5d6 no 10 e 8d6 no 15.'],
      [3, 'Words of Terror', 'Palavras de Terror', 'After speaking alone with a humanoid for at least 1 minute, it makes a Wisdom save or is frightened of you or a creature of your choice for 1 hour (ends if attacked or damaged). Once per short or long rest.', 'Depois de falar a sós com um humanoide por pelo menos 1 minuto, ele faz um teste de Sabedoria ou fica amedrontado por você ou por uma criatura à sua escolha por 1 hora (acaba se ele for atacado ou ferido). Uma vez por descanso curto ou longo.'],
      [6, 'Mantle of Whispers', 'Manto de Sussurros', 'When a humanoid dies within 30 feet, you can use your reaction to capture its shadow and later, as an action, take on its appearance for 1 hour, gaining a superficial knowledge of its life. Once per short or long rest.', 'Quando um humanoide morre a até 9 m, você pode usar a reação para capturar a sombra dele e depois, com uma ação, assumir a aparência dele por 1 hora, com um conhecimento superficial da vida dele. Uma vez por descanso curto ou longo.'],
      [14, 'Shadow Lore', 'Saber das Sombras', 'As an action, a creature within 30 feet that can understand you makes a Wisdom save or is charmed by you for 8 hours, believing you know its deepest secret and obeying your commands. Once per long rest.', 'Com uma ação, uma criatura a até 9 m que entende você faz um teste de Sabedoria ou fica enfeitiçada por 8 horas, acreditando que você sabe o segredo mais profundo dela e obedecendo às suas ordens. Uma vez por descanso longo.'],
    ],
  },
  // Clérigo
  {
    cls: 'cleric',
    name: 'Forge Domain',
    pt: 'Domínio da Forja',
    desc: 'Clerics of smith gods who craft blessed arms and armor and shrug off flame.',
    ptDesc: 'Clérigos de deuses ferreiros que forjam armas e armaduras abençoadas e resistem ao fogo.',
    features: [
      [[1, 3, 5, 7, 9], 'Domain Spells', 'Magias de Domínio', 'Always prepared: Identify, Searing Smite (1st); Heat Metal, Magic Weapon (3rd); Elemental Weapon, Protection from Energy (5th); Fabricate, Wall of Fire (7th); Animate Objects, Creation (9th).', 'Sempre preparadas: Identificação, Golpe Abrasador (1º); Esquentar Metal, Arma Mágica (3º); Arma Elemental, Proteção contra Energia (5º); Fabricar, Muralha de Fogo (7º); Animar Objetos, Criação (9º).'],
      [1, 'Bonus Proficiencies', 'Proficiências Adicionais', 'You gain proficiency with heavy armor and smith’s tools.', 'Você ganha proficiência com armaduras pesadas e ferramentas de ferreiro.'],
      [1, 'Blessing of the Forge', 'Bênção da Forja', 'At the end of a long rest, touch a nonmagical weapon or armor: it becomes magical with +1 to AC or to attack and damage rolls until your next long rest.', 'Ao fim de um descanso longo, toque numa arma ou armadura não mágica: ela vira mágica com +1 na CA ou nas jogadas de ataque e dano até o seu próximo descanso longo.'],
      [2, 'Channel Divinity: Artisan’s Blessing', 'Canalizar Divindade: Bênção do Artesão', 'Over a 1-hour ritual, create a nonmagical item of up to 100 gp that contains metal, consuming metal of equal value.', 'Num ritual de 1 hora, crie um item não mágico de até 100 PO que contenha metal, consumindo metal de valor igual.'],
      [6, 'Soul of the Forge', 'Alma da Forja', 'You have resistance to fire damage and +1 AC while wearing heavy armor.', 'Você tem resistência a dano de fogo e +1 na CA usando armadura pesada.'],
      [[8, 14], 'Divine Strike', 'Golpe Divino', 'Once per turn, your weapon hits deal an extra 1d8 fire damage (2d8 at 14th level).', 'Uma vez por turno, seus acertos com arma causam 1d8 de dano de fogo extra (2d8 no nível 14).'],
      [17, 'Saint of Forge and Fire', 'Santo da Forja e do Fogo', 'You are immune to fire damage, and while wearing heavy armor you have resistance to bludgeoning, piercing and slashing damage from nonmagical attacks.', 'Você é imune a dano de fogo e, usando armadura pesada, tem resistência a dano de concussão, perfuração e corte de ataques não mágicos.'],
    ],
  },
  {
    cls: 'cleric',
    name: 'Grave Domain',
    pt: 'Domínio da Sepultura',
    desc: 'Clerics who guard the line between life and death and oppose undeath.',
    ptDesc: 'Clérigos que guardam a fronteira entre a vida e a morte e combatem os mortos-vivos.',
    features: [
      [[1, 3, 5, 7, 9], 'Domain Spells', 'Magias de Domínio', 'Always prepared: Bane, False Life (1st); Gentle Repose, Ray of Enfeeblement (3rd); Revivify, Vampiric Touch (5th); Blight, Death Ward (7th); Antilife Shell, Raise Dead (9th).', 'Sempre preparadas: Perdição, Vitalidade Falsa (1º); Repouso Tranquilo, Raio do Enfraquecimento (3º); Revivificar, Toque Vampírico (5º); Praga, Proteção contra a Morte (7º); Concha Antivida, Reviver os Mortos (9º).'],
      [1, 'Circle of Mortality', 'Círculo da Mortalidade', 'When you heal a creature at 0 hit points, use the maximum of each healing die. You learn Spare the Dying, which you can cast as a bonus action with 30-foot range.', 'Ao curar uma criatura com 0 PV, use o valor máximo de cada dado de cura. Você aprende Poupar os Moribundos, que pode conjurar com ação bônus e alcance de 9 m.'],
      [1, 'Eyes of the Grave', 'Olhos da Sepultura', 'As an action, sense undead within 60 feet that aren’t behind total cover until the end of your next turn. Uses equal to your Wisdom modifier (minimum 1) per long rest.', 'Com uma ação, perceba mortos-vivos a até 18 m que não estejam sob cobertura total até o fim do seu próximo turno. Usos iguais ao modificador de Sabedoria (mínimo 1) por descanso longo.'],
      [2, 'Channel Divinity: Path to the Grave', 'Canalizar Divindade: Caminho para a Sepultura', 'As an action, curse a creature within 30 feet until the end of your next turn: the next attack that hits it has vulnerability to all its damage.', 'Com uma ação, amaldiçoe uma criatura a até 9 m até o fim do seu próximo turno: o próximo ataque que a atingir tem vulnerabilidade a todo o dano.'],
      [6, 'Sentinel at Death’s Door', 'Sentinela no Limiar da Morte', 'As a reaction, turn a critical hit against you or a creature within 30 feet into a normal hit. Uses equal to your Wisdom modifier (minimum 1) per long rest.', 'Com a reação, transforme um acerto crítico contra você ou uma criatura a até 9 m num acerto normal. Usos iguais ao modificador de Sabedoria (mínimo 1) por descanso longo.'],
      [8, 'Potent Spellcasting', 'Conjuração Potente', 'Add your Wisdom modifier to the damage of your cleric cantrips.', 'Some o modificador de Sabedoria ao dano dos seus truques de clérigo.'],
      [17, 'Keeper of Souls', 'Guardião das Almas', 'Once per round, when an enemy you can see dies within 60 feet, you or an ally within 60 feet regains hit points equal to the enemy’s number of Hit Dice.', 'Uma vez por rodada, quando um inimigo que você vê morre a até 18 m, você ou um aliado a até 18 m recupera PV iguais ao número de Dados de Vida do inimigo.'],
    ],
  },
  // Druida
  {
    cls: 'druid',
    name: 'Circle of Dreams',
    pt: 'Círculo dos Sonhos',
    desc: 'Druids tied to the Feywild who heal, protect and travel through dreamlike magic.',
    ptDesc: 'Druidas ligados à Agrestia das Fadas que curam, protegem e viajam com magia onírica.',
    features: [
      [2, 'Balm of the Summer Court', 'Bálsamo da Corte de Verão', 'You have a pool of d6s equal to your druid level, refreshed on a long rest. As a bonus action, spend up to half your druid level of these dice on a creature within 120 feet: it regains the rolled hit points and gains 1 temporary hit point per die.', 'Você tem uma reserva de d6 igual ao seu nível de druida, renovada no descanso longo. Com uma ação bônus, gaste até metade do seu nível de druida desses dados numa criatura a até 36 m: ela recupera o total rolado em PV e ganha 1 PV temporário por dado.'],
      [6, 'Hearth of Moonlight and Shadow', 'Lar de Luar e Sombras', 'During a rest, you ward a 30-foot sphere: those inside get +5 to Stealth and Perception checks, and light from fires inside can’t be seen from outside.', 'Durante um descanso, você protege uma esfera de 9 m: quem está dentro ganha +5 em testes de Furtividade e Percepção, e a luz de fogueiras ali dentro não é vista de fora.'],
      [10, 'Hidden Paths', 'Caminhos Ocultos', 'As a bonus action, teleport up to 60 feet to an unoccupied space you can see, or as an action teleport a willing creature you touch up to 30 feet. Uses equal to your Wisdom modifier (minimum 1) per long rest.', 'Com uma ação bônus, teletransporte-se até 18 m para um espaço livre que você vê, ou com uma ação teletransporte até 9 m uma criatura voluntária que você toca. Usos iguais ao modificador de Sabedoria (mínimo 1) por descanso longo.'],
      [14, 'Walker in Dreams', 'Andarilho dos Sonhos', 'After a short rest, you can cast Dream, Scrying or Teleportation Circle without a slot, the circle leading to where you last took a long rest. Once per long rest.', 'Depois de um descanso curto, você pode conjurar Sonho, Vidência ou Círculo de Teletransporte sem espaço, com o círculo levando ao lugar do seu último descanso longo. Uma vez por descanso longo.'],
    ],
  },
  {
    cls: 'druid',
    name: 'Circle of the Shepherd',
    pt: 'Círculo do Pastor',
    desc: 'Druids who commune with nature spirits and protect the beasts and fey under their care.',
    ptDesc: 'Druidas que comungam com espíritos da natureza e protegem as feras e as fadas sob seu cuidado.',
    features: [
      [2, 'Speech of the Woods', 'Fala da Floresta', 'You learn Sylvan, and beasts can understand your speech and you can understand theirs, as if under Speak with Animals.', 'Você aprende silvestre, e as feras entendem você e você as entende, como sob Falar com Animais.'],
      [2, 'Spirit Totem', 'Totem Espiritual', 'As a bonus action, summon a spirit aura (30-foot radius) for 1 minute, once per short or long rest. Bear: allies gain temporary hit points (5 + druid level) and advantage on Strength checks and saves. Hawk: as a reaction, grant advantage on an attack against a target in the aura; allies have advantage on Perception. Unicorn: allies have advantage to detect creatures in the aura, and when you cast a healing spell, each creature of your choice in the aura regains your druid level in hit points.', 'Com uma ação bônus, invoque uma aura espiritual (raio de 9 m) por 1 minuto, uma vez por descanso curto ou longo. Urso: aliados ganham PV temporários (5 + nível de druida) e vantagem em testes de Força. Falcão: com a reação, dê vantagem num ataque contra um alvo na aura; aliados têm vantagem em Percepção. Unicórnio: aliados têm vantagem para detectar criaturas na aura e, ao conjurar uma magia de cura, cada criatura à sua escolha na aura recupera PV iguais ao seu nível de druida.'],
      [6, 'Mighty Summoner', 'Invocador Poderoso', 'Beasts and fey you summon with spells have 2 extra hit points per Hit Die and their natural weapons count as magical.', 'Feras e fadas que você invoca com magias ganham 2 PV extras por Dado de Vida, e as armas naturais delas contam como mágicas.'],
      [10, 'Guardian Spirit', 'Espírito Guardião', 'Beasts and fey you summoned that end their turn in your Spirit Totem aura regain hit points equal to half your druid level.', 'Feras e fadas que você invocou e que terminam o turno na aura do Totem Espiritual recuperam PV iguais à metade do seu nível de druida.'],
      [14, 'Faithful Summons', 'Invocações Fiéis', 'When you are reduced to 0 hit points or incapacitated against your will, you can gain the benefits of Conjure Animals as a 9th-level spell, summoning four beasts of CR 2 or lower for 1 hour (no concentration). Once per long rest.', 'Quando você cai a 0 PV ou fica incapacitado contra a vontade, ganha os efeitos de Conjurar Animais no 9º círculo, invocando quatro feras de ND 2 ou menor por 1 hora (sem concentração). Uma vez por descanso longo.'],
    ],
  },
  // Guerreiro
  {
    cls: 'fighter',
    name: 'Arcane Archer',
    pt: 'Arqueiro Arcano',
    desc: 'Elven-trained archers who weave magic into their arrows.',
    ptDesc: 'Arqueiros treinados pelos elfos que tecem magia nas flechas.',
    features: [
      [3, 'Arcane Archer Lore', 'Saber do Arqueiro Arcano', 'You gain proficiency in Arcana or Nature, and learn the Prestidigitation or Druidcraft cantrip.', 'Você ganha proficiência em Arcanismo ou Natureza e aprende o truque Prestidigitação ou Arte Druídica.'],
      [[3, 7, 10, 15, 18], 'Arcane Shot', 'Disparo Arcano', 'You learn two Arcane Shot options (more at 7th, 10th, 15th and 18th; options: Banishing, Beguiling, Bursting, Enfeebling, Grasping, Piercing, Seeking, Shadow). Once per turn when you hit with a magic arrow from a shortbow or longbow, you can apply one. You have two uses per short or long rest. The save DC is 8 + proficiency + Intelligence. Effects improve at 18th level.', 'Você aprende duas opções de Disparo Arcano (mais nos níveis 7, 10, 15 e 18; opções: Banimento, Sedução, Explosão, Enfraquecimento, Agarrão, Perfuração, Busca e Sombra). Uma vez por turno, ao acertar com uma flecha de arco curto ou longo, você aplica uma. Tem dois usos por descanso curto ou longo. CD = 8 + proficiência + Inteligência. Os efeitos melhoram no nível 18.'],
      [7, 'Magic Arrow', 'Flecha Mágica', 'Nonmagical arrows you fire become magical for overcoming resistances.', 'Flechas não mágicas que você dispara se tornam mágicas para superar resistências.'],
      [7, 'Curving Shot', 'Disparo Curvo', 'When you miss with a magic arrow, you can use a bonus action to reroll the attack against a different target within 60 feet of the original.', 'Ao errar com uma flecha mágica, você pode usar uma ação bônus para rolar de novo o ataque contra outro alvo a até 18 m do original.'],
      [15, 'Ever-Ready Shot', 'Disparo Sempre Pronto', 'If you roll initiative with no Arcane Shot uses left, you regain one.', 'Se rolar iniciativa sem usos de Disparo Arcano, você recupera um.'],
    ],
  },
  {
    cls: 'fighter',
    name: 'Cavalier',
    pt: 'Cavaleiro',
    desc: 'Mounted warriors who protect allies and lock down foes.',
    ptDesc: 'Guerreiros montados que protegem aliados e prendem os inimigos.',
    features: [
      [3, 'Bonus Proficiency', 'Proficiência Adicional', 'You gain proficiency in Animal Handling, History, Insight, Performance or Persuasion, or learn one language.', 'Você ganha proficiência em Adestrar Animais, História, Intuição, Atuação ou Persuasão, ou aprende um idioma.'],
      [3, 'Born to the Saddle', 'Nascido na Sela', 'You have advantage on saves to avoid falling off your mount, land on your feet when you fall less than 10 feet from it, and mounting or dismounting costs only 5 feet of movement.', 'Você tem vantagem em testes para não cair da montaria, cai de pé de quedas de menos de 3 m dela, e montar ou desmontar custa só 1,5 m de deslocamento.'],
      [3, 'Unwavering Mark', 'Marca Inabalável', 'When you hit a creature with a melee weapon, you mark it until the end of your next turn: it has disadvantage on attacks against anyone but you, and if it damages someone else you can make a bonus-action melee attack with advantage against it, adding half your fighter level to damage. Bonus attacks equal your Strength modifier (minimum 1) per long rest.', 'Ao acertar uma criatura com arma corpo a corpo, você a marca até o fim do seu próximo turno: ela tem desvantagem em ataques contra quem não for você e, se ferir outra criatura, você pode fazer um ataque corpo a corpo com ação bônus e vantagem contra ela, somando metade do seu nível de guerreiro ao dano. Ataques bônus iguais ao modificador de Força (mínimo 1) por descanso longo.'],
      [7, 'Warding Maneuver', 'Manobra Protetora', 'When a creature within 5 feet of you is hit, you can use your reaction to add 1d8 to its AC; if it is still hit, it has resistance to the damage. Uses equal to your Constitution modifier (minimum 1) per long rest.', 'Quando uma criatura a 1,5 m de você é atingida, use a reação para somar 1d8 à CA dela; se ainda for atingida, ela tem resistência ao dano. Usos iguais ao modificador de Constituição (mínimo 1) por descanso longo.'],
      [10, 'Hold the Line', 'Segurar a Linha', 'Creatures provoke an opportunity attack from you when they move 5 feet or more within your reach, and a hit reduces their speed to 0 for the turn.', 'Criaturas provocam ataque de oportunidade seu ao se moverem 1,5 m ou mais dentro do seu alcance, e o acerto reduz o deslocamento delas a 0 no turno.'],
      [15, 'Ferocious Charger', 'Investida Feroz', 'Once per turn, if you move at least 10 feet in a straight line and then hit, the target makes a Strength save or is knocked prone.', 'Uma vez por turno, se você se mover pelo menos 3 m em linha reta e depois acertar, o alvo faz um teste de Força ou cai.'],
      [18, 'Vigilant Defender', 'Defensor Vigilante', 'You get a special reaction for opportunity attacks on every other creature’s turn.', 'Você tem uma reação especial para ataques de oportunidade no turno de cada outra criatura.'],
    ],
  },
  {
    cls: 'fighter',
    name: 'Samurai',
    pt: 'Samurai',
    desc: 'Disciplined warriors whose fighting spirit drives them forward.',
    ptDesc: 'Guerreiros disciplinados cujo espírito de luta os impulsiona.',
    features: [
      [3, 'Bonus Proficiency', 'Proficiência Adicional', 'You gain proficiency in History, Insight, Performance or Persuasion, or learn one language.', 'Você ganha proficiência em História, Intuição, Atuação ou Persuasão, ou aprende um idioma.'],
      [[3, 10, 15], 'Fighting Spirit', 'Espírito de Luta', 'As a bonus action, gain advantage on weapon attacks until the end of the turn and 5 temporary hit points (10 at 10th level, 15 at 15th). Three uses per long rest.', 'Com uma ação bônus, ganhe vantagem em ataques com arma até o fim do turno e 5 PV temporários (10 no nível 10, 15 no 15). Três usos por descanso longo.'],
      [7, 'Elegant Courtier', 'Cortesão Elegante', 'Add your Wisdom modifier to Charisma (Persuasion) checks, and gain proficiency in Wisdom saves (or Intelligence or Charisma if you already have it).', 'Some o modificador de Sabedoria a testes de Carisma (Persuasão) e ganhe proficiência em testes de resistência de Sabedoria (ou Inteligência ou Carisma, se já tiver).'],
      [10, 'Tireless Spirit', 'Espírito Incansável', 'If you roll initiative with no Fighting Spirit uses left, you regain one.', 'Se rolar iniciativa sem usos de Espírito de Luta, você recupera um.'],
      [15, 'Rapid Strike', 'Golpe Rápido', 'Once per turn, when you have advantage on an attack, you can give it up to make an extra weapon attack as part of the Attack action.', 'Uma vez por turno, quando tiver vantagem num ataque, você pode abrir mão dela para fazer um ataque com arma extra como parte da ação Atacar.'],
      [18, 'Strength Before Death', 'Força Antes da Morte', 'When damage drops you to 0 hit points without killing you, you can use your reaction to take an extra turn immediately; you fall unconscious afterwards if still at 0. Once per long rest.', 'Quando um dano reduz você a 0 PV sem matar, você pode usar a reação para ter um turno extra na hora; depois cai inconsciente se continuar com 0 PV. Uma vez por descanso longo.'],
    ],
  },
  // Monge
  {
    cls: 'monk',
    name: 'Way of the Drunken Master',
    pt: 'Caminho do Mestre Bêbado',
    desc: 'Monks who fight with the unpredictable sway of a drunkard.',
    ptDesc: 'Monges que lutam com o balanço imprevisível de um bêbado.',
    features: [
      [3, 'Bonus Proficiencies', 'Proficiências Adicionais', 'You gain proficiency in Performance and with brewer’s supplies.', 'Você ganha proficiência em Atuação e com suprimentos de cervejeiro.'],
      [3, 'Drunken Technique', 'Técnica do Bêbado', 'When you use Flurry of Blows, you also gain the Disengage benefit and +10 feet of walking speed until the end of the turn.', 'Ao usar Rajada de Golpes, você também ganha o efeito de Desengajar e +3 m de deslocamento até o fim do turno.'],
      [6, 'Tipsy Sway', 'Balanço Embriagado', 'Standing up from prone costs only 5 feet. When a creature misses you with a melee attack, you can spend 1 ki point and your reaction to make it hit another creature within 5 feet of you instead.', 'Levantar-se do chão custa só 1,5 m. Quando uma criatura erra você com um ataque corpo a corpo, você pode gastar 1 ki e a reação para fazê-la acertar outra criatura a 1,5 m de você.'],
      [11, 'Drunkard’s Luck', 'Sorte do Bêbado', 'When you make an ability check, attack roll or save with disadvantage, you can spend 2 ki points to cancel the disadvantage.', 'Ao fazer um teste de atributo, ataque ou teste de resistência com desvantagem, você pode gastar 2 ki para anular a desvantagem.'],
      [17, 'Intoxicated Frenzy', 'Frenesi Embriagado', 'When you use Flurry of Blows, you can make up to three extra attacks, each against a different creature.', 'Ao usar Rajada de Golpes, você pode fazer até três ataques extras, cada um contra uma criatura diferente.'],
    ],
  },
  {
    cls: 'monk',
    name: 'Way of the Kensei',
    pt: 'Caminho do Kensei',
    desc: 'Monks who train relentlessly with chosen weapons until they are an extension of the body.',
    ptDesc: 'Monges que treinam sem parar com armas escolhidas até que virem extensão do corpo.',
    features: [
      [[3, 6, 11, 17], 'Path of the Kensei', 'Caminho do Kensei', 'Choose two kensei weapons (one melee, one ranged; more at 6th, 11th and 17th), which count as monk weapons for you. If you hit with an unarmed strike during the Attack action, kensei melee weapons give +2 AC until your next turn. As a bonus action, kensei ranged weapon hits deal an extra 1d4. You also gain proficiency with calligrapher’s or painter’s supplies.', 'Escolha duas armas kensei (uma corpo a corpo e uma à distância; mais nos níveis 6, 11 e 17), que contam como armas de monge para você. Se acertar um ataque desarmado na ação Atacar, a arma kensei corpo a corpo dá +2 na CA até o seu próximo turno. Com uma ação bônus, os acertos com arma kensei à distância causam 1d4 extra. Você também ganha proficiência com suprimentos de calígrafo ou de pintor.'],
      [6, 'One with the Blade', 'Um com a Lâmina', 'Your kensei weapon attacks count as magical. Once per turn when you hit with a kensei weapon, you can spend 1 to 3 ki points to deal 1d4 extra damage per point.', 'Seus ataques com armas kensei contam como mágicos. Uma vez por turno, ao acertar com uma arma kensei, você pode gastar de 1 a 3 ki para causar 1d4 de dano extra por ponto.'],
      [11, 'Sharpen the Blade', 'Afiar a Lâmina', 'As a bonus action, spend up to 3 ki points to give a kensei weapon a bonus to attack and damage equal to the points spent for 1 minute.', 'Com uma ação bônus, gaste até 3 ki para dar a uma arma kensei bônus no ataque e no dano igual aos pontos gastos por 1 minuto.'],
      [17, 'Unerring Accuracy', 'Precisão Infalível', 'Once per turn, if you miss with a monk weapon, you can reroll the attack.', 'Uma vez por turno, se errar com uma arma de monge, você pode rolar o ataque de novo.'],
    ],
  },
  {
    cls: 'monk',
    name: 'Way of the Sun Soul',
    pt: 'Caminho da Alma Solar',
    desc: 'Monks who channel their ki into searing bolts of radiant light.',
    ptDesc: 'Monges que canalizam o ki em raios de luz radiante.',
    features: [
      [3, 'Radiant Sun Bolt', 'Raio do Sol Radiante', 'You gain a ranged spell attack (30 feet) that deals radiant damage equal to your Martial Arts die + Dexterity, and can replace attacks of the Attack action. After using it as an action, you can spend 1 ki point to make two more as a bonus action.', 'Você ganha um ataque mágico à distância (9 m) que causa dano radiante igual ao dado de Artes Marciais + Destreza e pode substituir ataques da ação Atacar. Depois de usá-lo como ação, pode gastar 1 ki para fazer mais dois com a ação bônus.'],
      [6, 'Searing Arc Strike', 'Golpe do Arco Abrasador', 'After the Attack action, you can spend 2 ki points to cast Burning Hands as a bonus action, spending 1 more ki per extra spell level (maximum half your monk level).', 'Depois da ação Atacar, você pode gastar 2 ki para conjurar Mãos Flamejantes com ação bônus, gastando mais 1 ki por círculo extra (no máximo metade do seu nível de monge).'],
      [11, 'Searing Sunburst', 'Explosão Solar Abrasadora', 'As an action, create a 20-foot-radius burst within 150 feet: creatures make a Constitution save or take 2d6 radiant damage. Spend up to 3 ki to add 2d6 per point.', 'Com uma ação, crie uma explosão de 6 m de raio a até 45 m: criaturas fazem um teste de Constituição ou sofrem 2d6 de dano radiante. Gaste até 3 ki para somar 2d6 por ponto.'],
      [17, 'Sun Shield', 'Escudo Solar', 'You can shed bright light (30 feet). While lit, when a creature hits you with a melee attack, you can use your reaction to deal it radiant damage equal to 5 + your Wisdom modifier.', 'Você pode emitir luz plena (9 m). Enquanto brilha, quando uma criatura acerta você corpo a corpo, você pode usar a reação para causar a ela dano radiante igual a 5 + modificador de Sabedoria.'],
    ],
  },
  // Paladino
  {
    cls: 'paladin',
    name: 'Oath of Conquest',
    pt: 'Juramento da Conquista',
    desc: 'Paladins who seek glory by crushing their enemies and ruling through fear.',
    ptDesc: 'Paladinos que buscam a glória esmagando inimigos e governando pelo medo.',
    features: [
      [[3, 5, 9, 13, 17], 'Oath Spells', 'Magias de Juramento', 'Always prepared: Armor of Agathys, Command (3rd); Hold Person, Spiritual Weapon (5th); Bestow Curse, Fear (9th); Dominate Beast, Stoneskin (13th); Cloudkill, Dominate Person (17th).', 'Sempre preparadas: Armadura de Agathys, Comando (3º); Imobilizar Pessoa, Arma Espiritual (5º); Rogar Maldição, Medo (9º); Dominar Fera, Pele de Pedra (13º); Névoa Mortal, Dominar Pessoa (17º).'],
      [3, 'Channel Divinity', 'Canalizar Divindade', 'Conquering Presence: as an action, creatures of your choice within 30 feet make a Wisdom save or are frightened for 1 minute (save at end of each turn). Guided Strike: when you attack, gain +10 to the roll.', 'Presença Conquistadora: com uma ação, criaturas à sua escolha a até 9 m fazem um teste de Sabedoria ou ficam amedrontadas por 1 minuto (novo teste no fim de cada turno). Golpe Guiado: ao atacar, ganhe +10 na jogada.'],
      [[7, 18], 'Aura of Conquest', 'Aura da Conquista', 'Creatures frightened of you within 10 feet (30 feet at 18th level) have speed 0 and take psychic damage equal to half your paladin level when starting their turn there.', 'Criaturas amedrontadas por você a até 3 m (9 m no nível 18) ficam com deslocamento 0 e sofrem dano psíquico igual à metade do seu nível de paladino ao começarem o turno ali.'],
      [15, 'Scornful Rebuke', 'Repreensão Desdenhosa', 'When a creature hits you, it takes psychic damage equal to your Charisma modifier (minimum 1) if you aren’t incapacitated.', 'Quando uma criatura acerta você, ela sofre dano psíquico igual ao seu modificador de Carisma (mínimo 1), se você não estiver incapacitado.'],
      [20, 'Invincible Conqueror', 'Conquistador Invencível', 'As an action, for 1 minute: resistance to all damage, one extra attack when you take the Attack action, and your melee hits crit on 19–20. Once per long rest.', 'Com uma ação, por 1 minuto: resistência a todo dano, um ataque extra ao usar a ação Atacar e seus acertos corpo a corpo são críticos com 19–20. Uma vez por descanso longo.'],
    ],
  },
  {
    cls: 'paladin',
    name: 'Oath of Redemption',
    pt: 'Juramento da Redenção',
    desc: 'Paladins who seek peace and redemption first, using violence only as a last resort.',
    ptDesc: 'Paladinos que buscam a paz e a redenção primeiro e usam a violência só em último caso.',
    features: [
      [[3, 5, 9, 13, 17], 'Oath Spells', 'Magias de Juramento', 'Always prepared: Sanctuary, Sleep (3rd); Calm Emotions, Hold Person (5th); Counterspell, Hypnotic Pattern (9th); Otiluke’s Resilient Sphere, Stoneskin (13th); Hold Monster, Wall of Force (17th).', 'Sempre preparadas: Santuário, Sono (3º); Acalmar Emoções, Imobilizar Pessoa (5º); Contramágica, Padrão Hipnótico (9º); Esfera Resiliente de Otiluke, Pele de Pedra (13º); Imobilizar Monstro, Muralha de Energia (17º).'],
      [3, 'Channel Divinity', 'Canalizar Divindade', 'Emissary of Peace: as a bonus action, gain +5 to Charisma (Persuasion) checks for 10 minutes. Rebuke the Violent: when a creature within 30 feet damages someone other than you, use your reaction to force a Wisdom save; it takes radiant damage equal to what it dealt (half on success).', 'Emissário da Paz: com uma ação bônus, ganhe +5 em testes de Carisma (Persuasão) por 10 minutos. Repreender o Violento: quando uma criatura a até 9 m fere alguém que não seja você, use a reação para obrigá-la a um teste de Sabedoria; ela sofre dano radiante igual ao que causou (metade se passar).'],
      [[7, 18], 'Aura of the Guardian', 'Aura do Guardião', 'When a creature within 10 feet (30 feet at 18th level) takes damage, you can use your reaction to take that damage instead.', 'Quando uma criatura a até 3 m (9 m no nível 18) sofre dano, você pode usar a reação para sofrer o dano no lugar dela.'],
      [15, 'Protective Spirit', 'Espírito Protetor', 'At the end of your turn, if you are below half your hit points and not incapacitated, regain 1d6 + half your paladin level hit points.', 'No fim do seu turno, se estiver com menos da metade dos PV e não estiver incapacitado, recupere 1d6 + metade do seu nível de paladino em PV.'],
      [20, 'Emissary of Redemption', 'Emissário da Redenção', 'You have resistance to all damage dealt by other creatures, and an attacker that damages you takes radiant damage equal to half of what it dealt. The benefit ends against a creature you attack or affect with a spell until you finish a long rest.', 'Você tem resistência a todo dano causado por outras criaturas, e quem ferir você sofre dano radiante igual à metade do que causou. O efeito some contra uma criatura que você atacar ou afetar com magia até terminar um descanso longo.'],
    ],
  },
  // Patrulheiro
  {
    cls: 'ranger',
    name: 'Gloom Stalker',
    pt: 'Espreitador Sombrio',
    desc: 'Rangers who hunt in the dark places of the world, striking from shadow.',
    ptDesc: 'Patrulheiros que caçam nos lugares escuros do mundo e atacam das sombras.',
    features: [
      [[3, 5, 9, 13, 17], 'Gloom Stalker Magic', 'Magia do Espreitador Sombrio', 'You learn extra spells that don’t count against your known spells: Disguise Self (3rd), Rope Trick (5th), Fear (9th), Greater Invisibility (13th), Seeming (17th).', 'Você aprende magias extras que não contam no limite: Disfarçar-se (3º), Truque da Corda (5º), Medo (9º), Invisibilidade Maior (13º), Aparência (17º).'],
      [3, 'Dread Ambusher', 'Emboscador Temível', 'Add your Wisdom modifier to initiative. On your first turn of combat, your speed increases by 10 feet and, if you take the Attack action, you make one extra weapon attack that deals an extra 1d8 damage on a hit.', 'Some o modificador de Sabedoria à iniciativa. No seu primeiro turno de combate, seu deslocamento aumenta em 3 m e, se usar a ação Atacar, você faz um ataque extra com arma que causa 1d8 de dano adicional se acertar.'],
      [3, 'Umbral Sight', 'Visão Umbral', 'You gain darkvision 60 feet (or +30 feet if you already have it), and you are invisible to creatures relying on darkvision to see you in darkness.', 'Você ganha visão no escuro de 18 m (ou +9 m se já tiver) e fica invisível para criaturas que dependem de visão no escuro para ver você na escuridão.'],
      [7, 'Iron Mind', 'Mente de Ferro', 'You gain proficiency in Wisdom saves (or Intelligence or Charisma if you already have it).', 'Você ganha proficiência em testes de resistência de Sabedoria (ou Inteligência ou Carisma, se já tiver).'],
      [11, 'Stalker’s Flurry', 'Rajada do Espreitador', 'Once per turn when you miss with a weapon attack, you can make another weapon attack as part of the same action.', 'Uma vez por turno, ao errar um ataque com arma, você pode fazer outro ataque com arma na mesma ação.'],
      [15, 'Shadowy Dodge', 'Esquiva Sombria', 'When a creature attacks you without advantage, you can use your reaction to impose disadvantage on the roll.', 'Quando uma criatura ataca você sem vantagem, você pode usar a reação para impor desvantagem na jogada.'],
    ],
  },
  {
    cls: 'ranger',
    name: 'Horizon Walker',
    pt: 'Andarilho do Horizonte',
    desc: 'Rangers who guard the world against threats from other planes.',
    ptDesc: 'Patrulheiros que protegem o mundo de ameaças de outros planos.',
    features: [
      [[3, 5, 9, 13, 17], 'Horizon Walker Magic', 'Magia do Andarilho do Horizonte', 'You learn extra spells: Protection from Evil and Good (3rd), Misty Step (5th), Haste (9th), Banishment (13th), Teleportation Circle (17th).', 'Você aprende magias extras: Proteção contra o Bem e o Mal (3º), Passo Nebuloso (5º), Velocidade (9º), Banimento (13º), Círculo de Teletransporte (17º).'],
      [3, 'Detect Portal', 'Detectar Portal', 'As an action, sense the distance and direction to the nearest planar portal within 1 mile. Once per short or long rest.', 'Com uma ação, perceba a distância e a direção do portal planar mais próximo a até 1,5 km. Uma vez por descanso curto ou longo.'],
      [[3, 11], 'Planar Warrior', 'Guerreiro Planar', 'As a bonus action, choose a creature within 30 feet: your next hit against it this turn deals force damage and an extra 1d8 (2d8 at 11th level).', 'Com uma ação bônus, escolha uma criatura a até 9 m: seu próximo acerto contra ela neste turno causa dano de energia e mais 1d8 (2d8 no nível 11).'],
      [7, 'Ethereal Step', 'Passo Etéreo', 'As a bonus action, cast Etherealness without a slot; it ends at the end of the turn. Once per short or long rest.', 'Com uma ação bônus, conjure Forma Etérea sem espaço; o efeito acaba no fim do turno. Uma vez por descanso curto ou longo.'],
      [11, 'Distant Strike', 'Golpe Distante', 'When you take the Attack action, you can teleport up to 10 feet before each attack. If you attack at least two different creatures, you can make one more attack against a third.', 'Ao usar a ação Atacar, você pode se teletransportar até 3 m antes de cada ataque. Se atacar pelo menos duas criaturas diferentes, pode fazer mais um ataque contra uma terceira.'],
      [15, 'Spectral Defense', 'Defesa Espectral', 'When you take damage from an attack, you can use your reaction to gain resistance to it.', 'Ao sofrer dano de um ataque, você pode usar a reação para ter resistência a ele.'],
    ],
  },
  {
    cls: 'ranger',
    name: 'Monster Slayer',
    pt: 'Matador de Monstros',
    desc: 'Rangers who hunt vampires, dragons and other supernatural threats.',
    ptDesc: 'Patrulheiros que caçam vampiros, dragões e outras ameaças sobrenaturais.',
    features: [
      [[3, 5, 9, 13, 17], 'Monster Slayer Magic', 'Magia do Matador de Monstros', 'You learn extra spells: Protection from Evil and Good (3rd), Zone of Truth (5th), Magic Circle (9th), Banishment (13th), Hold Monster (17th).', 'Você aprende magias extras: Proteção contra o Bem e o Mal (3º), Zona da Verdade (5º), Círculo Mágico (9º), Banimento (13º), Imobilizar Monstro (17º).'],
      [3, 'Hunter’s Sense', 'Sentido do Caçador', 'As an action, learn the immunities, resistances and vulnerabilities of a creature within 60 feet. Uses equal to your Wisdom modifier (minimum 1) per long rest.', 'Com uma ação, descubra as imunidades, resistências e vulnerabilidades de uma criatura a até 18 m. Usos iguais ao modificador de Sabedoria (mínimo 1) por descanso longo.'],
      [3, 'Slayer’s Prey', 'Presa do Matador', 'As a bonus action, designate a creature within 60 feet as your prey: the first time each turn you hit it, it takes an extra 1d6 damage. Lasts until a short or long rest or until you choose another.', 'Com uma ação bônus, marque uma criatura a até 18 m como presa: na primeira vez em cada turno que você a acerta, ela sofre 1d6 de dano extra. Dura até um descanso curto ou longo ou até você escolher outra.'],
      [7, 'Supernatural Defense', 'Defesa Sobrenatural', 'When your prey forces you to make a save or a check to escape its grapple, add 1d6 to the roll.', 'Quando sua presa obriga você a um teste de resistência ou a um teste para escapar do agarrão dela, some 1d6.'],
      [11, 'Magic-User’s Nemesis', 'Nêmesis dos Conjuradores', 'When a creature within 60 feet casts a spell or teleports, use your reaction to force a Wisdom save; on a failure, the spell or teleport fails and is wasted. Once per short or long rest.', 'Quando uma criatura a até 18 m conjura uma magia ou se teletransporta, use a reação para obrigá-la a um teste de Sabedoria; se falhar, a magia ou o teletransporte falha e é desperdiçado. Uma vez por descanso curto ou longo.'],
      [15, 'Slayer’s Counter', 'Contra-ataque do Matador', 'When your prey forces you to make a save, you can use your reaction to attack it; if you hit, you automatically succeed on the save.', 'Quando sua presa obriga você a um teste de resistência, você pode usar a reação para atacá-la; se acertar, passa automaticamente no teste.'],
    ],
  },
  // Ladino
  {
    cls: 'rogue',
    name: 'Inquisitive',
    pt: 'Inquisitivo',
    desc: 'Rogues who root out secrets and read people like books.',
    ptDesc: 'Ladinos que descobrem segredos e leem as pessoas como livros.',
    features: [
      [3, 'Ear for Deceit', 'Ouvido para Mentiras', 'When you make an Insight check to tell if someone is lying, treat a d20 roll of 7 or lower as an 8.', 'Ao fazer um teste de Intuição para saber se alguém mente, trate um resultado de 7 ou menos no d20 como 8.'],
      [3, 'Eye for Detail', 'Olho para Detalhes', 'You can use a bonus action to make a Perception check to spot a hidden creature or object, or an Investigation check to uncover clues.', 'Você pode usar uma ação bônus para fazer um teste de Percepção para notar uma criatura ou objeto escondido, ou de Investigação para achar pistas.'],
      [3, 'Insightful Fighting', 'Luta Perspicaz', 'As a bonus action, make an Insight check against a creature’s Deception: on a success, you can use Sneak Attack against it without advantage (but not with disadvantage) for 1 minute.', 'Com uma ação bônus, faça um teste de Intuição contra a Enganação de uma criatura: se vencer, pode usar Ataque Furtivo contra ela sem vantagem (mas não com desvantagem) por 1 minuto.'],
      [9, 'Steady Eye', 'Olhar Firme', 'If you move no more than half your speed on a turn, you have advantage on Perception and Investigation checks that turn.', 'Se você se mover no máximo metade do deslocamento num turno, tem vantagem em testes de Percepção e Investigação nesse turno.'],
      [13, 'Unerring Eye', 'Olho Infalível', 'As an action, sense illusions, shapechangers and other magical deceptions within 30 feet. Uses equal to your Wisdom modifier (minimum 1) per long rest.', 'Com uma ação, perceba ilusões, metamorfos e outros enganos mágicos a até 9 m. Usos iguais ao modificador de Sabedoria (mínimo 1) por descanso longo.'],
      [17, 'Eye for Weakness', 'Olho para Fraquezas', 'While Insightful Fighting applies to a creature, your Sneak Attack against it deals an extra 3d6.', 'Enquanto a Luta Perspicaz vale contra uma criatura, seu Ataque Furtivo contra ela causa 3d6 extras.'],
    ],
  },
  {
    cls: 'rogue',
    name: 'Mastermind',
    pt: 'Mentor',
    desc: 'Rogues who manipulate people and events, steering allies from behind the scenes.',
    ptDesc: 'Ladinos que manipulam pessoas e eventos, guiando aliados dos bastidores.',
    features: [
      [3, 'Master of Intrigue', 'Mestre da Intriga', 'You gain proficiency with the disguise kit, forgery kit and one gaming set, learn two languages, and can mimic speech patterns and accents after hearing them for 1 minute.', 'Você ganha proficiência com kit de disfarce, kit de falsificação e um jogo, aprende dois idiomas e pode imitar sotaques e jeitos de falar depois de ouvi-los por 1 minuto.'],
      [3, 'Master of Tactics', 'Mestre das Táticas', 'You can use the Help action as a bonus action, and help an ally attack a creature within 30 feet of you.', 'Você pode usar a ação Ajudar como ação bônus e ajudar um aliado a atacar uma criatura a até 9 m de você.'],
      [9, 'Insightful Manipulator', 'Manipulador Perspicaz', 'After observing a creature outside combat for 1 minute, learn whether it is equal, superior or inferior to you in two of: Intelligence, Wisdom, Charisma or class levels.', 'Depois de observar uma criatura fora de combate por 1 minuto, descubra se ela é igual, superior ou inferior a você em duas destas: Inteligência, Sabedoria, Carisma ou níveis de classe.'],
      [13, 'Misdirection', 'Despistar', 'When a creature targets you with an attack while a creature is within 5 feet of you giving you cover, you can use your reaction to redirect the attack to that creature.', 'Quando uma criatura ataca você enquanto outra a 1,5 m lhe dá cobertura, você pode usar a reação para redirecionar o ataque para essa outra criatura.'],
      [17, 'Soul of Deceit', 'Alma da Enganação', 'Your thoughts can’t be read by telepathy unless you allow it, you can present false thoughts, and magic that would determine whether you are lying always reports you are truthful.', 'Seus pensamentos não podem ser lidos por telepatia sem permissão, você pode mostrar pensamentos falsos, e magias que verificariam se você mente sempre dizem que fala a verdade.'],
    ],
  },
  {
    cls: 'rogue',
    name: 'Scout',
    pt: 'Batedor',
    desc: 'Rogues skilled in stealth and survival who range ahead of their allies.',
    ptDesc: 'Ladinos hábeis em furtividade e sobrevivência que avançam à frente dos aliados.',
    features: [
      [3, 'Skirmisher', 'Escaramuçador', 'When an enemy ends its turn within 5 feet of you, you can use your reaction to move up to half your speed without provoking opportunity attacks.', 'Quando um inimigo termina o turno a 1,5 m de você, você pode usar a reação para se mover até metade do deslocamento sem provocar ataques de oportunidade.'],
      [3, 'Survivalist', 'Sobrevivente', 'You gain proficiency in Nature and Survival, and double your proficiency bonus for checks with them.', 'Você ganha proficiência em Natureza e Sobrevivência e dobra o bônus de proficiência nos testes com elas.'],
      [9, 'Superior Mobility', 'Mobilidade Superior', 'Your walking speed (and climbing and swimming speeds, if any) increases by 10 feet.', 'Seu deslocamento (e os de escalada e natação, se tiver) aumenta em 3 m.'],
      [13, 'Ambush Master', 'Mestre da Emboscada', 'You have advantage on initiative. The first creature you hit in the first round of combat becomes easier to hit: attacks against it have advantage until the start of your next turn.', 'Você tem vantagem na iniciativa. A primeira criatura que você acerta na primeira rodada de combate fica exposta: ataques contra ela têm vantagem até o início do seu próximo turno.'],
      [17, 'Sudden Strike', 'Golpe Súbito', 'If you take the Attack action, you can make one additional attack as a bonus action; it can benefit from Sneak Attack even if you already used it this turn, but not against the same target.', 'Se usar a ação Atacar, você pode fazer um ataque adicional com ação bônus; ele pode ter Ataque Furtivo mesmo que você já tenha usado neste turno, mas não contra o mesmo alvo.'],
    ],
  },
  {
    cls: 'rogue',
    name: 'Swashbuckler',
    pt: 'Espadachim',
    desc: 'Rogues who fight with speed, elegance and charm.',
    ptDesc: 'Ladinos que lutam com velocidade, elegância e charme.',
    features: [
      [3, 'Fancy Footwork', 'Jogo de Pés', 'When you make a melee attack against a creature on your turn, it can’t make opportunity attacks against you for the rest of the turn.', 'Ao fazer um ataque corpo a corpo contra uma criatura no seu turno, ela não pode fazer ataques de oportunidade contra você pelo resto do turno.'],
      [3, 'Rakish Audacity', 'Audácia Libertina', 'Add your Charisma modifier to initiative. You can use Sneak Attack without advantage if you are within 5 feet of the target, no other creature is within 5 feet of you, and you don’t have disadvantage.', 'Some o modificador de Carisma à iniciativa. Você pode usar Ataque Furtivo sem vantagem se estiver a 1,5 m do alvo, nenhuma outra criatura estiver a 1,5 m de você e você não tiver desvantagem.'],
      [9, 'Panache', 'Panache', 'As an action, make a Persuasion check against a creature’s Insight. If hostile, it has disadvantage on attacks against others and can’t make opportunity attacks against anyone but you for 1 minute. If not hostile, it is charmed for 1 minute.', 'Com uma ação, faça um teste de Persuasão contra a Intuição de uma criatura. Se for hostil, ela tem desvantagem em ataques contra outros e só pode fazer ataques de oportunidade contra você por 1 minuto. Se não for hostil, fica enfeitiçada por 1 minuto.'],
      [13, 'Elegant Maneuver', 'Manobra Elegante', 'As a bonus action, gain advantage on your next Acrobatics or Athletics check this turn.', 'Com uma ação bônus, ganhe vantagem no próximo teste de Acrobacia ou Atletismo neste turno.'],
      [17, 'Master Duelist', 'Duelista Mestre', 'When you miss an attack, you can reroll it with advantage. Once per short or long rest.', 'Ao errar um ataque, você pode rolar de novo com vantagem. Uma vez por descanso curto ou longo.'],
    ],
  },
  // Feiticeiro
  {
    cls: 'sorcerer',
    name: 'Divine Soul',
    pt: 'Alma Divina',
    desc: 'Sorcerers whose power comes from a divine spark in their bloodline.',
    ptDesc: 'Feiticeiros cujo poder vem de uma centelha divina na linhagem.',
    features: [
      [1, 'Divine Magic', 'Magia Divina', 'You can learn spells from the cleric list as sorcerer spells. Based on your affinity (good, evil, law, chaos or neutrality), you also learn Cure Wounds, Inflict Wounds, Bless, Bane or Protection from Evil and Good.', 'Você pode aprender magias da lista de clérigo como magias de feiticeiro. Conforme sua afinidade (bem, mal, ordem, caos ou neutralidade), também aprende Curar Ferimentos, Infligir Ferimentos, Bênção, Perdição ou Proteção contra o Bem e o Mal.'],
      [1, 'Favored by the Gods', 'Favorecido pelos Deuses', 'When you fail a save or miss an attack, you can add 2d4 to the roll. Once per short or long rest.', 'Ao falhar num teste de resistência ou errar um ataque, você pode somar 2d4 à jogada. Uma vez por descanso curto ou longo.'],
      [6, 'Empowered Healing', 'Cura Fortalecida', 'When you or an ally within 5 feet rolls dice to heal with a spell, you can spend 1 sorcery point to reroll any number of those dice once.', 'Quando você ou um aliado a 1,5 m rola dados de cura de uma magia, você pode gastar 1 ponto de feitiçaria para rolar de novo qualquer quantidade desses dados uma vez.'],
      [14, 'Otherworldly Wings', 'Asas de Outro Mundo', 'As a bonus action, manifest spectral wings that give you a flying speed of 30 feet until you dismiss them.', 'Com uma ação bônus, manifeste asas espectrais que dão deslocamento de voo de 9 m até você dispensá-las.'],
      [18, 'Unearthly Recovery', 'Recuperação Sobrenatural', 'As a bonus action when below half your hit points, regain half your hit point maximum. Once per long rest.', 'Com uma ação bônus, quando estiver com menos da metade dos PV, recupere metade do seu máximo de PV. Uma vez por descanso longo.'],
    ],
  },
  {
    cls: 'sorcerer',
    name: 'Shadow Magic',
    pt: 'Magia das Sombras',
    desc: 'Sorcerers whose power comes from the Shadowfell.',
    ptDesc: 'Feiticeiros cujo poder vem da Umbra.',
    features: [
      [1, 'Eyes of the Dark', 'Olhos da Escuridão', 'You have darkvision 120 feet. At 3rd level, you learn Darkness and can cast it with 2 sorcery points, seeing through it.', 'Você tem visão no escuro de 36 m. No nível 3, aprende Escuridão e pode conjurá-la com 2 pontos de feitiçaria, enxergando através dela.'],
      [1, 'Strength of the Grave', 'Força da Sepultura', 'When damage (not radiant or a critical hit) drops you to 0 hit points, make a Charisma save (DC 5 + damage taken); on a success you drop to 1 hit point instead. Once per long rest.', 'Quando um dano (que não seja radiante nem crítico) reduz você a 0 PV, faça um teste de Carisma (CD 5 + dano sofrido); se passar, fica com 1 PV. Uma vez por descanso longo.'],
      [6, 'Hound of Ill Omen', 'Cão do Mau Agouro', 'As a bonus action, spend 3 sorcery points to summon a shadowy dire wolf next to a creature within 120 feet. It hunts that target, which has disadvantage on saves against your spells while the hound is adjacent.', 'Com uma ação bônus, gaste 3 pontos de feitiçaria para invocar um lobo atroz sombrio ao lado de uma criatura a até 36 m. Ele caça esse alvo, que tem desvantagem em testes contra suas magias enquanto o cão estiver adjacente.'],
      [14, 'Shadow Walk', 'Caminhar nas Sombras', 'While in dim light or darkness, you can use a bonus action to teleport up to 120 feet to another unoccupied space in dim light or darkness you can see.', 'Em penumbra ou escuridão, você pode usar uma ação bônus para se teletransportar até 36 m para outro espaço livre em penumbra ou escuridão que você veja.'],
      [18, 'Umbral Form', 'Forma Umbral', 'As a bonus action, spend 6 sorcery points to become shadow for 1 minute: resistance to all damage except force and radiant, and you can move through creatures and objects.', 'Com uma ação bônus, gaste 6 pontos de feitiçaria para virar sombra por 1 minuto: resistência a todo dano exceto energia e radiante, e você atravessa criaturas e objetos.'],
    ],
  },
  {
    cls: 'sorcerer',
    name: 'Storm Sorcery',
    pt: 'Feitiçaria da Tempestade',
    desc: 'Sorcerers whose power comes from elemental air and storms.',
    ptDesc: 'Feiticeiros cujo poder vem do ar elemental e das tempestades.',
    features: [
      [1, 'Wind Speaker', 'Voz do Vento', 'You can speak, read and write Primordial.', 'Você fala, lê e escreve primordial.'],
      [1, 'Tempestuous Magic', 'Magia Tempestuosa', 'Before or after casting a spell of 1st level or higher, you can use a bonus action to fly up to 10 feet without provoking opportunity attacks.', 'Antes ou depois de conjurar uma magia de 1º círculo ou maior, você pode usar uma ação bônus para voar até 3 m sem provocar ataques de oportunidade.'],
      [6, 'Heart of the Storm', 'Coração da Tempestade', 'You have resistance to lightning and thunder. When you cast a lightning or thunder spell of 1st level or higher, creatures of your choice within 10 feet take lightning or thunder damage equal to half your sorcerer level.', 'Você tem resistência a dano elétrico e trovejante. Ao conjurar uma magia elétrica ou trovejante de 1º círculo ou maior, criaturas à sua escolha a até 3 m sofrem dano elétrico ou trovejante igual à metade do seu nível de feiticeiro.'],
      [6, 'Storm Guide', 'Guia da Tempestade', 'You can stop rain in a 20-foot sphere around you, or control the direction of the wind within 100 feet.', 'Você pode parar a chuva numa esfera de 6 m ao seu redor ou controlar a direção do vento a até 30 m.'],
      [14, 'Storm’s Fury', 'Fúria da Tempestade', 'When a creature hits you with a melee attack, you can use your reaction to deal lightning damage equal to your sorcerer level; it makes a Strength save or is pushed up to 20 feet away.', 'Quando uma criatura acerta você corpo a corpo, você pode usar a reação para causar dano elétrico igual ao seu nível de feiticeiro; ela faz um teste de Força ou é empurrada até 6 m.'],
      [18, 'Wind Soul', 'Alma do Vento', 'You are immune to lightning and thunder and gain a flying speed of 60 feet. As an action, you can reduce it to 30 feet for 1 hour to give it to up to 3 + Charisma modifier creatures within 30 feet. Once per short or long rest.', 'Você é imune a dano elétrico e trovejante e ganha deslocamento de voo de 18 m. Com uma ação, pode reduzi-lo a 9 m por 1 hora para dar voo de 9 m a até 3 + modificador de Carisma criaturas a até 9 m. Uma vez por descanso curto ou longo.'],
    ],
  },
  // Bruxo
  {
    cls: 'warlock',
    name: 'The Celestial',
    pt: 'O Celestial',
    desc: 'Warlocks bound to a being of the Upper Planes, wielding healing light.',
    ptDesc: 'Bruxos ligados a um ser dos Planos Superiores, com uma luz que cura.',
    features: [
      [[1, 3, 5, 7, 9], 'Expanded Spell List', 'Lista de Magias Expandida', 'Added to your warlock list: Cure Wounds, Guiding Bolt (1st); Flaming Sphere, Lesser Restoration (2nd); Daylight, Revivify (3rd); Guardian of Faith, Wall of Fire (4th); Flame Strike, Greater Restoration (5th).', 'Somadas à sua lista de bruxo: Curar Ferimentos, Raio Guiador (1º); Esfera Flamejante, Restauração Menor (2º); Luz do Dia, Revivificar (3º); Guardião da Fé, Muralha de Fogo (4º); Coluna de Chamas, Restauração Maior (5º).'],
      [1, 'Bonus Cantrips', 'Truques Adicionais', 'You learn the Light and Sacred Flame cantrips.', 'Você aprende os truques Luz e Chama Sagrada.'],
      [1, 'Healing Light', 'Luz Curativa', 'You have a pool of d6s equal to 1 + your warlock level. As a bonus action, spend up to your Charisma modifier (minimum 1) dice to heal a creature within 60 feet. The pool refreshes on a long rest.', 'Você tem uma reserva de d6 igual a 1 + seu nível de bruxo. Com uma ação bônus, gaste até o seu modificador de Carisma (mínimo 1) em dados para curar uma criatura a até 18 m. A reserva volta no descanso longo.'],
      [6, 'Radiant Soul', 'Alma Radiante', 'You have resistance to radiant damage, and your fire or radiant spells deal extra damage to one target equal to your Charisma modifier.', 'Você tem resistência a dano radiante, e suas magias de fogo ou radiantes causam dano extra a um alvo igual ao seu modificador de Carisma.'],
      [10, 'Celestial Resilience', 'Resiliência Celestial', 'When you finish a rest, you gain temporary hit points equal to your warlock level + Charisma modifier, and up to five creatures of your choice gain half your warlock level + Charisma modifier.', 'Ao terminar um descanso, você ganha PV temporários iguais ao nível de bruxo + modificador de Carisma, e até cinco criaturas à sua escolha ganham metade do nível de bruxo + modificador de Carisma.'],
      [14, 'Searing Vengeance', 'Vingança Abrasadora', 'When you or an ally within 30 feet makes a death save, you can make that creature stand up with half its hit points, and enemies within 30 feet of it take 2d8 + Charisma radiant damage and are blinded until the end of the turn. Once per long rest.', 'Quando você ou um aliado a até 9 m faz um teste contra a morte, você pode fazê-lo se levantar com metade dos PV; inimigos a até 9 m dele sofrem 2d8 + Carisma de dano radiante e ficam cegos até o fim do turno. Uma vez por descanso longo.'],
    ],
  },
  {
    cls: 'warlock',
    name: 'The Hexblade',
    pt: 'O Lâmina Maldita',
    desc: 'Warlocks whose patron is a sentient weapon forged in the Shadowfell.',
    ptDesc: 'Bruxos cujo patrono é uma arma consciente forjada na Umbra.',
    features: [
      [[1, 3, 5, 7, 9], 'Expanded Spell List', 'Lista de Magias Expandida', 'Added to your warlock list: Shield, Wrathful Smite (1st); Blur, Branding Smite (2nd); Blink, Elemental Weapon (3rd); Phantasmal Killer, Staggering Smite (4th); Banishing Smite, Cone of Cold (5th).', 'Somadas à sua lista de bruxo: Escudo, Golpe Colérico (1º); Nublar, Golpe Marcante (2º); Piscar, Arma Elemental (3º); Assassino Fantasmagórico, Golpe Atordoante (4º); Golpe Banidor, Cone de Frio (5º).'],
      [1, 'Hexblade’s Curse', 'Maldição da Lâmina Maldita', 'As a bonus action, curse a creature within 30 feet for 1 minute: add your proficiency bonus to damage against it, crit on 19–20, and regain warlock level + Charisma modifier hit points if it dies. Once per short or long rest.', 'Com uma ação bônus, amaldiçoe uma criatura a até 9 m por 1 minuto: some a proficiência ao dano contra ela, critique com 19–20 e recupere nível de bruxo + modificador de Carisma em PV se ela morrer. Uma vez por descanso curto ou longo.'],
      [1, 'Hex Warrior', 'Guerreiro Maldito', 'You gain proficiency with medium armor, shields and martial weapons. You can use Charisma for attack and damage with one weapon you touch after a long rest (or your pact weapon).', 'Você ganha proficiência com armaduras médias, escudos e armas marciais. Pode usar Carisma no ataque e no dano com uma arma que tocar depois de um descanso longo (ou com sua arma do pacto).'],
      [6, 'Accursed Specter', 'Espectro Amaldiçoado', 'When you slay a humanoid, you can raise its spirit as a specter that obeys you until your next long rest, with temporary hit points equal to half your warlock level. Once per long rest.', 'Ao matar um humanoide, você pode erguer o espírito dele como um espectro que obedece você até o próximo descanso longo, com PV temporários iguais à metade do seu nível de bruxo. Uma vez por descanso longo.'],
      [10, 'Armor of Hexes', 'Armadura de Maldições', 'When the target of your Hexblade’s Curse hits you, roll a d6: on a 4 or higher, the attack misses.', 'Quando o alvo da sua Maldição acerta você, role um d6: com 4 ou mais, o ataque erra.'],
      [14, 'Master of Hexes', 'Mestre das Maldições', 'When the cursed creature dies, you can move the curse to another creature within 30 feet (without regaining hit points).', 'Quando a criatura amaldiçoada morre, você pode passar a maldição para outra criatura a até 9 m (sem recuperar PV).'],
    ],
  },
  // Mago
  {
    cls: 'wizard',
    name: 'War Magic',
    pt: 'Magia de Guerra',
    desc: 'Wizards who blend evocation and abjuration for the battlefield.',
    ptDesc: 'Magos que unem evocação e abjuração para o campo de batalha.',
    features: [
      [2, 'Arcane Deflection', 'Deflexão Arcana', 'When hit by an attack or failing a save, you can use your reaction to gain +2 AC against that attack or +4 to that save. Until the end of your next turn you can only cast cantrips.', 'Ao ser atingido ou falhar num teste de resistência, você pode usar a reação para ganhar +2 na CA contra esse ataque ou +4 nesse teste. Até o fim do seu próximo turno, só pode conjurar truques.'],
      [2, 'Tactical Wit', 'Perspicácia Tática', 'Add your Intelligence modifier to initiative.', 'Some o modificador de Inteligência à iniciativa.'],
      [6, 'Power Surge', 'Surto de Poder', 'You store power surges (start each long rest with one; regain one when you end a spell with Dispel Magic or Counterspell; max = Intelligence modifier). Once per turn, spend one to add half your wizard level as force damage to a spell’s damage.', 'Você acumula surtos de poder (começa cada descanso longo com um; ganha um ao encerrar uma magia com Dissipar Magia ou Contramágica; máximo = modificador de Inteligência). Uma vez por turno, gaste um para somar metade do seu nível de mago como dano de energia ao dano de uma magia.'],
      [10, 'Durable Magic', 'Magia Resistente', 'While concentrating on a spell, you have +2 AC and +2 on all saving throws.', 'Enquanto se concentra numa magia, você tem +2 na CA e em todos os testes de resistência.'],
      [14, 'Deflecting Shroud', 'Manto Defletor', 'When you use Arcane Deflection, up to three creatures of your choice within 60 feet take force damage equal to half your wizard level.', 'Ao usar Deflexão Arcana, até três criaturas à sua escolha a até 18 m sofrem dano de energia igual à metade do seu nível de mago.'],
    ],
  },
];

export const xgeSubclasses = specs.map((s) => subclass('xge', s));
