/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/antecedentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Antecedentes
         * @description Lista os antecedentes disponíveis, ordenados por id.
         */
        get: operations["listar_antecedentes_api_v1_antecedentes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/antecedentes/{antecedente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Antecedente
         * @description Retorna um antecedente pelo identificador.
         */
        get: operations["buscar_antecedente_api_v1_antecedentes__antecedente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Classes
         * @description Lista as classes disponíveis, ordenadas por id.
         */
        get: operations["listar_classes_api_v1_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Classe
         * @description Retorna uma classe pelo identificador.
         */
        get: operations["buscar_classe_api_v1_classes__classe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/criaturas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Criaturas
         * @description Lista as criaturas, ordenadas por id.
         */
        get: operations["listar_criaturas_api_v1_criaturas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/criaturas/{criatura_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Criatura
         * @description Retorna uma criatura pelo identificador.
         */
        get: operations["buscar_criatura_api_v1_criaturas__criatura_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/armas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Armas
         * @description Lista as armas, ordenadas por id.
         */
        get: operations["listar_armas_api_v1_equipamentos_armas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/armas/{arma_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Arma
         * @description Retorna uma arma pelo identificador.
         */
        get: operations["buscar_arma_api_v1_equipamentos_armas__arma_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/armaduras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Armaduras
         * @description Lista as armaduras e escudos, ordenados por id.
         */
        get: operations["listar_armaduras_api_v1_equipamentos_armaduras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/armaduras/{armadura_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Armadura
         * @description Retorna uma armadura ou escudo pelo identificador.
         */
        get: operations["buscar_armadura_api_v1_equipamentos_armaduras__armadura_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/ferramentas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Ferramentas
         * @description Lista as ferramentas, ordenadas por id.
         */
        get: operations["listar_ferramentas_api_v1_equipamentos_ferramentas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/ferramentas/{ferramenta_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Ferramenta
         * @description Retorna uma ferramenta pelo identificador.
         */
        get: operations["buscar_ferramenta_api_v1_equipamentos_ferramentas__ferramenta_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/itens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Itens
         * @description Lista os itens de equipamento de aventura, ordenados por id.
         */
        get: operations["listar_itens_api_v1_equipamentos_itens_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/itens/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Item
         * @description Retorna um item de equipamento de aventura pelo identificador.
         */
        get: operations["buscar_item_api_v1_equipamentos_itens__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/propriedades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Propriedades
         * @description Lista as propriedades e as propriedades de maestria das armas, ordenadas por id.
         */
        get: operations["listar_propriedades_api_v1_equipamentos_propriedades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equipamentos/propriedades/{propriedade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Propriedade
         * @description Retorna uma propriedade de arma pelo identificador.
         */
        get: operations["buscar_propriedade_api_v1_equipamentos_propriedades__propriedade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Especies
         * @description Lista as espécies disponíveis, ordenadas por id.
         */
        get: operations["listar_especies_api_v1_especies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/{especie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Especie
         * @description Retorna uma espécie pelo identificador.
         */
        get: operations["buscar_especie_api_v1_especies__especie_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fontes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Fontes
         * @description Lista as fontes, ordenadas por id.
         */
        get: operations["listar_fontes_api_v1_fontes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fontes/{fonte_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Fonte
         * @description Retorna uma fonte pelo identificador.
         */
        get: operations["buscar_fonte_api_v1_fontes__fonte_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/magias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Magias
         * @description Lista as magias, ordenadas por id, opcionalmente de um círculo e/ou da lista de uma classe.
         */
        get: operations["listar_magias_api_v1_magias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/magias/{magia_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Magia
         * @description Retorna uma magia pelo identificador.
         */
        get: operations["buscar_magia_api_v1_magias__magia_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subclasses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Subclasses
         * @description Lista as subclasses disponíveis, ordenadas por id, opcionalmente de uma única classe.
         */
        get: operations["listar_subclasses_api_v1_subclasses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subclasses/{subclasse_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Subclasse
         * @description Retorna uma subclasse pelo identificador.
         */
        get: operations["buscar_subclasse_api_v1_subclasses__subclasse_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/talentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Talentos
         * @description Lista os talentos disponíveis, ordenados por id, opcionalmente de uma única categoria.
         */
        get: operations["listar_talentos_api_v1_talentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/talentos/{talento_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Talento
         * @description Retorna um talento pelo identificador.
         */
        get: operations["buscar_talento_api_v1_talentos__talento_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Antecedente
         * @description Antecedente de personagem, como retornado pela API.
         */
        Antecedente: {
            /**
             * Id
             * @description ID do antecedente
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome do antecedente
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição do antecedente
             */
            descricao: string;
            /**
             * Valores Atributo
             * @description Atributos cujos valores o antecedente permite aumentar
             */
            valores_atributo: string[];
            /**
             * Talento
             * @description Talento concedido, como no livro (ex.: "Artífista (veja o capítulo 5)")
             */
            talento: string;
            /**
             * Proficiencias Pericias
             * @description Perícias em que o antecedente concede proficiência
             */
            proficiencias_pericias: string[];
            /**
             * Proficiencia Ferramentas
             * @description Proficiência com ferramentas, como no livro
             */
            proficiencia_ferramentas: string;
            /**
             * Equipamento
             * @description Opções de equipamento inicial, à escolha
             */
            equipamento: components["schemas"]["OpcaoEquipamento"][];
        };
        /**
         * Arma
         * @description Arma da tabela Armas, como retornada pela API.
         */
        Arma: {
            /**
             * Id
             * @description ID da arma
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da arma
             */
            nome: string;
            /**
             * Categoria
             * @description Categoria da arma, como no livro (ex.: "Simples", "Marcial")
             */
            categoria: string;
            /**
             * Tipo
             * @description Tipo da arma, como no livro (ex.: "Corpo a Corpo", "À Distância")
             */
            tipo: string;
            /**
             * Dano
             * @description Dano e tipo de dano, como no livro (ex.: "1d4 Perfurante")
             */
            dano: string;
            /**
             * Propriedades
             * @description Propriedades da arma, como no livro (ex.: "Arremesso (Alcance 6/18)"); vazia se não houver
             */
            propriedades: string[];
            /**
             * Maestria
             * @description Propriedade de maestria da arma
             */
            maestria: string;
            /**
             * Peso
             * @description Peso, como no livro (ex.: "0,5 kg", "—")
             */
            peso: string;
            /**
             * Custo
             * @description Custo, como no livro (ex.: "2 PO")
             */
            custo: string;
        };
        /**
         * Armadura
         * @description Armadura ou escudo da tabela Armaduras, como retornada pela API.
         */
        Armadura: {
            /**
             * Id
             * @description ID da armadura
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da armadura
             */
            nome: string;
            /**
             * Categoria
             * @description Categoria, como no livro (ex.: "Leve", "Média", "Pesada", "Escudo")
             */
            categoria: string;
            /**
             * Vestir Despir
             * @description Tempo para vestir e despir, como no livro (ex.: "1 Minuto para Vestir ou Despir")
             */
            vestir_despir: string;
            /**
             * Classe Armadura
             * @description Classe de Armadura (CA), como no livro (ex.: "11 + modificador de Des")
             */
            classe_armadura: string;
            /**
             * Forca
             * @description Valor de Força exigido, como no livro (ex.: "For 13"); nulo se não houver
             */
            forca?: string | null;
            /**
             * Furtividade
             * @description Efeito em Furtividade, como no livro (ex.: "Desvantagem"); nulo se não houver
             */
            furtividade?: string | null;
            /**
             * Peso
             * @description Peso, como no livro (ex.: "4 kg")
             */
            peso: string;
            /**
             * Custo
             * @description Custo, como no livro (ex.: "5 PO")
             */
            custo: string;
        };
        /**
         * AtributoCriatura
         * @description Linha da tabela de atributos do bloco de estatísticas.
         */
        AtributoCriatura: {
            /**
             * Atributo
             * @description Abreviação do atributo, como no livro (ex.: "For")
             */
            atributo: string;
            /**
             * Valor
             * @description Valor do atributo
             */
            valor: number;
            /**
             * Modificador
             * @description Modificador (coluna MOD)
             */
            modificador: number;
            /**
             * Salvaguarda
             * @description Modificador de salvaguarda (coluna SG); nulo quando o bloco não tem a coluna (2014)
             */
            salvaguarda?: number | null;
        };
        /**
         * Beneficio
         * @description Benefício nomeado de um talento (ex.: "Proficiência em Iniciativa").
         */
        Beneficio: {
            /**
             * Nome
             * @description Nome do benefício
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição do benefício
             */
            descricao: string;
        };
        /**
         * Capacidade
         * @description Traço, ação, ação bônus, reação ou ação lendária do bloco de estatísticas.
         */
        Capacidade: {
            /**
             * Nome
             * @description Nome, como no livro (ex.: "Teia (Recarga 5–6)")
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição
             */
            descricao: string;
        };
        /**
         * Caracteristica
         * @description Característica de classe ou de subclasse obtida em um nível.
         */
        Caracteristica: {
            /**
             * Nivel
             * @description Nível da classe em que a característica é obtida
             */
            nivel: number;
            /**
             * Nome
             * @description Nome da característica
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição da característica
             */
            descricao: string;
            /**
             * Opcoes
             * @description Opções à escolha dentro da característica; vazia quando não há
             */
            opcoes?: components["schemas"]["OpcaoCaracteristica"][];
        };
        /**
         * Classe
         * @description Classe de personagem, como retornada pela API.
         */
        Classe: {
            /**
             * Id
             * @description ID da classe
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da classe
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição da classe
             */
            descricao: string;
            /**
             * Atributo Primario
             * @description Atributo primário, como no livro (ex.: "Força")
             */
            atributo_primario: string;
            /**
             * Dado Vida
             * @description Dado de Ponto de Vida, como no livro (ex.: "D12 por nível de Bárbaro")
             */
            dado_vida: string;
            /**
             * Proficiencias Salvaguardas
             * @description Atributos em cujas salvaguardas a classe é proficiente
             */
            proficiencias_salvaguardas: string[];
            /**
             * Proficiencias Pericias
             * @description Proficiência em perícias, como no livro (ex.: "Escolha 2: ...")
             */
            proficiencias_pericias: string;
            /**
             * Proficiencias Armas
             * @description Proficiências com armas, como no livro
             */
            proficiencias_armas: string;
            /**
             * Treinamento Armaduras
             * @description Treinamento com armadura, como no livro
             */
            treinamento_armaduras: string;
            /**
             * Equipamento
             * @description Opções de equipamento inicial, à escolha
             */
            equipamento: components["schemas"]["OpcaoEquipamentoClasse"][];
            /**
             * Multiclasse
             * @description O que se adquire ao entrar na classe como personagem multiclasse
             */
            multiclasse: string;
            /**
             * Progressao
             * @description Tabela de características da classe, por nível
             */
            progressao: components["schemas"]["NivelClasse"][];
            /**
             * Caracteristicas
             * @description Características de classe, ordenadas por nível
             */
            caracteristicas: components["schemas"]["Caracteristica"][];
            /**
             * Subclasses
             * @description Subclasses da classe
             */
            subclasses: components["schemas"]["ResumoSubclasse"][];
        };
        /**
         * ColunaProgressao
         * @description Valor de uma coluna específica da classe na tabela de características (ex.: Fúrias).
         */
        ColunaProgressao: {
            /**
             * Nome
             * @description Nome da coluna, como no livro (ex.: "Dano da Fúria")
             */
            nome: string;
            /**
             * Valor
             * @description Valor da coluna no nível, como no livro (ex.: "+2")
             */
            valor: string;
        };
        /**
         * Criatura
         * @description Bloco de estatísticas de uma criatura, como retornado pela API.
         *
         *     Aceita os formatos de 2024 e de 2014: linhas que só existem em um deles são nulas no outro.
         */
        Criatura: {
            /**
             * Id
             * @description ID da criatura
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da criatura
             */
            nome: string;
            /**
             * Tipo
             * @description Tipo e tamanho, como no livro (ex.: "Fera Grande", "Ínfero Minúsculo (Diabo)")
             */
            tipo: string;
            /**
             * Alinhamento
             * @description Alinhamento, como no livro (ex.: "Sem Alinhamento")
             */
            alinhamento: string;
            /**
             * Classe Armadura
             * @description Classe de Armadura (CA), como no livro (ex.: "14 (armadura natural)")
             */
            classe_armadura: string;
            /**
             * Iniciativa
             * @description Iniciativa, como no livro (ex.: "+2 (12)"); nula quando o bloco não tem a linha (2014)
             */
            iniciativa?: string | null;
            /**
             * Pontos Vida
             * @description Pontos de Vida, como no livro (ex.: "26 (4d10 + 4)")
             */
            pontos_vida: string;
            /**
             * Deslocamento
             * @description Deslocamento, como no livro (ex.: "9 m, Escalada 9 m")
             */
            deslocamento: string;
            /**
             * Atributos
             * @description Os seis atributos, na ordem do bloco
             */
            atributos: components["schemas"]["AtributoCriatura"][];
            /**
             * Salvaguardas
             * @description Linha de Salvaguardas, como no livro (ex.: "Des +5, Con +5"); nula se o bloco não tiver
             */
            salvaguardas?: string | null;
            /**
             * Pericias
             * @description Perícias, como no livro; nulo se o bloco não tiver a linha
             */
            pericias?: string | null;
            /**
             * Resistencias
             * @description Resistências a dano; nulo se o bloco não tiver a linha
             */
            resistencias?: string | null;
            /**
             * Vulnerabilidades
             * @description Vulnerabilidades a dano; nulo se o bloco não tiver a linha
             */
            vulnerabilidades?: string | null;
            /**
             * Imunidades Dano
             * @description Imunidades a dano (no formato de 2024, a parte antes do ";"); nulo se não houver
             */
            imunidades_dano?: string | null;
            /**
             * Imunidades Condicao
             * @description Imunidades a condição (no formato de 2024, a parte após o ";"); nulo se não houver
             */
            imunidades_condicao?: string | null;
            /**
             * Equipamento
             * @description Equipamento; nulo se o bloco não tiver a linha
             */
            equipamento?: string | null;
            /**
             * Sentidos
             * @description Sentidos, como no livro (ex.: "Visão no Escuro 18 m, Percepção Passiva 12")
             */
            sentidos: string;
            /**
             * Idiomas
             * @description Idiomas, como no livro ("—" quando não há)
             */
            idiomas: string;
            /**
             * Nivel Desafio
             * @description Nível de Desafio, como no livro (ex.: "1/4 (XP 50; BP +2)", "1/2 (100 XP)")
             */
            nivel_desafio: string;
            /**
             * Bonus Proficiencia
             * @description Bônus de Proficiência quando o bloco o mostra à parte (ex.: "+2"); nulo se vier no ND
             */
            bonus_proficiencia?: string | null;
            /**
             * Tracos
             * @description Traços; vazia quando não há
             */
            tracos?: components["schemas"]["Capacidade"][];
            /**
             * Acoes
             * @description Ações; vazia quando não há
             */
            acoes?: components["schemas"]["Capacidade"][];
            /**
             * Acoes Bonus
             * @description Ações Bônus; vazia quando não há
             */
            acoes_bonus?: components["schemas"]["Capacidade"][];
            /**
             * Reacoes
             * @description Reações; vazia quando não há
             */
            reacoes?: components["schemas"]["Capacidade"][];
            /**
             * Descricao Acoes Lendarias
             * @description Parágrafo de introdução das Ações Lendárias; nulo quando a criatura não as tem
             */
            descricao_acoes_lendarias?: string | null;
            /**
             * Acoes Lendarias
             * @description Ações Lendárias; vazia quando não há
             */
            acoes_lendarias?: components["schemas"]["Capacidade"][];
        };
        /**
         * DetalheValidacao
         * @description Problema encontrado em um parâmetro da requisição.
         */
        DetalheValidacao: {
            /**
             * Campo
             * @description Parâmetro com problema
             */
            campo: string;
            /**
             * Mensagem
             * @description Descrição do problema
             */
            mensagem: string;
        };
        /**
         * Especie
         * @description Espécie jogável, como retornada pela API.
         */
        Especie: {
            /**
             * Id
             * @description ID da espécie
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da espécie
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição da espécie
             */
            descricao: string;
            /**
             * Deslocamento
             * @description Deslocamento da espécie, como no livro (ex.: "9 metros")
             */
            deslocamento: string;
            /**
             * Tamanho
             * @description Tamanho da espécie, como no livro, incluindo as opções de escolha
             */
            tamanho: string;
            /**
             * Habilidades
             * @description Habilidades da espécie
             */
            habilidades: components["schemas"]["Habilidade"][];
        };
        /**
         * Ferramenta
         * @description Ferramenta da seção Ferramentas, como retornada pela API.
         */
        Ferramenta: {
            /**
             * Id
             * @description ID da ferramenta
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da ferramenta
             */
            nome: string;
            /**
             * Categoria
             * @description Seção do livro (ex.: "Ferramentas de Artesão", "Outras Ferramentas")
             */
            categoria: string;
            /**
             * Custo
             * @description Custo, como no livro (ex.: "8 PO", "Varia")
             */
            custo: string;
            /**
             * Atributo
             * @description Atributo usado nos testes com a ferramenta
             */
            atributo: string;
            /**
             * Peso
             * @description Peso, como no livro (ex.: "3 kg", "Varia")
             */
            peso: string;
            /**
             * Usar Objeto
             * @description O que a ação Usar Objeto permite fazer com a ferramenta, com a CD
             */
            usar_objeto: string;
            /**
             * Fabricacao
             * @description Itens que a ferramenta permite fabricar; vazia quando não há
             */
            fabricacao?: string[];
            /**
             * Variantes
             * @description Variantes, como no livro (ex.: "Alaúde (35 PO, 1 kg)"); vazia quando não há
             */
            variantes?: string[];
        };
        /**
         * Fonte
         * @description Livro ou homebrew de onde vêm os dados, como retornado pela API.
         */
        Fonte: {
            /**
             * Id
             * @description ID da fonte
             */
            id: number;
            /**
             * Nome
             * @description Nome da fonte (ex.: "Livro do Jogador (2024)")
             */
            nome: string;
            /**
             * Edicao
             * @description Edição: "5e" (2014), "5.5e" (2024) ou "homebrew"
             */
            edicao: string;
            /**
             * Abreviacao
             * @description Abreviação da fonte (ex.: "LDJ24")
             */
            abreviacao: string;
        };
        /**
         * Habilidade
         * @description Habilidade concedida por uma espécie.
         */
        Habilidade: {
            /**
             * Nome
             * @description Nome da habilidade
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição da habilidade
             */
            descricao: string;
            /**
             * Opcoes
             * @description Opções à escolha dentro da habilidade; vazia quando não há
             */
            opcoes?: components["schemas"]["OpcaoHabilidade"][];
        };
        /**
         * ItemAventura
         * @description Item da tabela Equipamento de Aventura, como retornado pela API.
         */
        ItemAventura: {
            /**
             * Id
             * @description ID do item
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome do item, como no livro (ex.: "Cantil (cheio)")
             */
            nome: string;
            /**
             * Peso
             * @description Peso, como no livro (ex.: "0,5 kg", "—", "Varia")
             */
            peso: string;
            /**
             * Custo
             * @description Custo, como no livro (ex.: "25 PO", "Varia")
             */
            custo: string;
            /**
             * Descricao
             * @description Descrição do item
             */
            descricao: string;
            /**
             * Tabelas
             * @description Tabelas da descrição (ex.: tipos de Munição); vazia quando não há
             */
            tabelas?: components["schemas"]["Tabela"][];
        };
        /**
         * ItemEquipamento
         * @description Item de uma opção de equipamento, com a quantidade separada do nome.
         */
        ItemEquipamento: {
            /**
             * Nome
             * @description Nome do item, como no livro (ex.: "Algibeira")
             */
            nome: string;
            /**
             * Quantidade
             * @description Quantidade do item
             * @default 1
             */
            quantidade: number;
        };
        /**
         * Magia
         * @description Magia, como retornada pela API.
         */
        Magia: {
            /**
             * Id
             * @description ID da magia
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da magia
             */
            nome: string;
            /**
             * Circulo
             * @description Círculo da magia; 0 para truques
             */
            circulo: number;
            /**
             * Escola
             * @description Escola de magia (ex.: "Evocação")
             */
            escola: string;
            /**
             * Classes
             * @description Classes cuja lista de magias inclui a magia
             */
            classes: components["schemas"]["ResumoClasse"][];
            /**
             * Tempo Conjuracao
             * @description Tempo de Conjuração, como no livro (ex.: "1 minuto ou Ritual")
             */
            tempo_conjuracao: string;
            /**
             * Alcance
             * @description Alcance, como no livro (ex.: "18 metros", "Toque")
             */
            alcance: string;
            /**
             * Componentes
             * @description Componentes, como no livro (ex.: "V, S, M (um sino e um fio de prata)")
             */
            componentes: string;
            /**
             * Duracao
             * @description Duração, como no livro (ex.: "Concentração, até 1 minuto")
             */
            duracao: string;
            /**
             * Descricao
             * @description Descrição da magia
             */
            descricao: string;
            /**
             * Circulo Superior
             * @description Texto de "Usando um Espaço de Magia de Círculo Superior"; nulo se não houver
             */
            circulo_superior?: string | null;
            /**
             * Aprimoramento Truque
             * @description Texto de "Aprimoramento de Truque"; nulo se não houver
             */
            aprimoramento_truque?: string | null;
            /**
             * Tabelas
             * @description Tabelas da magia; vazia quando não há
             */
            tabelas?: components["schemas"]["Tabela"][];
        };
        /**
         * MagiasNivel
         * @description Linha da tabela de magias da subclasse (ex.: "Magias de Domínio da Guerra").
         */
        MagiasNivel: {
            /**
             * Nivel
             * @description Nível da classe a partir do qual as magias ficam preparadas
             */
            nivel: number;
            /**
             * Magias
             * @description Magias sempre preparadas, como no livro
             */
            magias: string[];
        };
        /**
         * NivelClasse
         * @description Linha da tabela "Características de <Classe>" para um nível.
         */
        NivelClasse: {
            /**
             * Nivel
             * @description Nível da classe
             */
            nivel: number;
            /**
             * Bonus Proficiencia
             * @description Bônus de Proficiência no nível
             */
            bonus_proficiencia: number;
            /**
             * Caracteristicas
             * @description Características de classe obtidas no nível; vazia onde o livro mostra "—"
             */
            caracteristicas?: string[];
            /**
             * Colunas
             * @description Colunas específicas da classe (ex.: Fúrias, Truques, Magias Preparadas)
             */
            colunas?: components["schemas"]["ColunaProgressao"][];
            /**
             * Espacos Magia
             * @description Espaços de magia por círculo, a partir do 1º (0 onde o livro mostra "—"); vazia se não houver
             */
            espacos_magia?: number[];
        };
        /**
         * NivelOpcao
         * @description Benefício de uma opção a partir de um nível de personagem (ex.: uma linha da tabela Legados Ínferos).
         */
        NivelOpcao: {
            /**
             * Nivel
             * @description Nível de personagem em que o benefício é obtido
             */
            nivel: number;
            /**
             * Descricao
             * @description Descrição do benefício
             */
            descricao: string;
        };
        /**
         * OpcaoCaracteristica
         * @description Opção à escolha dentro de uma característica (ex.: os efeitos de Golpe Brutal).
         */
        OpcaoCaracteristica: {
            /**
             * Nome
             * @description Nome da opção
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição da opção
             */
            descricao: string;
        };
        /**
         * OpcaoEquipamento
         * @description Uma das opções de equipamento inicial do antecedente (ex.: a opção A).
         */
        OpcaoEquipamento: {
            /**
             * Opcao
             * @description Identificador da opção, como no livro (ex.: "A")
             */
            opcao: string;
            /**
             * Ouro
             * @description Peças de ouro (PO) da opção
             * @default 0
             */
            ouro: number;
            /**
             * Ferramentas
             * @description Ferramentas da opção
             */
            ferramentas?: components["schemas"]["ItemEquipamento"][];
            /**
             * Armas
             * @description Armas da opção
             */
            armas?: components["schemas"]["ItemEquipamento"][];
            /**
             * Outros
             * @description Demais itens da opção (ex.: algibeiras, roupas)
             */
            outros?: components["schemas"]["ItemEquipamento"][];
        };
        /**
         * OpcaoEquipamentoClasse
         * @description Uma das opções de equipamento inicial da classe (ex.: a opção A), que pode incluir armaduras.
         */
        OpcaoEquipamentoClasse: {
            /**
             * Opcao
             * @description Identificador da opção, como no livro (ex.: "A")
             */
            opcao: string;
            /**
             * Ouro
             * @description Peças de ouro (PO) da opção
             * @default 0
             */
            ouro: number;
            /**
             * Ferramentas
             * @description Ferramentas da opção
             */
            ferramentas?: components["schemas"]["ItemEquipamento"][];
            /**
             * Armas
             * @description Armas da opção
             */
            armas?: components["schemas"]["ItemEquipamento"][];
            /**
             * Outros
             * @description Demais itens da opção (ex.: algibeiras, roupas)
             */
            outros?: components["schemas"]["ItemEquipamento"][];
            /**
             * Armaduras
             * @description Armaduras e escudos da opção (ex.: "Escudo")
             */
            armaduras?: components["schemas"]["ItemEquipamento"][];
        };
        /**
         * OpcaoHabilidade
         * @description Opção à escolha dentro de uma habilidade (ex.: as transformações da Revelação Celestial).
         */
        OpcaoHabilidade: {
            /**
             * Nome
             * @description Nome da opção
             */
            nome: string;
            /**
             * Descricao
             * @description Descrição da opção; nula quando a opção só tem benefícios por nível
             */
            descricao?: string | null;
            /**
             * Por Nivel
             * @description Benefícios da opção por nível de personagem; vazia quando não há
             */
            por_nivel?: components["schemas"]["NivelOpcao"][];
        };
        /**
         * Propriedade
         * @description Propriedade de arma ou propriedade de maestria, como definida no capítulo 6.
         */
        Propriedade: {
            /**
             * Id
             * @description ID da propriedade
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome da propriedade (ex.: "Acuidade", "Afligir")
             */
            nome: string;
            /**
             * Tipo
             * @description "Propriedade" (coluna Propriedades) ou "Maestria" (propriedade de maestria)
             */
            tipo: string;
            /**
             * Descricao
             * @description Definição da propriedade
             */
            descricao: string;
        };
        /**
         * RespostaErro
         * @description Formato de todas as respostas de erro da API.
         */
        RespostaErro: {
            /**
             * Erro
             * @description Mensagem do erro
             */
            erro: string;
            /**
             * Codigo
             * @description Código estável do erro
             */
            codigo: string;
            /**
             * Detalhes
             * @description Problemas de validação, quando houver
             */
            detalhes?: components["schemas"]["DetalheValidacao"][] | null;
        };
        /**
         * ResumoClasse
         * @description Classe em cuja lista de magias a magia aparece; os detalhes ficam em /api/v1/classes/{id}.
         */
        ResumoClasse: {
            /**
             * Id
             * @description ID da classe
             */
            id: number;
            /**
             * Nome
             * @description Nome da classe
             */
            nome: string;
        };
        /**
         * ResumoFonte
         * @description Fonte de um registro, presente em todos os domínios.
         */
        ResumoFonte: {
            /**
             * Id
             * @description ID da fonte
             */
            id: number;
            /**
             * Nome
             * @description Nome da fonte (ex.: "Livro do Jogador (2024)")
             */
            nome: string;
            /**
             * Edicao
             * @description Edição: "5e" (2014), "5.5e" (2024) ou "homebrew"
             */
            edicao: string;
        };
        /**
         * ResumoSubclasse
         * @description Identificação de uma subclasse da classe; os detalhes ficam em /api/v1/subclasses/{id}.
         */
        ResumoSubclasse: {
            /**
             * Id
             * @description ID da subclasse
             */
            id: number;
            /**
             * Nome
             * @description Nome da subclasse
             */
            nome: string;
        };
        /**
         * Subclasse
         * @description Subclasse de uma classe de personagem, como retornada pela API.
         */
        Subclasse: {
            /**
             * Id
             * @description ID da subclasse
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Classe Id
             * @description ID da classe à qual a subclasse pertence
             */
            classe_id: number;
            /**
             * Nome
             * @description Nome da subclasse
             */
            nome: string;
            /**
             * Subtitulo
             * @description Subtítulo da subclasse, como no livro
             */
            subtitulo: string;
            /**
             * Descricao
             * @description Descrição da subclasse
             */
            descricao: string;
            /**
             * Magias Preparadas
             * @description Magias sempre preparadas por nível da classe; vazia quando a subclasse não tem
             */
            magias_preparadas: components["schemas"]["MagiasNivel"][];
            /**
             * Caracteristicas
             * @description Características da subclasse, ordenadas por nível
             */
            caracteristicas: components["schemas"]["Caracteristica"][];
        };
        /**
         * Tabela
         * @description Tabela apresentada dentro de um texto do livro (ex.: Fabricação Rápida).
         */
        Tabela: {
            /**
             * Titulo
             * @description Título da tabela, como no livro
             */
            titulo: string;
            /**
             * Colunas
             * @description Cabeçalho das colunas
             */
            colunas: string[];
            /**
             * Linhas
             * @description Linhas da tabela, com os valores na ordem das colunas
             */
            linhas: string[][];
        };
        /**
         * Talento
         * @description Talento, como retornado pela API.
         */
        Talento: {
            /**
             * Id
             * @description ID do talento
             */
            id: number;
            /** @description Fonte do registro (livro ou homebrew) */
            fonte: components["schemas"]["ResumoFonte"];
            /**
             * Nome
             * @description Nome do talento
             */
            nome: string;
            /**
             * Categoria
             * @description Categoria, como no livro (ex.: "Origem", "Geral"); nula nos talentos de 2014
             */
            categoria?: string | null;
            /**
             * Pre Requisito
             * @description Pré-requisito, como no livro (ex.: "Nível 4 ou superior"); nulo se não houver
             */
            pre_requisito?: string | null;
            /**
             * Descricao
             * @description Texto do talento antes dos benefícios nomeados
             */
            descricao: string;
            /**
             * Beneficios
             * @description Benefícios nomeados do talento; vazia quando o texto não os separa
             */
            beneficios?: components["schemas"]["Beneficio"][];
            /**
             * Repetivel
             * @description Texto da subseção "Repetível"; nulo se o talento não for repetível
             */
            repetivel?: string | null;
            /**
             * Tabelas
             * @description Tabelas do talento; vazia quando não há
             */
            tabelas?: components["schemas"]["Tabela"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_antecedentes_api_v1_antecedentes_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Antecedente"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_antecedente_api_v1_antecedentes__antecedente_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                antecedente_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Antecedente"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_classes_api_v1_classes_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Classe"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_classe_api_v1_classes__classe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Classe"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_criaturas_api_v1_criaturas_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Criatura"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_criatura_api_v1_criaturas__criatura_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criatura_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Criatura"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_armas_api_v1_equipamentos_armas_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Arma"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_arma_api_v1_equipamentos_armas__arma_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                arma_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Arma"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_armaduras_api_v1_equipamentos_armaduras_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Armadura"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_armadura_api_v1_equipamentos_armaduras__armadura_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                armadura_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Armadura"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_ferramentas_api_v1_equipamentos_ferramentas_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ferramenta"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_ferramenta_api_v1_equipamentos_ferramentas__ferramenta_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ferramenta_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ferramenta"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_itens_api_v1_equipamentos_itens_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemAventura"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_item_api_v1_equipamentos_itens__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemAventura"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_propriedades_api_v1_equipamentos_propriedades_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Propriedade"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_propriedade_api_v1_equipamentos_propriedades__propriedade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propriedade_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Propriedade"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_especies_api_v1_especies_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Especie"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_especie_api_v1_especies__especie_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                especie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Especie"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_fontes_api_v1_fontes_get: {
        parameters: {
            query?: {
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fonte"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_fonte_api_v1_fontes__fonte_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fonte_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fonte"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_magias_api_v1_magias_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Filtra pelo círculo (0 para truques) */
                circulo?: number | null;
                /** @description Filtra pelas magias da lista de uma classe */
                classe_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Magia"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_magia_api_v1_magias__magia_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                magia_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Magia"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_subclasses_api_v1_subclasses_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Filtra pelas subclasses de uma classe */
                classe_id?: number | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subclasse"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_subclasse_api_v1_subclasses__subclasse_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subclasse_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subclasse"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    listar_talentos_api_v1_talentos_get: {
        parameters: {
            query?: {
                /** @description Filtra por trecho do nome, sem diferenciar maiúsculas nem acentos ("acido" acha "Ácido") */
                nome?: string | null;
                /** @description Filtra pela fonte (veja /api/v1/fontes) */
                fonte_id?: number | null;
                /** @description Filtra pela categoria, exatamente como no livro (ex.: "Origem") */
                categoria?: string | null;
                /** @description Número da página */
                pagina?: number;
                /** @description Itens por página */
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Talento"][];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
    buscar_talento_api_v1_talentos__talento_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                talento_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Talento"];
                };
            };
            /** @description Recurso não encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Parâmetro inválido */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
            /** @description Erro interno inesperado */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaErro"];
                };
            };
        };
    };
}
